### ISSUE TITLE
Stand alone presentation + printout

### ISSUE THREAD

**Issue by paddelkraft** [webpro/reveal-md#105]
The way I use reveal-md is that i write notes of what i want to talk about and by doing that in markdown it is easy to pressent it. I love this way of working and it works fine as long as you do not need to share the presentations or you can host the presentation somewhere.

Unfortunately this is often not possible for me as the presentations might include potentially sensitive information and the only hosting option i have inside company borders are Sharepoint and confluence.

To solve this i have been thinking creating a standalone presentation output (notes do not work). And a printout that renders the markdown into an ordinary html that is also stand alone. So i can share individual files that people can view easily in their browsers without installing anything. 

would these   features make sense as part of reveal-md?

//Magnus

**Comment by webpro** [comment]
Sounds like a good idea. Maybe something like [inliner](https://github.com/remy/inliner) can do this. I wouldn't mind if the static site generator always generates a single stand-alone file. This would replace #103.

**Comment by webpro** [comment]
Just tried this, and inliner seems to work well (together with the inlined image feature), at least from the command line. From the generated site folder:

```
inliner index.html > standalone.html
```

**Comment by paddelkraft** [comment]
Yes i got that to work also but it demanded that all references to js,css and font files that is suposed to be aligned needs to be referenced with proper html tags. 

referencing all files from cdnjs seems like a much nicer solution

pull request will come soon

**Comment by webpro** [comment]
Using a CDN would mean an internet connection is required, which means a serious breaking change in certain cases (firewalls, proxies, whatnot).

**Comment by paddelkraft** [comment]
Now there is a pull request.

Did this with inliner first it was quite a hassle .
It needed a custom template and inliner creates some problems with base directories and so on to inline files. 

in the  end  I chose this way as it saved 3.5 mb in file size and seemed like a much cleaner solution and i assumed most people would be connected and not have a problem with reaching a cdn, (i might be wrong)

but the stand alone is a separate command `--standalone` so nothing that have worked before is broken (that Im aware of).

**Comment by webpro** [comment]
OK let's discuss it over there (#108), I'll review it soon.
