### ISSUE TITLE
Math equations render failed!

### ISSUE THREAD

**Issue by IvanJobs** [webpro/reveal-md#109]
HI all,

I'm using reveal-md to markdown my presentation. I have a bunch of math equations to write. Things went well until I encountered equation below:
> $$
> k<i+1\arrowvert P_{k-1}\sqsupset P_{m-1}
> $$

it just cannot be rendered. But if I change to Mathjax official site, it was good.

 I made a little bit of modification: 

> $$
> k<i+1\arrowvert P_{k-1}\sqsupset P_m
> $$

This is ok in reveal-md.

Something must be wrong somewhere.

**Comment by webpro** [comment]
FYI, I'm not sure why this last part `P_{m-1}` is problematic.

**Comment by hholst80** [comment]
Another repro

    $$
    S_m S_m
    $$

works.

    $$
    S_{m} S_m
    $$

works.

    $$
    S_m S_{m}
    $$

works.

But this breaks:

    $$
    S_{m} S_{m}
    $$

So its "definitely" something related to the curly braces and the _ operator. "S" can be any operator like \int or whatnot. The  ^ operator works just fine:

    $$
    \int^{a} \int^{b}
    $$ 

I think that this final example reveals what might be going on:

    $$
    {A}_{CURLEY?}_{C}
    $$ 

![image](https://cloud.githubusercontent.com/assets/6200749/25785196/e6e2dcd6-337a-11e7-895f-0bac849dcf37.png)

**Comment by wwoods** [comment]
For the record, I typically need to escape my `_` with reveal-md: `$\hat{I}\_{vgnd}V\_t$` rather than `$\hat{I}_{vgnd}V_t$`.  Then it works fine.  I believe it is because markdown converts the pair of `_`'s to italic, which MathJAX ignores.

**Comment by webpro** [comment]
Closing this, as it seems it's not a reveal-md issue, and there is a work-around (escaping).

**Comment by doosik71** [comment]
I use markdown format to produce not only reveal-md presentation but also pandoc pdf and gitbook.
Pandoc and gitbook works fine without escaping underscore in math expression.
This problem only happens in reveal-md.
If I escape underscore to work around for reveal-md, it breaks rendering in pandoc and gitbook.
Reveal-md need to solve this problem.

**Comment by webpro** [comment]
@doosik71 It's not an issue in reveal-md itself, it's in the reveal.js Markdown plugin (https://github.com/hakimel/reveal.js/tree/master/plugin/markdown).
