### ISSUE TITLE
div tags and scripts

### ISSUE THREAD

**Issue by hholst80** [webpro/reveal-md#112]
Is this supposed to work? It would be very cool if we could include d3.js graphics inside our reveal-md presentations!

slide.md:

```
# A div tag showing some Venn diagram
<div id="venn"></div>
```

```
root@puff:/data# ls *.js
d3.v4.min.js  myvenn.js  venn.js
root@puff:/data# cat myvenn.js
// define sets and set set intersections
var sets = [ {sets: ['A'], size: 12},
             {sets: ['B'], size: 12},
             {sets: ['A','B'], size: 2}];

var chart = venn.VennDiagram();
d3.select("#venn").datum(sets).call(chart);

root@puff:/data# node_modules/.bin/reveal-md -w --scripts d3.v4.min.js,venn.js,myvenn.js
Reveal-server started at http://localhost:1948
```

Example taken from http://benfred.github.io/venn.js/examples/simple.html

**Comment by webpro** [comment]
Yes, scripts are supposed to work. They're added as regular `<script src="venn.js">` tags in the markup at the end of the `<body>`: https://github.com/webpro/reveal-md/blob/master/lib/template/reveal.html#L73-L75

**Comment by webpro** [comment]
You can now also use [custom templates](https://github.com/webpro/reveal-md#custom-template).
