### ISSUE TITLE
Including images from subdirectories

### ISSUE THREAD

**Issue by slhck** [webpro/reveal-md#115]
Perhaps I'm missing something obvious, but I'm not able to include images from subfolders of the one where my slides are saved.

In my slides (`slides.md`) I have:

```
![](./assets/vqeg.jpg)
```

```
reveal-md slides.md
Error: ENOENT: no such file or directory, stat '/home/werner/slides/vqeg.jpg'
    at Error (native)
```

Seems that it's trying to serve the image from the same directory where `slides.md` is, but it's actually in a directory called `assets`.

**Comment by webpro** [comment]
Thanks for reporting this. Looks like an issue with `imgPath` around https://github.com/webpro/reveal-md/blob/4655f9d82a0357e4171e0426b34b73455b6d5304/lib/static.js#L8-L28. If you or someone else could come up with a PR to fix this, that would be great.

**Comment by slhck** [comment]
Isn't this code just related to static HTML file generation? That code snippet looks alright to me; it doesn't seem to strip any components from the image path, at least.

I have close to zero experience in debugging node.js apps, so I can't promise if I can find something easily.

**Comment by webpro** [comment]
Let's close this in favor of #116, and discuss over there if needed.
