### ISSUE TITLE
Problem with markdown-file containing BOM

### ISSUE THREAD

**Issue by ma4a** [webpro/reveal-md#118]
Running reveal-md 0.3.1 on Linux I recognized a problem when the UTF8 markdown-file contains BOM. 

The used markdown-file:
```
---
title: test
theme: solarized
revealOptions:
    transition: 'convex'
---

# test

reveal-md
```
The YAML Front matter header isn't recognized as header anymore. The options are ignored and another first slide with the header-content is added as you can see:

![243ad02f-312d-421d-bd3d-455efc742420](https://user-images.githubusercontent.com/1401431/27129822-f794b85a-5103-11e7-8ebf-f9d45dfbd1e0.png)

After converting the file to UTF-8 w/o BOM everything seems fine:
![6ae505fd-c37a-4090-893e-84d0d619ae3a](https://user-images.githubusercontent.com/1401431/27130098-0c6312d0-5105-11e7-8cdd-be820f7b25d2.png)

**Comment by webpro** [comment]
Fixed in [v0.4.2](https://github.com/webpro/reveal-md/releases/tag/0.4.2).
