### ISSUE TITLE
Print to PDF fails if there are spaces in the name

### ISSUE THREAD

**Issue by Grayda** [webpro/reveal-md#119]
I'm trying to run this command on WIndows:

`reveal-md "Introduction to git.md" --print "Introduction to git.md.pdf"`

And it's giving me this error:

> Error: Command failed: phantomjs C:\Users\Grayda\AppData\Roaming\npm\node_modules\reveal-md\node_modules\reveal.js\plugin\print-pdf\print-pdf.js http://localhost:1948/Introduction to git.md?print-pdf Introduction to git.pdf

The issue is obviously the spaces, because if I rename the file to `Introduction%20to%20git.md`, then everything works as expected.

This also happens on Linux (I'm actually trying to use this as part of a CI script)

I'm running `0.3.1` on both Windows 10, and a Docker container (`node:latest`)

**Comment by batjko** [comment]
Should be easily fixed by adding some quotes around the filename [here](https://github.com/webpro/reveal-md/blob/a0158200c6e430a7d128006be7142047285a0536/lib/print.js#L24).

**Comment by webpro** [comment]
Fixed in [v0.4.2](https://github.com/webpro/reveal-md/releases/tag/0.4.2).
