### ISSUE TITLE
Advanced markdown examples?

### ISSUE THREAD

**Issue by abelnation** [webpro/reveal-md#12]
I'm having trouble figuring out how to use some of the advanced markdown features.  I've tried examples as shown on the reveal.js site, e.g.:

```
- Item 1 <!-- .element: class="fragment" data-fragment-index="2" -->
- Item 2 <!-- .element: class="fragment" data-fragment-index="1" -->
```

Can you provide some examples in markdown of how to do fragments and vertical slides in markdown?

Thanks!

**Comment by firoozye** [comment]
@webpro Fragments seem to be a very useful way of presenting. Reveal-md already adds to MD by giving ```---``` and ```----```  other meanings, I would think it makes sense to add a special character or characters to introduce fragments, i.e.,

```
* This gets displayed first
    * This gets displayed at the same time
    + This gets displayed as a fragment, i.e., displayed second
    + This gets displayed third
    * Maybe this gets displayed third also? 
```

I would think it's feasible but only viable if there are some limitations, i.e., the bullets get displayed sequentially.

In reveal.js you can choose arbitrary orders for fragments to be displayed, but I think it's not possible to easily accommodate all fragment types in a simple addition to MD. Just some thoughts.

**Comment by masasin** [comment]
@firoozye You could possibly do this:

    * This gets displayed first
        * This gets displayed at the same time
        + This gets displayed as a fragment, i.e., displayed second
        + This gets displayed third
        +! This gets displayed third too
        +2 This gets displayed after +1
        +1 This gets displayed after the third ones, but before +2
        * This gets displayed at the same time

**Comment by safareli** [comment]
you can just write html in md. this will work:

```
<div class="fragment" data-fragment-index="3">Appears last</div>
<div class="fragment" data-fragment-index="1">Appears first</div>
<div class="fragment" data-fragment-index="2">Appears second</div>
```

**Comment by automaticgiant** [comment]
i think there's probably an accessible compromise - supporting a useful subset of the fragment feature in markdown is probably a more expedient/pragmatic value-add than getting into the weeds of the expressivity of the full fragments code, but that's again what much of the markdown syntax is trying to do - support a generous subset and make our lives easier.
