### ISSUE TITLE
Export a markdown slideshow to a continuous html file

### ISSUE THREAD

**Issue by boileaum** [webpro/reveal-md#120]
For training purpose, it would be nice to have two renderings of the same markdown source:
1. a slideshow for the teacher
2. a continuous html file (typically rendered in github-markdown style) for the students that would continuously scroll the document, copy-pasting some code blocks. 

This would require to remove the slides separators and may run together with the `--static` option.

**Comment by webpro** [comment]
An option is to include custom script (`--script`) and styles (`--css`) to override the normal behavior/styling of reveal.js.

Check out reveal.js settings for what you can configure out of the box: https://github.com/hakimel/reveal.js#configuration (put this in a `reveal.json` file). Together with configuring non-existing slide separators (to fake a single slide), you might even get away with styling only.

**Comment by boileaum** [comment]
Thank you for your suggestion! As I'm not a specialist of reveal.js, I found another solution using pandoc:
```
sed s/---//g test-reveal.md | pandoc -s -t html5 -c pandoc.css -o index.html
```
Using `doctoc`, one may also insert a table of content.

**Comment by webpro** [comment]
Sounds great!
