### ISSUE TITLE
Making slide background part of a custom theme

### ISSUE THREAD

**Issue by frankscholten** [webpro/reveal-md#121]
Seems there is no mailinglist for this project so I will ask a question by opening an issue.

I have added the following snippet in my slides to add a background image

```
<!-- .slide: data-background="./resources/slide-background.svg" -->
```

and this works but it seems I have to repeat that for each slide. What kind changes should I make to the css theme so that each slide has this background by default? 

Great project, keep up the good work!

**Comment by webpro** [comment]
You can set a background image in CSS, right?

**Comment by frankscholten** [comment]
I added this snippet

```
.reveal {
  font-family: "Roboto", Helvetica, sans-serif;
  font-size: 38px;
  font-weight: normal;
  color: #1c98e6;
  background-image: url('/resources/slide-background.svg');
  background-repeat: no-repeat;
  background-position: center center;
  background-attachment: fixed;
  background-size: cover;
}
```
which works but when I want to change the background of the title slide and add this

```
<!-- .slide: data-background="./resources/title-background.svg" -->
```

the slide will have both backgrounds applied to it. Any idea how I can make it so it uses a default background unless overridden through the tag above?

**Comment by webpro** [comment]
Perhaps reveal.js adds a `data-background` property or something to the HTML, which you can use to disable the CSS background image.

**Comment by frankscholten** [comment]
It does not seem to add a `data-background` property unless I add it myself via a comment. Could I write a script that sets the background for the first slide and a different background for the other slides? Which property or conditional value can I use to determine when to set which background?

**Comment by webpro** [comment]
You can use `--script` to include custom scripts. Sounds like something of a `.slides section:first-child` CSS selector could to the trick as well.

**Comment by frankscholten** [comment]
@moretea and I figured it out. We added this snippet:

```
.reveal > .backgrounds > div {
   background-image: url('slide-background.svg');
 }
 
 .reveal > .backgrounds > div:first-child {
   background-image: url('title-background.svg');
 }
```

This way every slide uses te same background image except the title slide which has its own image.

Thanks for helping out @webpro!
