### ISSUE TITLE
considering add chrome printing

### ISSUE THREAD

**Issue by jzz4012650** [webpro/reveal-md#122]
I found that [reveal.js](https://github.com/hakimel/reveal.js) has the feature of printing PDF with chrome browser. 

Since this repo is based on reveal.js, how about adding this [feature](https://github.com/hakimel/reveal.js#pdf-export)? 

It seems PDF printed from chrome looks nicer than from Phantomjs (just personal opinion).

**Comment by webpro** [comment]
Resolved by #125
