### ISSUE TITLE
Chrome ?print-pdf link broken between 0.0.34 and 0.1.1... Seems broken since?

### ISSUE THREAD

**Issue by wwoods** [webpro/reveal-md#127]
This appears to be due to the fact that ".reveal" does not get `overflow: visible` assigned to it.  Also, pdf-pages are not broken correctly.  Also, any slide backgrounds are not rendering correctly any longer.

This all last worked in 0.0.34.  0.1.0 did not display slides correctly.  0.1.1 demonstrates the broken behavior.

**Comment by wwoods** [comment]
This would be fixed by #125

**Comment by breschke** [comment]
No longer working--see #139
