### ISSUE TITLE
How to run the server on specific IP

### ISSUE THREAD

**Issue by singh1114** [webpro/reveal-md#130]
Hello there!

I have been using your services from a long time and found them very amazing. I was trying to run reveal-md on my server. I apply the command:
`reveal-md abc.md`
It runs on `localhost:1948`. I want it to run on `my_server_ip:PORT`. How can I do that?

Thanks for your help guys.

**Comment by singh1114** [comment]
Sorry for the inconvineince, I found the solution. 
use this command:
`reveal-md -h server_ip -p PORT file_name.md`

**Comment by webpro** [comment]
Glad you've found it :-)
