### ISSUE TITLE
Unable to generate PDF

### ISSUE THREAD

**Issue by utrescu** [webpro/reveal-md#131]
When I try to generate the pdf the `--print` option is ignored (same with -P)

    $ reveal-md post.md --print post.pdf
    Reveal-server started at http://localhost:1948

I'm using Fedora Linux and I have node 8.4.0 (via nvm) and phantomjs 2.1.7 ... 

    $ npm list -g --depth=0
    /home/user/.nvm/versions/node/v8.4.0/lib
    ├── ...
    ├── npm@5.3.0
    ├── phantomjs@2.1.7
    ├── reveal-md@0.4.0
    └── typescript@2.4.2

I have some incompatible versions, missed some dependencies, or it's a bug?

**Comment by webpro** [comment]
Hi @utrescu, thanks for the bug report. This was introduced in v0.4.0. It is now fixed in [v0.4.1](https://github.com/webpro/reveal-md/releases/tag/0.4.1).
