### ISSUE TITLE
Existing way to add social links

### ISSUE THREAD

**Issue by grokify** [webpro/reveal-md#132]
Is there an existing way to add social links like Twitter, Facebook, Github, etc.?

If not, are there any pointers on the best way to add this?

**Comment by webpro** [comment]
Hi @grokify. You can just use links and images in Markdown, so I'm not sure what you mean?

**Comment by grokify** [comment]
I was thinking of adding a short string of icons in a corner say upper right or lower left corner of each page, similar to the navigation controls.

**Comment by webpro** [comment]
You could use a [custom template](https://github.com/webpro/reveal-md#custom-template) for this.
