### ISSUE TITLE
no code samples

### ISSUE THREAD

**Issue by ChrisJefferson** [webpro/reveal-md#134]
How do I embed code, and pick the language? This doesn't seem to be mentioned in either the docs, or the examples.

**Comment by grokify** [comment]
See this:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by webpro** [comment]
Thanks @grokify. This is a feature of reveal.js itself, so please also see e.g. [reveal.js#code-syntax-highlighting](https://github.com/hakimel/reveal.js#code-syntax-highlighting)
