### ISSUE TITLE
Gitbook plugins inside revel-md

### ISSUE THREAD

**Issue by juanda99** [webpro/reveal-md#138]
I've seen some issues about reveal-md plugins, but I think is not just the same case.
I'm using [gitbook plugin youtube](https://www.npmjs.com/package/gitbook-plugin-youtube), however it renders the video when using gitbook serve, but not when using reveal-md (just print the text).

**Comment by webpro** [comment]
Hi, @juanda99. This doesn't look like a reveal.js plugin, or is it? Therefore I'm closing this issue, but feel free to discuss further.
