### ISSUE TITLE
Documentation for custom templates

### ISSUE THREAD

**Issue by fdw** [webpro/reveal-md#142]
I would like to write my own custom template (f.e. with specific scripts). However, I could not find any information on how to do that. Could you please point me in the right direction?

**Comment by webpro** [comment]
Please see https://github.com/webpro/reveal-md#custom-template

Let me know how/where you need more help.

**Comment by fdw** [comment]
Thank you :)

Unfortunately, the link only explains how to use a custom template, but not how to write one. My use case is that I already have an old presentation with a specific style and scripts that I'd like to re-use, but I prefer to write the content with markdown. Therefore, it would make the most sense if I could convert the existing presentation into a template and use reveal-md to generate the content. So far, I found no documentation on how a template should look, what it requires, etc.

**Comment by webpro** [comment]
This section links to the default template used here with reveal-md: https://github.com/webpro/reveal-md/blob/master/lib/template/reveal.html

I think this template be a good starting point.

Just saying: you can use `--scripts` and `--css` to inject custom scripts and styling.

**Comment by fdw** [comment]
I'll have a look at the `--scripts` and `--css` flags, thanks!

However, the default template didn't really help. What exactly is the `{{{base}}}` directory? What does `{{#cssPaths}}` do? Some more documentation about the keywords would be very helpful.

**Comment by webpro** [comment]
To provide a little bit of background here: all of the features mentioned in this ticket have been added by others with pull requests. I was fine with that, as they weren't adding much complexity (especially the custom template). Unfortunately, documentation in general isn't very comprehensive. Specifically the (custom) template requires some knowledge about the rest of the codebase.

Apologies for leaving you a bit in the dark here. Maybe with some trial and error (by inspecting the rendered HTML and tweaking the template) you get it to work the way you want it to. Also, feel free to ask further questions and I or others may be able to help you out soon.
