### ISSUE TITLE
Custom Theme not working with direct access to slides in subfolder

### ISSUE THREAD

**Issue by singingknight** [webpro/reveal-md#145]
With a structure like this:

    +- reveal-md.json
    +-- theme
    |   +-- mytheme.css
    +-- presentation1
    |   +-- slides.md
    |   +-- img1.jpg
    |   +-- img2.jpg
    +-- presentation2
        +-- slides.md
        +-- img1.jpg
        +-- img2.jpg

If I run `reveal-md --theme mytheme.css presentation1/slides.md` then it can't find `/theme/mytheme.css`, because it's looking inside presentation1

One solution could be to load it from /assets/theme/mytheme.css (I can provide pull request)

**Comment by webpro** [comment]
I've just fixed/changed this behavior in [v0.5.0](https://github.com/webpro/reveal-md/releases/tag/0.5.0). So the command would become:

```
reveal-md --theme theme/mytheme.css presentation1/slides.md
```

Also see https://github.com/webpro/reveal-md#theme. Let me know if you still have any issues.
