### ISSUE TITLE
pdf export, no math mode

### ISSUE THREAD

**Issue by janstuemmel** [webpro/reveal-md#149]
when i export to pdf, no math formulas will be drawn, its just mathML text.

**Comment by MichielStock** [comment]
Same thing here! Does reveal-js have the same bug?

**Comment by janstuemmel** [comment]
it's a revealjs bug, in the print-pdf.js plugin

**Comment by maiermic** [comment]
I use [decktape](https://github.com/astefanutti/decktape) in the meantime:

```
decktape reveal http://localhost:1948/slides.md slides.pdf
```

**Comment by webpro** [comment]
Since this is a bug in a reveal.js plugin, I'm going to close this issue. Please note that reveal-md v2 should generate better PDFs, but I'm afraid it's not relevant for this issue.
