### ISSUE TITLE
PDF export puzzled pages

### ISSUE THREAD

**Issue by fungs** [webpro/reveal-md#152]
Installed version 1.0.0 via npm and phantomjs 1.9.0 and pages are not printed to pdf correctly, slides extend over multiple pages.

**Comment by webpro** [comment]
There have been multiple issues reported regarding PDF output/printing. Please look them up in the issues (https://github.com/webpro/reveal-md/search?q=print&type=Issues) and see if there's anything of help, or if you could help out in any way. Closing this as it's a duplicate of other tickets.
