### ISSUE TITLE
Command line parameters precedence over hardcoded parameters

### ISSUE THREAD

**Issue by fungs** [webpro/reveal-md#153]
If I set a theme in the markdown file metadata and specify a different theme on the command line, it still uses the hardcoded one. Usually, and this makes most sense IMO, command line parameters should overwrite the others, to be able to quickly force a theme change.

Version of reveal-md is 1.0.0

**Comment by webpro** [comment]
Agreed, CLI arguments should overide defaults.

**Comment by webpro** [comment]
Thanks, this will be in the next release.
