### ISSUE TITLE
Reloading unrenders math formulas

### ISSUE THREAD

**Issue by fungs** [webpro/reveal-md#154]
In many situations, when reloading the presentation either using the -w parameter or manually displays inline and block math code as text instead of rendering.

Version of reveal-md was 1.0.0

**Comment by fungs** [comment]
This was true in recent firefox and chromium, so it should not be a browser issue.

**Comment by webpro** [comment]
Can you please verify whether this is a reveal-md issue, or of reveal.js itself?

**Comment by fungs** [comment]
how do I best do that? I'm not much into web programming...

**Comment by webpro** [comment]
Can you please share an example that shows the issue?

**Comment by fungs** [comment]
Today I tried to reproduce with current Firefox and Chromium but it didn't show again.

**Comment by webpro** [comment]
Then I'm going to close this issue. Feel free to open a new ticket if you encounter any issues.
