### ISSUE TITLE
SVG images missing in static site

### ISSUE THREAD

**Issue by fungs** [webpro/reveal-md#155]
I included some SVG images which are missing when exporting the presentation to a folder using the `--static` command line parameter. They are there, when I run the presentation locally.

Version is 1.0.0

**Comment by webpro** [comment]
That's indeed not supported (yet). Maybe you can take advantage of the new `--staticDirs` feature introduced in v1.1.0.

**Comment by fungs** [comment]
What does `--staticDirs` do?

I found the best solution to exporting the presentation to just save it from the web browser which seemed to include everything.

**Comment by webpro** [comment]
You can copy extra directories when using `--static`.

Happy to hear you've found a solution.
