### ISSUE TITLE
Speaker view shows next slide (vertical) but not horizontal

### ISSUE THREAD

**Issue by iranzo** [webpro/reveal-md#156]
Hi,
When using the slides I'm using the horizontal navigation for main topics and vertical for going deeper, but the speaker view shows the slides in vertical as next slide.

I think it should  use another field to show both next in horizontal and down in vertical so it's easier to decide *on the go* if it's better, based on audience, timing, etc to move horizontally to next topic or dig deeper.

**Comment by webpro** [comment]
Can you please verify this is an issue with reveal-md, or with reveal.js itself?

**Comment by iranzo** [comment]
Well, tbh showing either the one down on next would be good, but as we do have both possibilities to move right or down, shouldn't we have another section in 'speaker view' about which one is next in vertical and in horizontal?

For me it was more like a Request for Enhancement than a bug

If you want me to run some specific commands to validate, let me know how should I proceed.

Thanks a lot!
Pablo

**Comment by webpro** [comment]
Right, I understand. Well, reveal-md is some kind of server to present Markdown files using [reveal.js](https://revealjs.com), the "actual" project. Please discuss this over there. Thanks!
