### ISSUE TITLE
Custom HTML template not working as described

### ISSUE THREAD

**Issue by MichelGabriel** [webpro/reveal-md#157]
Hi,

I noticed that the use of '--reveal-template' as described in the documentation is not working. In 'cli.js' another name is used: '--template': https://github.com/webpro/reveal-md/blob/f6ae20139a49f1f45b48698dfafa009bb3078e72/bin/cli.js#L47

**Comment by webpro** [comment]
Thanks, @MichelGabriel! Can you please open a PR to fix this?

**Comment by MichelGabriel** [comment]
Hi @webpro,

Yes I can, would you like to have a fix for the documentation or the javascript file?

**Comment by webpro** [comment]
Just made the change, thanks :-)
