### ISSUE TITLE
Highlight Theme cannot be a relative path

### ISSUE THREAD

**Issue by mhartington** [webpro/reveal-md#158]
Hi there! 

First off, thanks for reveal-md!

Issue: Specifying a highlightTheme using a relative path does not work.

In a reveal-md.json config,  

```json
{
  "title": "Stencil",
  "theme": "theme/stencil.css",
  "highlightTheme": "theme/oceanicnext.css"
}
``` 

Passing a custom reveal theme works, but it does not work for highlightTheme, which seems like it should.  Would it be possible to add this?

**Comment by webpro** [comment]
Sorry, a custom highlight theme isn't supported (yet). To be fair, it's also not documented like that. Feel free to open a PR for this.

**Comment by haykh** [comment]
Not sure if this is still a relevant issue, but you can now put the `css` of the syntax highlight into `./css/highlights/` (i.e., copy from `./node_modules/highlights.js/styles/`) and then specify the theme by just doing (all the themes are [here](https://highlightjs.org/static/demo/)):
```markdown
---
theme: night
highlightTheme: atom-one-dark
---
```

**Comment by LateNightIceCream** [comment]
Just as an update in case anybody comes across this issue:
I managed to get it working by putting the highlight css in `css/highlight/` (not `.css/highlights/`) and then doing the same things as [haykh](https://github.com/webpro/reveal-md/issues/158#issuecomment-976158448)
