### ISSUE TITLE
exit on json parse error

### ISSUE THREAD

**Issue by HansHammel** [webpro/reveal-md#159]
app swallows json errors on at least reveal-md.json

**Comment by webpro** [comment]
As this file is not required to exist, reveal-md indeed swallows the error. I agree it would be better to report JSON parsing issues if the file exists.

You can use `DEBUG=reveal-md reveal-md [...]` for debugging (https://github.com/webpro/reveal-md/blob/master/CONTRIBUTING.md#-file-a-bug). This would reveal the issue.
