### ISSUE TITLE
notesSeparator has no effect

### ISSUE THREAD

**Issue by HansHammel** [webpro/reveal-md#160]
`notesSeparator` has no effect in reveal-md.json not yaml header

**Comment by webpro** [comment]
Do you mean it has no effect in either way, or not at all?

**Comment by webpro** [comment]
Hi, been working on a rewrite, which should improve things. Could you guys please give this a shot? You can install with:

```
npm install --global reveal-md@rc
```

Let me know any issues you may encounter, and we can fix up before a final v2.

**Comment by webpro** [comment]
Can you guys please try again with version 2.0.0-rc.4? Feel free to (re)open tickets if any issues occur.

```
npm install reveal-md@rc --global
```
