### ISSUE TITLE
simplify regex matching in defaults.json

### ISSUE THREAD

**Issue by HansHammel** [webpro/reveal-md#161]
I found `"^(\r\n?|\n)---(\r\n?|\n)$"` in defaults.json
This is IHMO wrong. The `?` applies to `\n`
can be simplified to  `"^(\r?\n)---(\r?\n)$"`
if you can omit the group matches go with `"^\r?\n---\r?\n$"`
but even that is wrong (for multiline matching), so, no wonder even this works: `"\r?\n---\r?\n"` <- IMHO best solution

**Comment by webpro** [comment]
Nice find, @HansHammel. I totally agree. Could you please open a PR for this?

**Comment by HansHammel** [comment]
I am afraid not - currently focused on .net, just doing some node monkey patching on my current setup.

**Comment by webpro** [comment]
No problem, thanks for reporting. It will be in the next release.
