### ISSUE TITLE
Path with space on windows

### ISSUE THREAD

**Issue by malys** [webpro/reveal-md#163]
Hi,
Thank you for developping this tool.
I have detected a bug:
https://github.com/webpro/reveal-md/blob/5d9d83a65340e6c10e1dd0809f11dc5a5c76d287/lib/print.js#L20

To protect your code of windows path with space (ex: c:\program files\), we have to add " around your path:
```js
`phantomjs "${printPluginPath}" "${url}?print-pdf" "${pdfFilename}.pdf"`
```

**Comment by webpro** [comment]
Hi @malys, thanks for the report. This should be fixed with v2.0.0.
