### ISSUE TITLE
Live view does not use YAML front matter

### ISSUE THREAD

**Issue by matthjes** [webpro/reveal-md#165]
Hi,

The YAML front matter is not used when I run reveal-md in live mode, i.e. `reveal-md slideshow.md`, however, the front matter **is** used when I create static HTML files.

This is my simple file:
```
---                                                                            
title: Foobar                                                                                       
separator: <!--s-->                                                                                 
verticalSeparator: <!--v-->                                                                         
theme: solarized                                                                                    
revealOptions:                                                                                      
  transition: 'fade'                                                                              
---                                                                                                 
Foo                                                                                                 
                                                                                                    
Note: test note                                                                                     
                                                                                                    
<!--s-->                                                                                            
                                                                                                    
# Bar                                                                                               
                                                                                                    
<!--v-->                 
```

And this is the result:

![screenshot-2018-1-31 reveal-md](https://user-images.githubusercontent.com/1440866/35623610-89407d78-068c-11e8-9728-3d2a88ce4691.png)

Only `Foo` is shown, and I cannot go to the next slide.

Here is the same presentation, now generated as static HTML files:

![screenshot-2018-1-31 foobar 1](https://user-images.githubusercontent.com/1440866/35623707-d802085a-068c-11e8-8322-0b8e4366c539.png)

Now the theme is correct and I can switch to the next slide (see arrow).

I'm using Firefox 58.0.1 on Manjaro Linux.

**Comment by medains** [comment]
The live view and static apply options in a different order.

Options need to be applied consistently in this order (first encountered should be applied)
* command line overrides
* YAML headers
* defaults

There's quite a bit of work to fix this because the command line and defaults have been conflated, and the static and live view apply them in different orders.

I'll have a go at it if I find a bit of time to do so.

**Comment by psifertex** [comment]
Some updates to the documentation section on the YAML front-matter explaining that it only works in some modes would be very helpful (and would have saved me some time just now!)

**Comment by webpro** [comment]
Can you guys please try again with version 2.0.0-rc.4? Feel free to (re)open tickets if any issues occur.

```
npm install reveal-md@rc --global
```
