### ISSUE TITLE
Print to PDF command requires theme option

### ISSUE THREAD

**Issue by peckeltw** [webpro/reveal-md#168]
According to https://github.com/webpro/reveal-md#print-to-pdf printing to PDF is done by

`reveal-md slides.md --print slides.pdf`

This just creates a blank page with the black background. So I need to specify a theme, even the default one, to print to PDF successfully:

`reveal-md slides.md --theme black  --print slides.pdf`

**Comment by medains** [comment]
Related to #165 I expect.

**Comment by webpro** [comment]
Hi, been working on a rewrite, which should improve things. Could you guys please give this a shot? You can install with:

```
npm install --global reveal-md@rc
```

Let me know any issues you may encounter, and we can fix up before a final v2.

**Comment by peckeltw** [comment]
Hi @webpro,
thanks a lot, it is working now.

`reveal-md test.md --print test.pdf`

outputs

`Attempting to print "test.md?print-pdf" to filename "test.pdf" as PDF.
2
3 Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: {},
  pathname: 'test.md',
  path: 'test.md',
  href: 'test.md' }
4 '/Users/peckel/Src/talks/test.md'`

and creates a correct PDF file.

**Comment by webpro** [comment]
Thanks! Version 2 will be out soon.
