### ISSUE TITLE
YAML config in slides not loaded?

### ISSUE THREAD

**Issue by yanick** [webpro/reveal-md#177]
I don't know if this is caused by reveal-md itself or one of its dependencies, but with the latest
version of reveal-md, the YAML config in the slides don't seem to have any effect (I was modifying the `separator` and the `verticalSeparator`, amongst other things.

**Comment by yanick** [comment]
Did some regression, and the YAML config was loading in v0.5.0, v1.0.0, v1.1.0 and breaks in v1.1.1.

**Comment by jinwoo** [comment]
`title` doesn't seem to work either. `revealOptions` does seem to work though. At least its `transition` field works.

**Comment by humanfactors** [comment]
I cannot get `reveal-md -w slides.md` to read the theme defined in the YAML header. I can get this to work, however, by manually overriding with ` --theme $(THEME)`. On the other hand, `reveal-md --static` works just fine.

**Comment by webpro** [comment]
Hi, been working on a rewrite, which should improve things. Could you guys please give this a shot? You can install with:

```
npm install --global reveal-md@rc
```

Let me know any issues you may encounter, and we can fix up before a final v2.

**Comment by jinwoo** [comment]
I installed `reveal-md@rc` but it didn't respect `title` field of YAML either.

**Comment by webpro** [comment]
Could you please share your slides cq. a case for me to reproduce this issue?

**Comment by jinwoo** [comment]
Here's a pretty simple repro case.

```markdown
---
revealOptions:
  title: 'This is a title'
---

# A Header

*   Blah blah
```

```sh
$ reveal-md index.md
```

The title "This is a title" doesn't show on the browser tab. Instead it says "reveal-md".

But if you do
```sh
$ reveal-md index.md --title "This is a title"
```
, now the browser tab shows "This is a title".

**Comment by webpro** [comment]
Please refer to https://github.com/webpro/reveal-md#yaml-front-matter.

Only options specific to the reveal.js deck go in the `revealOptions` section (https://github.com/hakimel/reveal.js/#configuration).

**Comment by jinwoo** [comment]
Sorry about the wrong repro case. With the correct YAML, the current `reveal-md` fails to show the title but `reveal-md@rc` does show it. Thanks for the fix!
