### ISSUE TITLE
Static site with custom theme does not work

### ISSUE THREAD

**Issue by almondtools** [webpro/reveal-md#178]
The final index.html has the line:

./_assets/theme/custom.css

but the directory _assets does not exist. Copying the custom theme to _assets/theme makes it work.

OS: Windows

**Comment by webpro** [comment]
Hi, been working on a rewrite, which should improve things. Could you guys please give this a shot? You can install with:

```
npm install --global reveal-md@rc
```

Let me know any issues you may encounter, and we can fix up before a final v2.

**Comment by almondtools** [comment]
**Generating static sites for a custom theme:**

`reveal-md slides.md --theme theme/custom.css` --static` for static sites generation

the theme is not correctly displayed, the html contains a suspicious line `<link rel="stylesheet" href="./undefined" id="theme">`

**Generating static sites for a custom theme:**

`reveal-md slides.md --theme theme/custom.css` --print` for pdf generation

fails with a long error message.

Yet it is not really good documented how a custom theme can be included properly. So maybe I did it the wrong way. Yet `reveal-md slides.md --theme theme/custom.css` works fine.

**Comment by webpro** [comment]
Can you guys please try again with version 2.0.0-rc.4? Feel free to (re)open tickets if any issues occur.

```
npm install reveal-md@rc --global
```

**Comment by quitequinn** [comment]
Was this resolved? I'm running into the same issue.

**Comment by quitequinn** [comment]
Seems the solution is to preface your path with "../".

Ex. `--theme theme/my-theme.css` should be `--theme ../theme/my-theme.css`
