### ISSUE TITLE
demo index page is white on white - not loading a theme

### ISSUE THREAD

**Issue by bdowling** [webpro/reveal-md#180]
The latest branch does not load a theme into the directory listing of demo.

To make this worse, the template has a hard coded `color: white` so the page appears completely blank out of the box until further inspection.

Would suggest the hard coded color be removed or both fore/background be set ;)

Without digging too far, it is not clear to me why themePath this is left undefined instead of using the default:

```diff
-  options.themePath = args.theme ? parseThemeArg(args.theme) : undefined;
+  options.themePath = args.theme ? parseThemeArg(args.theme) : options.defaults.themePath;
```

```
       <title>Directory Listing</title>
        <link rel="stylesheet" href="" id="theme">
        <style type="text/css">
            body {
                margin: 1em;
            }
            a {
                color: white;
                display: block;
            }
        </style>
```

**Comment by webpro** [comment]
Can you guys please try again with version 2.0.0-rc.4? Feel free to (re)open tickets if any issues occur.

```
npm install reveal-md@rc --global
```
