### ISSUE TITLE
SVG in static site

### ISSUE THREAD

**Issue by antifermion** [webpro/reveal-md#181]
SVG images are embedded as `![](data:image/svg;base64,PD9...`, it should be 
`![](data:image/svg+xml;base64,PD9` instead, I think.

**Comment by webpro** [comment]
This uses [image-data-uri](https://github.com/DiegoZoracKy/image-data-uri) which seems to simply use the extension only (`svg` in your example).

I could make an exception for `svg+xml` and replace it in the data string.

Are you experiencing render issues with this?
