### ISSUE TITLE
Code Fragment Highlighting

### ISSUE THREAD

**Issue by mavatoo** [webpro/reveal-md#187]
This is a feature request.  It would be awesome to include an integration with a plugin such as:

https://github.com/bnjmnt4n/reveal-code-focus

along with a md syntax to make it easy to step through code samples.  Gitpitch seems to do something similar that works well.

**Comment by webpro** [comment]
Sounds cool. I'm happy to look into a PR with this feature.

**Comment by fuhrmanator** [comment]
I have got used to doing markdown with reveal using [this VS Code plugin](https://marketplace.visualstudio.com/items?itemName=evilz.vscode-reveal). Unfortunately, it suffers from not being able to deploy with Travis CI (there's no npm command to generate a static web site). 

There's a rich demo in a [reveal markdown file](https://raw.githubusercontent.com/evilz/vscode-reveal/master/sample.md) that works in that VSCode plugin; it includes support for Code Fragment Highlighting and other features. 

It would be great if `reveal-md` could eventually support all those features, too -- an ambitious endeavor, but worth mentioning. Perhaps some of the implementation from that plugin could be integrated here?

**Comment by webpro** [comment]
Re-opening for visibility.

**Comment by pluskal** [comment]
Now, when Gitpitch ends, it would be awesome to have this functionality for those of us who are migrating.
