### ISSUE TITLE
Slide background not working with static site export

### ISSUE THREAD

**Issue by Allaman** [webpro/reveal-md#199]
reveal-md version: 2.05
OS: OpenSuse Tumbleweed

`reveal-md presentation.md --static public `does create an index.html with images as string encoded. Nevertheless slide background images are neither integrated in the html nor copied to the exported directory. Therefore, the slides are missing there background.

Snippet:

```markdown
## Tooling
<!-- .slide: data-background="./background.png" -->
<!-- .slide: style="color:red" -->
```
background is not visible in the exported presentation. Colored font is working as expected

Workaround: Copy all slide background images to the root of the directory

**Comment by webpro** [comment]
You can copy extra directories with `--static-dirs`, I've just added this to the docs.
