### ISSUE TITLE
Can't use local images

### ISSUE THREAD

**Issue by avish** [webpro/reveal-md#2]
I'm trying to include an image in a presentation, and can't get reveal-md to serve it. I'm placing the image next to the MD file and using `<img src="image.png"/>` but get a 404 (reveal-md is started from the same directory as the MD file).

Does the local reveal-md server serve static files at all?

**Comment by jarandaf** [comment]
>Root folder is resolved from Markdown file (or directory) reveal-md was started with.

Might be interesting to include a "statics" folder feature. I can think of multiple presentations sharing same resources (images, css, etc.), and with the current approach, every one should include them separately in the same related `.md` file folder.

**Comment by webpro** [comment]
@jarandaf I'm open for a PR to include this feature.
