### ISSUE TITLE
Add shorthand for fragments

### ISSUE THREAD

**Issue by dorianbrown** [webpro/reveal-md#201]
Hi guys,

Big fan of the library, makes writing reveal.js presentation super nice. 

One thing I think is missing (or maybe I didn't see the option) is easily inserting fragments into slides. The only way I could find is using 

```
<!-- .element: class="fragment" -->
```

which seems a little clumsy. Any ideas on what would be a good sequence for this?

Maybe something like `<frag>`? This isn't really consistent with the rest though...

**Comment by webpro** [comment]
Well, as you found out, your example is the way to do this with reveal.js (https://github.com/hakimel/reveal.js/#element-attributes). Really the only syntax reveal-md adds is to separate slides.
