### ISSUE TITLE
Question: how to change where custom css assets are placed?

### ISSUE THREAD

**Issue by ericmjl** [webpro/reveal-md#207]
I have noticed that when running reveal-md, custom CSS assets are placed in a folder called `_assets`. 

One thing that I cannot figure out is why github pages cannot find the CSS folder placed in there, though. Everything else loads properly. I have verified this by manually typing in the URLs for each asset that gets loaded. 

My question, then, is this: is it possible to change the folder that the custom assets are placed in?

**Comment by webpro** [comment]
That sounds weird. So the Javascript is loaded from `_assets`, but the CSS is not?

**Comment by webpro** [comment]
Oh wait, you are saying _custom_ assets, the ones you add yourself? See this command, you can use any dir you want:

```
reveal-md slides.md --static --static-dirs=assets
```

**Comment by ericmjl** [comment]
@webpro thanks for getting back! I eventually figured out that GitHub pages, which is built by Jekyll, ignores any directories and files that are prefixed with an underscore. 

That said, I'm wondering if we could create a different target directory for static assets? For example, instead of placing all the files in `_assets`, can we put it in a directory called `static`?

**Comment by webpro** [comment]
Ah, nice find. It wouldn't be too hard to make it configurable. I don't have a lot of time for this currently, but let's leave this issue open in case you or anyone else is up to this task!

**Comment by webpro** [comment]
Just released this in [v2.2.0](https://github.com/webpro/reveal-md/releases/tag/2.2.0). Now the assets dir can be adjusted using `--assets-dir=my-stuff`.

Thanks to @kazigk for picking this up!
