### ISSUE TITLE
Element attributes do not work

### ISSUE THREAD

**Issue by kemelzaidan** [webpro/reveal-md#21]
In reveal.js there is a way to set element class and attributes by passing a comment like in the reveal.js documentation:

    > - Item 1 
    > - Item 2 

It is very useful to set element's fragments, but unfortunately, that does't work with reveal-md.

**Comment by kemelzaidan** [comment]
If the change fixes this issue without breaking anything else, that would be very nice :+1:

**Comment by JanoschDeurer** [comment]
In the moment I have not enouth time to test it. The parts that I used so far worked. I will work on it in about 2 month and then file a pull request.

**Comment by webpro** [comment]
Let's first wait if/until I've merged #26 (no idea what's in Reveal.js v3.x).

**Comment by webpro** [comment]
Looks like this works fine out of the box now. Can you guys please take a look and confirm?

**Comment by kemelzaidan** [comment]
Is the version in npm the same you fixed? I've tried version 0.0.15 and it didn't work for me. HTML generated show an empty html comment.

**Comment by jossemarGT** [comment]
Just as follow up, the comment syntax seems to work for me

```html
<!-- .element: class="fragment" data-fragment-index="1" -->
```

**Comment by webpro** [comment]
Thanks @jossemarGT.

I consider this issue to be fixed. Feel free to re-open if you still encounter issues.
