### ISSUE TITLE
--puppeteer-launch-args not given to puppeteer launch args.

### ISSUE THREAD

**Issue by JulienPalard** [webpro/reveal-md#210]
As the title say, the puppeteer-launch-args are just not given to puppeteer. Looks like they are not used at all.

**Comment by matthiasharrer** [comment]
This seems to be the same issue I encountered here: #209 

The ```--puppeteer-launch-args``` were respected for printing the featured slide https://github.com/webpro/reveal-md/blob/master/lib/featured-slide.js#L42 but not for printing the whole pdf of the slides.

**Comment by webpro** [comment]
This should be fixed in [v2.1.1](https://github.com/webpro/reveal-md/releases/tag/2.1.1). Thanks!

**Comment by JulienPalard** [comment]
Thanks @webpro!
