### ISSUE TITLE
Latex not being ignored by markdown parsing

### ISSUE THREAD

**Issue by dorianbrown** [webpro/reveal-md#211]
# Problem
While adding some latex to slides, I discovered a bug where two underscores (used a lot of subscripts) where translated into `<em>` tags. So this:
```latex
$$\Theta_t = G_t \Theta_{t-1} + w_t$$
```
was rendered like this in the presentation's HTML:
```html
$$\Theta_t = G
<em>t \Theta <\em>
{t-1} + w_t$$
```
which is far from ideal.
## Possible Solution
Although I am not familiar with the code, I believe there is a parser which translates the markdown to HTML. A solution would be to have this parser ignore all text contained within `$` or `$$` signs.

I'll try to solve it, but if someone is more familiar with the source code this might be a quick one to fix.

**Comment by webpro** [comment]
Not sure if this is a bug, as there is not actually any support for LaTeX. Did you add your own scripts for to render this?

Related: #109

**Comment by dorianbrown** [comment]
I didn't add anything for LaTeX, it's included in the default template, `lib/template/reveal.html`:

https://github.com/webpro/reveal-md/blob/81109970d3eaf26ddd7602009e0e9eb41c9fd962/lib/template/reveal.html#L55-L64

It's possible this is a bug in reveal.js, but I haven't tested that yet. I'll see if I can create some markdown slides in reveal.js to test this.

**Comment by webpro** [comment]
Right, I forgot that MathJax can parse LaTeX as input. Related issues:

* https://github.com/hakimel/reveal.js/issues/702
* https://github.com/hakimel/reveal.js/pull/1205
* https://github.com/hakimel/reveal.js/issues/1359

I'm going to close this issue, as I still think it's an issue with the reveal.js plugin(s).

**Comment by dorianbrown** [comment]
Yeah you are right, it's an issue with the marked plugin which is used to parse the markdown. There's already a PR to fix it.
