### ISSUE TITLE
Printing: Puppeteer unavailable, unable to generate PDF file.

### ISSUE THREAD

**Issue by robertdebock** [webpro/reveal-md#216]
When using [this container](https://github.com/robertdebock/docker-revealmd/blob/master/Dockerfile) to print a presentations, I see this errror:

```
reveal-md some-slideshow.md --print some-slideshow.pdf
Puppeteer unavailable, unable to generate PDF file
```

It seems this should work, but does not. Maybe something is not installed? (Missing from package.json?)

**Comment by webpro** [comment]
Hi @robertdebock. Not sure what's going on in the Dockerfile, but you may remember #191. Apparently Puppeteer fails to install in the container, which is outside the scope of reveal-md.
