### ISSUE TITLE
Blank PDF

### ISSUE THREAD

**Issue by jossemarGT** [webpro/reveal-md#22]
**First:** This module is the best!  Thanks :octocat: 

**Second:** Yeah I know that #19 was close, but I have the same issue with pdf printing

```reveal-md Slides.md --print Slides.md.pdf```

Creates a pdf with the same background color and amount of slides, but, the sentences are transparent. Maybe the problem is in `@print` styles?

If a have some time I'll be glad to trace that bug, but at this moment I'm just open for ideas. BTW I'm usign `node@0.10.31` and `phantomjs@1.9.9` on GNU Debian Linux.

**Comment by grigio** [comment]
An alternative is to print to PDF via `http://localhost:1948/slides.md?print-pdf` it works
