### ISSUE TITLE
Custom CSS specified in YAML header not copied when generating static website

### ISSUE THREAD

**Issue by pezcode** [webpro/reveal-md#221]
I specify a custom CSS in the YAML front matter header like this:
```YAML
css: slides.css
```
which works fine for live presentations (`reveal-md -w slides.md`). But when I export it to a static website:

```bash
reveal-md slides.md --static slides_static --static-dirs images,videos
```

it generates the correct stylesheet link in the html header
```html
<link rel="stylesheet" href="./_assets/slides.css">
```
but it doesn't copy the *_assets* folder.

What **does** work is specifying `--css slides.css` in the previous call to reveal-md - it correctly copies the stylesheet to *_assets*. It's a workaround but it means I can't have most of the config in the .md file.

**Comment by webpro** [comment]
The whole "generate static website" got a bit out of hand; but I'm happy to accept a PR with a fix!
