### ISSUE TITLE
Adding a header and / or footer

### ISSUE THREAD

**Issue by mvdkleijn** [webpro/reveal-md#222]
Sorry if this is a stupid question... is it possible to add a header and/or footer for all slides?
I've got two small logos that I have to add, preferably top left and bottom left and tried doing this with custom CSS but didn't have any luck. Best I can manage is a single logo using something like:

```
body:after {
  content: url('myimage.png');
}
```

**Comment by webpro** [comment]
Either you would work with the existing template, if it has enough "hooks" in the markup to apply the CSS to. Or, you can use a different template: https://github.com/webpro/reveal-md#custom-template. You can copy the one from this project and make the modifications you need. Let me know if you still got any issues!

**Comment by JulienPalard** [comment]
If of any help¹, a friend helped me do it here: https://framagit.org/JulienPalard/paris.py-19/blob/master/reveal.html

1: If, like me, you're really not a "front-end guy"...
