### ISSUE TITLE
Two columns

### ISSUE THREAD

**Issue by facontidavide** [webpro/reveal-md#223]
Ok, this is probably a stupid question related to the fact that I am not familiar with CSS and HTML.

Is there any way to support a 2 column layout in reveal-md?
If there is, it would be nice to have it either in the readme or the wiki

**Comment by facontidavide** [comment]
I am trying this https://stackoverflow.com/questions/30861845/how-to-use-two-column-layout-with-reveal-js

But the text inside div is not recognized as markdown

```
<div id="left">

## Title 1

- item 1
- item 2
</div>

<div id="right">

## Title 2

- item A
- item B
</div>

![image](https://user-images.githubusercontent.com/2822888/49146447-75677a00-f302-11e8-9c08-844bd30a4b56.png)

```

**Comment by webpro** [comment]
Oh yes, I forgot about HTML within the Markdown. Isn't an extra newline before the closing `</div>` necessary?

**Comment by facontidavide** [comment]
Even with the newline, it doesn't work

**Comment by webpro** [comment]
I think I've seen people using HTML within Markdown with reveal-md. You could search the issues in this project, maybe there are working examples.

**Comment by facontidavide** [comment]
I could not find any useful information on the internet... anyway, thanks for your awesome work.

**Comment by kiwidamien** [comment]
Can we reopen this issue? Came here looking for the same thing --  I can make two columns by creating divs (as in the example above) but then all Markdown in the divs no longer renders.

**Comment by webpro** [comment]
Reopening for visibility. Yet the ~issue~ challenge is more with reveal.js and the Markdown parser, so I'm afraid there isn't much that reveal-md itself can do.

**Comment by jakupmichaelsen** [comment]
I don't know why, but it seemingly works for me 🤔

I've added this to my CSS theme: 

```
#left {
	margin: 10px 0 15px 20px;
	text-align: left;
	float: left;
	z-index:-10;
	width:48%;
	font-size: 0.85em;
	line-height: 1.5; 
}

#right {
	margin: 10px 0 15px 0;
	float: right;
	text-align: left;
	z-index:-10;
	width:48%;
	font-size: 0.85em;
	line-height: 1.5; 
}
```

And in my Markdown presentation:

```
<div id="left">

## Left column
- Bullet 1
- Bullet 2
- Bullet 3 
- Even [links](https://www.google.com)

</div>

<div id="right">

## Right colum
1. List
2. List
3. ![Icon](https://cdn3.iconfinder.com/data/icons/ballicons-free/128/graph.png)

</div>
```

Which generates: 

![imgur](https://i.imgur.com/Awj8VzF.png)

**Comment by kekru** [comment]
Works for me, too. After upgrading from reveal-md 3.0.4 to 3.4.1
