### ISSUE TITLE
custom name for static html

### ISSUE THREAD

**Issue by ndaman** [webpro/reveal-md#225]
I am using reveal-md to prepare lecture notes for my class, and it would be nice if I could share one common folder structure but simply have a name other than index.html given to the static page. Is there a simple way to do this already that I'm missing? Or could it be added as an option to --static? Thanks!

**Comment by webpro** [comment]
This isn't featured in reveal-md currently. You could provide a custom folder name (e.g. `--static my-lecture`), but it still contains `index.html`.

Happy to look into a PR for this, though!

**Comment by webpro** [comment]
I've just released a pre-release for v3, which might be what you're after. When doing a `--static` export of a whole directory (e.g. `reveal-md dir/`), it generates `slides-a.html` from `slides-a.md` etc.

You can install this:

```
npm install reveal-md@next
```

Happy to know whether this works for you.
