### ISSUE TITLE
firefox --print not work

### ISSUE THREAD

**Issue by xigrug** [webpro/reveal-md#226]
npm list -g --depth=0
> /public/home/hysplit/software/node-v8.11.3/lib
> ├── npm@6.4.1
> └── reveal-md@2.3.1
firefox --version
> Mozilla Firefox 52.2.0
google-chrome --version
> Google Chrome 70.0.3538.110
the file can be find in [intro-to-category-theory](https://github.com/ruippeixotog/intro-to-category-theory)

reveal-md slides.md
>Reveal-server started at http://localhost:1948

reveal-md slides.md --static ./test
> Wrote static site to /public/home/hysplit/work/study/tool/intro-to-category-theory/test

This is no problem, but:
reveal-md slides.md --print test.pdf
> Attempting to print "slides.md?print-pdf" to filename "test.pdf" as PDF.
> Error while generating PDF for "slides.md"
and nothing to happen.

I try to change the chrome to the default browser, but it failed. `Google Chrome cannot determine or set the default browser` 
My system is  
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
```
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core
```

**Comment by webpro** [comment]
Hi @xigrug! `reveal-md` uses Puppeteer to generate the PDF. It is an optional dependency to the reveal-md package (but required to generate PDF).

Was Puppeteer installed with reveal-md? You can try again with `npm install -g reveal-md`, and check the logs.

**Comment by xigrug** [comment]
Hi @webpro, I don't get some information for Puppeteer:

npm install -g reveal-md

> /public/home/hysplit/software/node-v8.11.3/bin/reveal-md -> /public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/bin/cli.js
> npm WARN rollback Rolling back abbrev@1.1.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/abbrev/.nfs000000001910069e000002a8'
> npm WARN rollback Rolling back code-point-at@1.1.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/code-point-at/.nfs00000000191007c1000002ad'
> npm WARN rollback Rolling back brace-expansion@1.1.11 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/brace-expansion/.nfs00000000191007c4000002ae'
> npm WARN rollback Rolling back chownr@1.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/chownr/.nfs00000000191007c3000002ac'
> npm WARN rollback Rolling back aproba@1.2.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/aproba/.nfs00000000191007c0000002a9'
> npm WARN rollback Rolling back balanced-match@1.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/balanced-match/.nfs00000000191007be000002ab'
> npm WARN rollback Rolling back fs.realpath@1.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/fs.realpath/.nfs00000000191007c9000002b5'
> npm WARN rollback Rolling back ansi-regex@2.1.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/ansi-regex/.nfs00000000191007bf000002aa'
> npm WARN rollback Rolling back has-unicode@2.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/has-unicode/.nfs00000000191007ca000002b6'
> npm WARN rollback Rolling back console-control-strings@1.1.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/console-control-strings/.nfs00000000191007c5000002af'
> npm WARN rollback Rolling back inherits@2.0.3 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/inherits/.nfs00000000191007cb000002b7'
> npm WARN rollback Rolling back ini@1.3.5 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/ini/.nfs00000000191007cc000002b8'
> npm WARN rollback Rolling back ignore-walk@3.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/ignore-walk/.nfs00000000191007cf000002bc'
> npm WARN rollback Rolling back is-fullwidth-code-point@1.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/is-fullwidth-code-point/.nfs00000000191007d2000002c3'
> npm WARN rollback Rolling back npm-bundled@1.0.3 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/npm-bundled/.nfs000000001911015d000002c0'
> npm WARN rollback Rolling back isarray@1.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/isarray/.nfs00000000191007cd000002b9'
> npm WARN rollback Rolling back minimatch@3.0.4 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/minimatch/.nfs00000000191007ce000002ba'
> npm WARN rollback Rolling back npm-packlist@1.1.10 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/npm-packlist/.nfs000000001911015f000002c2'
> npm WARN rollback Rolling back ms@2.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/ms/.nfs000000001911015b000002be'
> npm WARN rollback Rolling back number-is-nan@1.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/number-is-nan/.nfs0000000019110160000002c1'
> npm WARN rollback Rolling back os-homedir@1.0.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/os-homedir/.nfs0000000019110162000002c4'
> npm WARN rollback Rolling back object-assign@4.1.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/object-assign/.nfs0000000019110161000002c5'
> npm WARN rollback Rolling back osenv@0.1.5 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/osenv/.nfs0000000019110163000002c7'
> npm WARN rollback Rolling back os-tmpdir@1.0.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/os-tmpdir/.nfs0000000019110164000002c6'
> npm WARN rollback Rolling back path-is-absolute@1.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/path-is-absolute/.nfs0000000019110165000002c8'
> npm WARN rollback Rolling back safer-buffer@2.1.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/safer-buffer/.nfs0000000019110167000002cc'
> npm WARN rollback Rolling back safe-buffer@5.1.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/safe-buffer/.nfs0000000019110168000002cd'
> npm WARN rollback Rolling back process-nextick-args@2.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/process-nextick-args/.nfs0000000019110166000002cb'
> npm WARN rollback Rolling back set-blocking@2.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/set-blocking/.nfs000000001911016a000002d2'
> npm WARN rollback Rolling back signal-exit@3.0.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/signal-exit/.nfs000000001911016c000002d3'
> npm WARN rollback Rolling back strip-ansi@3.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/strip-ansi/.nfs000000001911016d000002d4'
> npm WARN rollback Rolling back strip-json-comments@2.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/strip-json-comments/.nfs0000000019110171000002d6'
> npm WARN rollback Rolling back string-width@1.0.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/string-width/.nfs000000001911016f000002d5'
> npm WARN rollback Rolling back util-deprecate@1.0.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/util-deprecate/.nfs0000000019110174000002d9'
> npm WARN rollback Rolling back are-we-there-yet@1.1.4 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/are-we-there-yet/.nfs00000000191006dc000002dc'
> npm WARN rollback Rolling back wide-align@1.1.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/wide-align/.nfs0000000019110070000002db'
> npm WARN rollback Rolling back wrappy@1.0.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/wrappy/.nfs000000001911007b000002dd'
> npm WARN rollback Rolling back gauge@2.7.4 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/gauge/.nfs00000000191006d5000002df'
> npm WARN rollback Rolling back npmlog@4.1.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/npmlog/.nfs000000001911006b000002de'
> npm WARN rollback Rolling back once@1.4.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/once/.nfs0000000019110065000002e0'
> npm WARN rollback Rolling back glob@7.1.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/glob/.nfs00000000191006c3000002e3'
> npm WARN rollback Rolling back inflight@1.0.6 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/inflight/.nfs00000000191006c8000002e1'
> npm WARN rollback Rolling back rimraf@2.6.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/rimraf/.nfs000000001911008a000002e2'
> npm WARN rollback Rolling back yallist@3.0.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/yallist/.nfs0000000019110004000002e4'
> npm WARN rollback Rolling back minipass@2.2.4 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/minipass/.nfs00000000191006cd000002e5'
> npm WARN rollback Rolling back fs-minipass@1.2.5 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/fs-minipass/.nfs00000000191006ad000002e6'
> npm WARN rollback Rolling back minizlib@1.1.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/minizlib/.nfs00000000191006be000002e7'
> npm WARN rollback Rolling back concat-map@0.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/concat-map/.nfs00000000191007c2000002b0'
> npm WARN rollback Rolling back deep-extend@0.5.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/deep-extend/.nfs00000000191007c7000002b1'
> npm WARN rollback Rolling back detect-libc@1.0.3 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/detect-libc/.nfs00000000191007d4000002b2'
> npm WARN rollback Rolling back core-util-is@1.0.2 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/core-util-is/.nfs00000000191007c6000002b3'
> npm WARN rollback Rolling back delegates@1.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/delegates/.nfs00000000191007c8000002b4'
> npm WARN rollback Rolling back minimist@1.2.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/rc/node_modules/minimist/.nfs0000000019110175000002c9'
> npm WARN rollback Rolling back nopt@4.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/nopt/.nfs000000001911016e000002ca'
> npm WARN rollback Rolling back debug@2.6.9 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/debug/.nfs00000000191007d1000002bf'
> npm WARN rollback Rolling back mkdirp@0.5.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/mkdirp/.nfs00000000191007d5000002bd'
> npm WARN rollback Rolling back nan@2.11.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/nan/.nfs00000000191006a8000002ea'
> npm WARN rollback Rolling back minimist@0.0.8 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/minimist/.nfs00000000191007d0000002bb'
> npm WARN rollback Rolling back semver@5.5.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/semver/.nfs0000000019110172000002d0'
> npm WARN rollback Rolling back string_decoder@1.1.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/string_decoder/.nfs000000001911016b000002d7'
> npm WARN rollback Rolling back tar@4.4.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/tar/.nfs000000001911001c000002e8'
> npm WARN rollback Rolling back sax@1.2.4 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/sax/.nfs0000000019110169000002cf'
> npm WARN rollback Rolling back iconv-lite@0.4.21 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/iconv-lite/.nfs00000000191007d3000002ce'
> npm WARN rollback Rolling back needle@2.2.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/needle/.nfs0000000019110170000002d1'
> npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/readable-stream/.nfs000000001911008f000002da'
> npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/node-pre-gyp/.nfs0000000019110080000002e9'
> npm WARN rollback Rolling back rc@1.2.7 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/rc/.nfs0000000019110173000002d8'
> npm WARN rollback Rolling back fsevents@1.2.4 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/ansi-regex/.nfs00000000191007bf000002aa'
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/reveal-md/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> + reveal-md@2.3.1
> updated 1 package in 159.283s

**Comment by xigrug** [comment]
I find some information about puppeteer:
 ├──  error: ENOENT: no such file or directory, open '/public/home/hysplit/software/node-v8.11.3/lib/node_modules/reveal-md/node_modules/nan/package.json
  ├─┬ opn@5.4.0
  │ └── is-wsl@1.1.0
  ├─┬ `puppeteer@1.3.0`
  │ ├── debug@2.6.9 deduped
  │ ├─┬ extract-zip@1.6.7
  │ │ ├─┬ concat-stream@1.6.2
  │ │ │ ├── buffer-from@1.1.1
  │ │ │ ├── inherits@2.0.3 deduped
  │ │ │ ├── readable-stream@2.3.6 deduped
  │ │ │ └── typedarray@0.0.6
  │ │ ├── debug@2.6.9 deduped
  │ │ ├─┬ mkdirp@0.5.1
  │ │ │ └── minimist@0.0.8
  │ │ └─┬ yauzl@2.4.1
  │ │   └─┬ fd-slicer@1.0.1
  │ │     └── pend@1.2.0
  │ ├─┬ https-proxy-agent@2.2.1
  │ │ ├─┬ agent-base@4.2.1
  │ │ │ └─┬ es6-promisify@5.0.0
  │ │ │   └── es6-promise@4.2.5
  │ │ └─┬ debug@3.2.6
  │ │   └── ms@2.1.1
  │ ├── mime@1.4.1
  │ ├── progress@2.0.2
  │ ├── proxy-from-env@1.0.0
  │ ├─┬ rimraf@2.6.2
  │ │ └── glob@7.1.3 deduped
  │ └─┬ ws@3.3.3
  │   ├── async-limiter@1.0.0
  │   ├── safe-buffer@5.1.2 deduped
  │   └── ultron@1.1.1

**Comment by webpro** [comment]
Perhaps Puppeteer is not supported on CentOS? Why is "firefox" in the title of this issue?

**Comment by xigrug** [comment]
OK, I think maybe it is caused by firefox. 
Another issue，[intro-to-category-theory](https://github.com/ruippeixotog/intro-to-category-theory) is ok 
 for fully picture.

**Comment by webpro** [comment]
I'm going to close this issue, but feel free to re-open to discuss anything related.
