### ISSUE TITLE
picture does not show fully

### ISSUE THREAD

**Issue by xigrug** [webpro/reveal-md#227]
`reveal-md slides.md --highlight-theme github`
this is ok.
`reveal-md slides.md --highlight-theme github --static test`
 Just half of the picture is displayed for the  index.html.

`npm list -g --depth=0`
> /public/home/hysplit/software/node-v8.11.3/lib
> ├── npm@6.4.1
> └── reveal-md@2.3.1
> firefox --version
> Mozilla Firefox 52.2.0
> google-chrome --version
> Google Chrome 70.0.3538.110

the test file can be find in [intro-to-category-theory](https://github.com/ruippeixotog/intro-to-category-theory)

**Comment by webpro** [comment]
That sounds like an issue with HTML/CSS and/or [reveal.js](https://github.com/hakimel/reveal.js) itself. Feel free to discuss, but I'm going to close this issue for now.
