### ISSUE TITLE
[feature] Split single presentation in multiple .md files?

### ISSUE THREAD

**Issue by ebousse** [webpro/reveal-md#228]
While having to write all slides of a single presentation in a single `.md` file is OK for small-ish talks, navigating in the single markdown file can become difficult when it gets very large.

Idea: could reveal-md provide a simple way to take as input a list of `.md` files instead of a single one, and could simply append them (in memory) before processing them as one large file as usual? 

The list of slides could also be provided as a file (eg. similarly to https://github.com/slara/generator-reveal where a json file must contain the list of used `.md` files), and this file passed to reveal-md instead of a markdown file.

**Comment by webpro** [comment]
One option that is already available is to link to another file, e.g. you can have `[deck b](./b.md]` in `a.md`.

Another one is to concatenate files and open the result:

```
cat a.md b.md > c.md && reveal-md c.md
```

Does that help?

**Comment by BPScott** [comment]
[Reveal supports referencing an external markdown files](https://github.com/hakimel/reveal.js#external-markdown) by customising the data-markdown property It might be worth playing with that?

**Comment by bukowskiadam** [comment]
I needed that too and used custom markdown preprocessor to fix that

preprocess.js
```js
const { readFileSync } = require('fs');
const path = require('path');

const LINE_SEPARATOR = '\n';
const FILE_REF_REGEX = /^FILE: (.+)$/;

const isFileReference = (line) => FILE_REF_REGEX.test(line);
const loadFileContent = (line, basePath) => {
    const filePath = line.match(FILE_REF_REGEX)[1];

    return readFileSync(path.join(basePath, filePath));
};

const preprocess = async (markdown, options) =>
    markdown
        .split(LINE_SEPARATOR)
        .map(line => isFileReference(line) ? loadFileContent(line, options.initialDir) : line)
        .join(LINE_SEPARATOR);

module.exports = preprocess;
```
then set [custom preprocessor](https://github.com/webpro/reveal-md#pre-process-markdown) option

then write `index.md`
```markdown
# My presentation

---

FILE: chapter-1.md

---

FILE: chapter-2.md
```

and write the rest of slides in chapter files.

**Comment by draptik** [comment]
@bukowskiadam Your solution looks interesting. Could you provide a minimal example?
Running your demo code simply outputs the string `FILE: chapter-1.md` instead of replacing it with the content of the file.
I have tried replacing the line separator with `\r\n` (instead of `\n`, because I'm currently on Windows), but still the preprocessor does not replace any content.

**Comment by bukowskiadam** [comment]
Here you are https://github.com/bukowskiadam/reveal-md-multifile
There is no recursive file includes. It could be added but I haven't need it yet.

**Comment by draptik** [comment]
@bukowskiadam  Thank you very much, your sample works like a charm!
