### ISSUE TITLE
revealOptions in md frontmatter should merge with options in reveal.json

### ISSUE THREAD

**Issue by BPScott** [webpro/reveal-md#230]
Currently if you specify any `revealOptions` in yaml front matter then nothing from reveal.json shall be honoured. I think these objects should be merged. As it currently stands it is not possible to specify some defaults in reveal.json, then override some of them by using `revealOptions` on a per-markdown file basis.

Consider the following:

Given a `reveal.json` with a setting in it:

```json
{
  "transition": "none"
}
```

and an `index.md` with a `revealOptions` key:

```md
---
revealOptions:
  width: 1024
  height: 768
---

# Slide Heading!
```

The options that get passed to reveal.js only contain a width and a height, they do not contain the transition.

The following is a test case that can be added to `render.spec.js` to demonstrate the behaviour that I would expect - The options are merged and in the even of duplicate keys the value from "renderOptions in the markdown front matter should win.

```js
  it('should merge revealOptions from frontmatter and options', () => {
    return render.render('---\nrevealOptions:\n  width: 300\n  height: 500\n---\nSlide', { revealOptions: { height: 100, transition: 'none' } }).then(actual => {
      expect(actual).toContain('var options = {"width": 300, "height": 500, "transition": "none"};');
    });
  });
```

**Comment by webpro** [comment]
Should work in the next release:

```
npm install reveal-md@next
```

Would appreciate it if you could give this a shot on your slides.

**Comment by webpro** [comment]
Should work in v3
