### ISSUE TITLE
[RFE] 'standalone file' with remote resources

### ISSUE THREAD

**Issue by iranzo** [webpro/reveal-md#231]
Currently the standalone version, outputs not just the presentation but resource files.

My understanding is that this is done to allow 'offline' presentations and to present where there's no reveal access.

I've enhanced a Pelican plugin https://github.com/iranzo/pelican-revealmd/ that uses 'pandoc' to improve some of the issues I found, but as it uses pandoc, features like proper slides in vertical/horizontal and other features might be lost.

If believe that if instead of pandoc I could invoke reveal-md to generate a static html (even without the headers), the resulting rendered 'presentations' on blogs would look a lot better.

As an example, what pandoc outputs is something like this (no headers, no css, etc):

~~~html
<section id="project-hosting-and-automation" class="slide level2">
<h2>Project hosting and automation</h2>
<p>/me: Pablo Iranzo Gómez ( <a href="https://iranzo.github.io" class="uri">https://iranzo.github.io</a> )</p>
</section>
<section id="you-got-a-shinny-new-project-what-now" class="slide level2">
...
...
...
</section>
~~~

Out of the file available at https://github.com/iranzo/iranzo.github.io/blob/source/content/presentations/automation-travis-ghpages-containers/2019-01-16-automate-project-github-pages-travis-and-quay.revealjs

Then, with a Pelican template like: https://github.com/iranzo/pelican-revealmd/blob/master/templates/revealmd.html all the css are loaded and presentation displayed

**Comment by webpro** [comment]
Not sure what exactly you are asking for?

Anyway, today I've refactored reveal-md to no longer inline images. So they're always external to the markdown/markup. Could you give it a shot?

```
npm install reveal-md@next
```

**Comment by iranzo** [comment]
Hi,
What I meant, is to just 'save' the 'html' file without headers, css, etc.

I'll be trying the updated version to see how it behaves and if something can be done here.

Thanks a lot!
Pablo
