### ISSUE TITLE
how to embed a video?

### ISSUE THREAD

**Issue by kaischleicher** [webpro/reveal-md#234]
Hi, I have a local .mp4 video file and do not manage to add it to my slideshow. Is this a supported feature?
I tried:
```
<video data-autoplay src="/movies/DB-EGFP-CDMPR.mp4"></video>
```
and 
```
<video width="480" height="320" controls="controls">
<source src="/movies/DB-EGFP-CDMPR.mp4" type="video/mp4">
</video>
```
but both do not work for me (tested in firefox, chrome, and opera). Thanks for your help!

**Comment by webpro** [comment]
This copy-pasted example works fine for me:

```
<video controls width="250">
    <source src="https://interactive-examples.mdn.mozilla.net/media/examples/flower.webm" type="video/webm">
    <source src="https://interactive-examples.mdn.mozilla.net/media/examples/flower.mp4" type="video/mp4">
    Sorry, your browser doesn't support embedded videos.
</video>

```

**Comment by webpro** [comment]
Ah, I think the `src` attribute should not be absolute (`/...`) but relative (`./...`).

And you can embed any HTML in Markdown, reveal-md shouldn't touch it.

**Comment by kaischleicher** [comment]
super, thanks for the code snippet! I used it to test and found that it was in fact my mp4 video file that could not be played. I could test it successfully with a webm file. Not sure if my mp4 is the problem or maybe a missing codec in the browser though. Thanks!
