### ISSUE TITLE
Fragments and code

### ISSUE THREAD

**Issue by mikesolem** [webpro/reveal-md#235]
Is it possible to do data-noescape with reveal-md?
  https://github.com/hakimel/reveal.js#code-syntax-highlighting

Is it possible to use "fragment" with code blocks?  Either fragments within a code block, or having multiple code blocks each as a fragment?

I want to be able to show source code, revealing a few more lines at a time.

Thanks

**Comment by webpro** [comment]
In general, reveal-md supports what reveal.js supports. Here is the list of plugins: https://github.com/webpro/reveal-md/blob/bcf9b0f27d27d5b1df6f8ff95c7ceedaa81fe347/lib/template/reveal.html#L57-L63

reveal-md basically just separates the slides for you.

What did you try? What does not work as expected?

**Comment by mikesolem** [comment]
Ok, I understand.  I went back to the reveal.js docs, and was able to get it working.  This seems to do what I want:

``` 

<pre class="fragment">
  <code>
package main
  </code>
</pre>

<pre class="fragment">
  <code data-trim data-noescape>
import (
	"encoding/json"
	"fmt"
	<mark>"io"</mark>
	"log"
	"strings"
)
  </code>
</pre>

```

Thanks for your help!

**Comment by webpro** [comment]
Great you got it working for you. Thanks for letting me know!
