### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by jwgrenning** [webpro/reveal-md#236]
Hi

I get errors when I install reveal-md.  I can run a basic presentation with a couple slides and bullet points.   I can't generate a PDF.  It says `Puppeteer unavailable, unable to generate PDF file.`

Here are the install errors.

`
$ sudo npm install -g reveal-md
Password:
/usr/local/bin/reveal-md -> /usr/local/lib/node_modules/reveal-md/bin/cli.js

> fsevents@1.2.7 install /usr/local/lib/node_modules/reveal-md/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/lib'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/james/.node-gyp/10.15.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /usr/local/lib/node_modules/reveal-md/node_modules/fsevents
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/reveal-md/node_modules/fsevents
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/reveal-md/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)

> puppeteer@1.3.0 install /usr/local/lib/node_modules/reveal-md/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r549031! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/.local-chromium' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/reveal-md/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@1.3.0 (node_modules/reveal-md/node_modules/puppeteer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@1.3.0 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ reveal-md@2.4.1
added 384 packages from 493 contributors in 18.163s
`

**Comment by webpro** [comment]
Looks like you're on a OS that is not supported by Puppeteer. It's an optional dependency of reveal-md. If it's not available, PDFs can't be generated. Sorry, not much I can do about it.

(Also, in general, it's not a best practice to install packages with `sudo`. But that doesn't seem related to this issue.)

**Comment by jwgrenning** [comment]
Thanks for the prompt reply.

I am on a Mac. I think I'll give it a try from a Docker container.

Thank for the sudo warning.

James

**Comment by webpro** [comment]
I'm on macOS as well, Puppeteer should definitely install/work. Looks like sudo is the culprit:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/james/.node-gyp/10.15.1"
...
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/.local-chromium']
errno: -13,
code: 'EACCES',
syscall: 'mkdir',
path:
'/usr/local/lib/node_modules/reveal-md/node_modules/puppeteer/.local-chromium' }
```

Guess your main challenge is to make sure `npm install -g` works without `sudo`.

**Comment by jwgrenning** [comment]
I first tried without sudo and got a permissions error.  Then I got the 
same with sudo. (If I recall correctly, but I would not have added sudo 
without a permissions error)

..... Time goes bye ...

THANKS, you clue on the install has me up and running.

**Comment by onlythinking** [comment]
I tried the following command successfully.
`sudo npm install -g reveal-md --unsafe-perm=true`
