### ISSUE TITLE
Error --print in docker container

### ISSUE THREAD

**Issue by pikalo** [webpro/reveal-md#239]
When i want to use **--print** in docker container
```
Error: Failed to launch chrome!
/home/ubuntu/nvm/versions/node/v10.15.1/lib/node_modules/reveal-md/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome: 
error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/ubuntu/nvm/versions/node/v10.15.1/lib/node_modules/reveal-md/node_modules/puppeteer/lib/Launcher.js:255:14)
    at Interface.helper.addEventListener (/home/ubuntu/nvm/versions/node/v10.15.1/lib/node_modules/reveal-md/node_modules/puppeteer/lib/Launcher.js:244:50)
    at Interface.emit (events.js:194:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Because of the puppeteer and chromium error

When I searched the internet, I reached this link too
[https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)

* Setting Up Chrome Linux Sandbox
   * If you absolutely trust the content you open in Chrome, you can launch Chrome with the --no-sandbox argument:
```
const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
```

**But my question is how to use it ?**

**Comment by pikalo** [comment]
I would suggest that you create a **docker image** for use with `reveal-md`, if possible

**Comment by webpro** [comment]
I think this is where `--puppeteer-launch-args` comes in (see `reveal-md --help`)

**Comment by pikalo** [comment]
### For docker container (ubuntu):
In order to generate PDF, `reveal-md` needs to install `puppeteer & Chromium` which is not installed in container by default. Thus, we need to install reveal-md with command **-f** 
```
npm install -g -f reveal-md
```
I installed it but again Chromium didn't work properly because it needed more packages for container.

```
apt-get update -yq && \
    apt-get -yq upgrade
	
sudo apt-get install -yq 
gconf-service \
libasound2 \
libatk1.0-0 \
libc6 \
libcairo2 \
libcups2 \
libdbus-1-3 \
libexpat1 \
libfontconfig1 \
libgcc1 \
libgconf-2-4 \
libgdk-pixbuf2.0-0 \
libglib2.0-0 \
libgtk-3-0 \
libnspr4 \
libpango-1.0-0 \
libpangocairo-1.0-0 \
libstdc++6 \
libx11-6 \
libx11-xcb1 \
libxcb1 \
libxcomposite1 \
libxcursor1 \
libxdamage1 \
libxext6 \
libxfixes3 \
libxi6 \
libxrandr2 \
libxrender1 \
libxss1 \
libxtst6 \
ca-certificates \
fonts-liberation \
libappindicator1 \
libnss3 \
lsb-release \
xdg-utils \
wget
```
I added the needed packages to container. Then, I added `--puppeteer-launch-args="dumpio:true --no-sandbox --disable-setuid-sandbox"` to argument for print-pdf.

```
reveal-md --puppeteer-launch-args="dumpio:true --no-sandbox --disable-setuid-sandbox" --print sample.md
```
 Voila! it works like a magic

**Comment by webpro** [comment]
Thanks, @pikalo! This is useful for other people as well.
