### ISSUE TITLE
Generate static site

### ISSUE THREAD

**Issue by hugozap** [webpro/reveal-md#24]
Hi, This module is really cool. I want to share the rendered html, is there an easy way to do it?
Thanks

**Comment by maxlath** [comment]
@hugozap that's also what I'm looking for, did you a way to do that?

**Comment by webpro** [comment]
Maybe a service like https://ngrok.com or https://localtunnel.me is what you guys are after? Just Google for "share local website".

**Comment by maxlath** [comment]
@webpro no, it's more about doing something like
` reveal-md slides.md --build-static dist/ `
which would package the html/css/javascript to be hosted has a static page (like [a github page](http://vladimiralexiev.github.io/pres/20140611-SmartCulture-sem-tech-CH/index.html))

**Comment by webpro** [comment]
Ah. That shouldn't be too hard. It's just writing to HTML files instead of `res.send`-ing it with Express.

**Comment by maxlath** [comment]
indeed! just tried to
```
    res.send(build)
    fs.writeFile('./index.html', build)
```
and got my html file!
All that was missing then were the links to the associated reveal css and js files (and also my images), and done :)

**Comment by webpro** [comment]
So maybe you can send a PR to put this behind e.g. `--dist [dir]`?

**Comment by maxlath** [comment]
I tried to have a look at that, but I'm a bit confused on how to use commander to get the options, gather reveal files and handle `href` and `src` possible need to be rewritten

**Comment by justmytwospence** [comment]
theoretically this could even be integrated with GitHub pages, and a --publish option added

**Comment by devinshields** [comment]
``--publish`` is what I'm looking for, similar to ``make html`` found in [python's sphinx tool](http://sphinx-doc.org/tutorial.html)

markdown -> render -> gh-pages is really powerful, mostly because it's so easy.

**Comment by agonzalezro** [comment]
Was this closed because it was fixed or for cleaning the open issues?

I just started using your project (thanks!) and I would like to generate a `.html` file that I can use in my `gh-pages`. It doesn't look like there is an easy way of doing that at the moment.

Could you perhaps add some workaround explanation to the `README.md`?

**Comment by webpro** [comment]
It was a cleanup round indeed, apologies for not making that clear. I'm
happy to re-open if somebody offers an actual solution or work-around.

On Sunday, June 21, 2015, Alexandre González <notifications@github.com>
wrote:

> Was this closed because it was fixed or for cleaning the open issues?
>
> I just started using your project (thanks!) and I would like to generate a
> .html file that I can use in my gh-pages. It doesn't look like there is
> an easy way of doing that at the moment.
>
> Could you perhaps add some workaround explanation to the README.md?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpro/reveal-md/issues/24#issuecomment-113837306>.
>


-- 
Sent from Gmail Mobile

**Comment by mandeeps708** [comment]
Is there any way out to have my presentation saved on disk?
In which file I should edit 
```
  res.send(build)
    fs.writeFile('./index.html', build)
```
according to @maxlath

**Comment by webpro** [comment]
Or simply a "save page" in the browser.

**Comment by mandeeps708** [comment]
But nothing was rendered on the browser when I opened the saved HTML document.

**Comment by mandeeps708** [comment]
Is there another way out?
Can you give me solution that was used by @maxiath?
I mean which file to modify to be able to render html.
