### ISSUE TITLE
Live reload / watch not working since 2.4.1

### ISSUE THREAD

**Issue by mcanlas** [webpro/reveal-md#241]
I upgraded to the 3.0 series from 2.4.1 and the live reload option stopped working.

**Comment by webpro** [comment]
Seems to work fine here. Could you share the steps to reproduce?

**Comment by HoverBaum** [comment]
Just ran into the same issue. Looks like the option isn't handed to the handlebars context correctly. Will so some more investigation and hopefully open a Pull Request to fix this.
