### ISSUE TITLE
reveal-md path/to/my/slides.md doesn't work

### ISSUE THREAD

**Issue by pikalo** [webpro/reveal-md#242]
In new version, images are not displayed correctly when I want to run a md file like your example or in print to pdf

```
reveal-md path/to/my/slides.md
```

The reason is the wrong path on the server
 
```
http://localhost:1948/slides.md#/
```
It should be :

```
http://localhost:1948/path/to/my/slides.md#/
```
Everything worked correctly in version 2.4.1

**Comment by webpro** [comment]
This means images should be in the same or a subdir of the Markdown file.

The alternative is to start e.g. `reveal-md .` and navigate to your Markdown file there.

**Comment by pikalo** [comment]
the alternative way (`reveal-md .`) functions well for the server (web view), but what is the alternative for  exporting PDF? it is better to give path like the older version. If someone wants to use md file without path, it is better to run reveal-md from md file path. the second method is that it is better to have option in reveal.json for choosing path as same as old or new version. the older version is more functional because images are not in the same or a subdir of the md file.

**Comment by webpro** [comment]
The codebase is much cleaner now, without support for every imaginable use case. You can stay on v2 to keep things the way you want. Sorry for the inconvenience!
