### ISSUE TITLE
Demo font-awesome

### ISSUE THREAD

**Issue by draptik** [webpro/reveal-md#248]
Could somebody demonstrate how to include font-awesome fonts?

I have read https://github.com/webpro/reveal-md/issues/129 but I still do not know the proper way to use the fonts.

I would like to use it like:

```
<i class="fa fa-twitter" aria-hidden="true"></i>@someTwitter
```

Pointers or demo-projects?

**Comment by rmarku** [comment]
Hi draptic, 
I fixed it by adding the following CSS styles in a file.
```
.reveal i.fab {
    font-family: "Font Awesome 5 Brands";
    font-style: normal;
} 

.reveal i.far {
    font-family: "Font Awesome 5 Free";
    font-style: normal;
} 
```

This is for last font awesome where the twitter icon is:

```
<i class="fab fa-twitter"></i>
```

Here I have something
https://github.com/rmarku/slides
