### ISSUE TITLE
videos in a parent folder

### ISSUE THREAD

**Issue by xarthurx** [webpro/reveal-md#249]
hi, is it possible to embed a video file in another folder under the parent folder?

say I have:

```
xx\slides\slides.md
xx\video\video.mp4
```

I only manage to make it work if the video file is under `xx\slides` or `xx\slides\whatever`, but not the above setup.

Guess this is because the **node.js** server is setup under `slides` so that there is no access to the video file?
Or some other reasons?

Thanks.

**Comment by webpro** [comment]
That's correct. Files are served from the directory where the slides are in.
