### ISSUE TITLE
[feature] stop server after close the chrome window

### ISSUE THREAD

**Issue by ShuguangSun** [webpro/reveal-md#251]
Is it possible to stop the server or exist preview after closing the chrome window or idle?

Like the -time-out in [markdown-preview](https://github.com/yuanchuan/markdown-preview)

**Comment by webpro** [comment]
Not sure what you mean. You can `Ctrl-c` or close the terminal to stop the reveal-md server.

**Comment by ShuguangSun** [comment]
Thanks for your response.

We can mannulay using `Ctrl-c` or close the terminal to stop the server. If we can stop the server by determin whether user close the opened brower or brower tap (for example, no interaction in a period), it would be better.

**Comment by webpro** [comment]
Personally, I'm not interested in developing this feature. Feel free to open a PR for this, and I'm happy to look into it.
