### ISSUE TITLE
Unable to override themes after update

### ISSUE THREAD

**Issue by izumitelj** [webpro/reveal-md#252]
After updating reveal-md (>3.0.4), npm (>6.9.0) and nodejs (>v10.16.0) on Windows 7 x64, I could no longer override theme. Suggested syntax `reveal-md slides.md --theme solarized` or `reveal-md slides.md --theme theme/my-custom.css` doesn't work, neither for built-in themes or custom ones. 

The only way to make it work is by removing line defining default theme from the header of the markdown (YAML front matter) (for example `theme: black`)

Is anyone else experiencing this issue, and is there anything else I can try to collect more info on this issue? Thanks

**Comment by webpro** [comment]
That seems like a bug indeed. Feel free to open a PR for this, otherwise I'll look into it soon.

**Comment by webpro** [comment]
Should be fixed in [3.0.5](https://github.com/webpro/reveal-md/releases/tag/3.0.5)
