### ISSUE TITLE
multiple language with reveal-md

### ISSUE THREAD

**Issue by xinity** [webpro/reveal-md#254]
hey there,

I'm planning to move away from using google slides to use reveal-md as especially a good friend as created for me a nifty theme :)
I want to be able to manage multiple language files for the same presentation.
The idea is to have for example in a single md file the English language and the Spanish language.
Depending on a parameter set to reveal-md it will load one or the other.

Do any reveal-md gurus know perhaps how to achieve that or anything close to it?

Thank you so much for this awesome piece of software !!! :)

**Comment by webpro** [comment]
Hi @xinity. I would recommend to put different languages in different files. It's probably easier to manage "externally" than from inside the presentation/reveal-md.
