### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by ivakyb** [webpro/reveal-md#256]
reveal-md https://raw.githubusercontent.com/webpro/reveal-md/master/demo/a.md

```
[Error: ENOENT: no such file or directory, stat '/Users/ivakyb/https:/raw.githubusercontent.com/webpro/reveal-md/master/demo/a.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/kyb/devel/yocto-presentation/https:/raw.githubusercontent.com/webpro/reveal-md/master/demo/a.md'
}
```

**Comment by ivakyb** [comment]
## Workaround
    wget https://raw.githubusercontent.com/webpro/reveal-md/master/demo/a.md
    reveal-md a.md

**Comment by HoverBaum** [comment]
A duplicate of #245 which also describes the same error, although doesn't mention the workaround.

Maybe you could open a PR to update the docs @ivakyb, at least until this is fixed 🙂

**Comment by webpro** [comment]
I've removed this part from the docs for now. Let's leave this ticket open until it is resolved.
