### ISSUE TITLE
reveal.md and reveal-md won't be loaded

### ISSUE THREAD

**Issue by jeud** [webpro/reveal-md#258]
Hi, there

I have setup the project as below, but it seems that the the reveal.md and reveal-md were not loaded at all

Please guide, thanks

`reveal-md` Version: 3.0.4
OS: Windows 10 Pro

*Path*

```
|-reveal-md.json
|-reveal.json
|-01.md
|-02.md
```

*reveal-md.json*

```json
{
    "css": "style.css",
    "highlightTheme": "atom-one-dark",
    "theme": "black"
}
```

*reveal.json*

```json
{
    "hideAddressBar": true,
    "history": true,
    "slideNumber": "c / t",
    "transition": "slide"
}
```

I start `reveal-md` using

```bash
reveal-md .
```

**Comment by HoverBaum** [comment]
Hi @jeud, tried to reproduce your issues but didn't get any errors or unexpected behaviour.

What error are you seeing?

The expected behaviour should be that a black tab opens in your browser where you can select between `01.md` and `02.md`.
