### ISSUE TITLE
Different font and different port (Mac OS X)

### ISSUE THREAD

**Issue by ekzGuille** [webpro/reveal-md#259]
Hi, I've tried reveal md (v 3.0.4) on a Ubuntu 18.04, Windows 10 (1709) and a Mac OS X 10.14.5.
On Ubuntu and Windows my reveal-md server launches at the default port (1948) but on my Mac is launching on port (1337).

I've noticed aswell that on Windows and Ubuntu the font is the same, and it's very different from the OSX version (which messes up my slides due font size).

I don't know if you had that in mind but just wanted to let you know.

**Comment by webpro** [comment]
The default port is `1948`, so somehow in your Mac it's configured to be `1337` (e.g. from CLI `--port 1337` or in `reveal-md.json`).

Not sure how the font looks like on your Mac, but from my experience they're OK for me and other folks :)
