### ISSUE TITLE
Feature request custom favicon

### ISSUE THREAD

**Issue by iegik** [webpro/reveal-md#261]
https://github.com/webpro/reveal-md/blob/6d068644d2ee5bfdecb85f6e3f45f8b35bf44b19/lib/server.js#L22

- load `favicon.ico` from same directory of markdown file

```
reval-md foo/bar.md <- should check for foo/favicon.ico, overwise load lib/favicon.ico

**Comment by webpro** [comment]
Feel free to open a PR for this! Happy to look into it and merge it.
