### ISSUE TITLE
White margins in exported PDFs

### ISSUE THREAD

**Issue by hejmsdz** [webpro/reveal-md#263]
Hi,

I tried to export a reveal-md presentation to a PDF file and noticed that slides are surrounded by white margins. This may be intended for printing, but it's undesirable when the PDF is meant to be presented on screen.

I investigated a bit and found the reason: the page size in Puppeteer `pdf()` call in [print.js](https://github.com/webpro/reveal-md/blob/master/lib/print.js#L35) is hard-coded to A4 paper. When I change it to the same values as in my `reveal.json` or 960x700px, as it is by default, the margins disappear and slides fill the pages nicely.

I'll be happy to submit a pull request if we agree on how it should be solved. What do you think about using configured slide dimensions (from `reveal.json`, falling back to 960x700) and adding a command-line option `--format`/`--size` to optionally override it?

Cheers!

**Comment by webpro** [comment]
Sounds good to me, @hejmsdz! Let's use `--printSize` as the argument to override the paper size. Thank you in advance.

**Comment by hejmsdz** [comment]
I finally made a pull request. @webpro, please let me know if it meets your expectations.
