### ISSUE TITLE
Reveal-md does not work / any problem with recent updates?

### ISSUE THREAD

**Issue by ovitrac** [webpro/reveal-md#264]
Dear Webpro,
Many thanks for this great project. The previous versions were working fine on Ubuntu 16.04 and 18.04. I did not succeed to make `reveal-md `working on a fresh installation of a **Centos 7.6** with:
- _nodejs.x86_64   6.17.1-1.el7_
- _npm.x86_64 1:3.10.10-1.6.17.1.1.el7_
- _reveal-md@3.1.0_ 

The demo generates the following error:
[demo]> `reveal-md a.md`
/usr/lib/node_modules/reveal-md/bin/**reveal-md.js:29**

> (async () => {
        ^
 SyntaxError: Unexpected token (
     at createScript (vm.js:56:10)
     at Object.runInThisContext (vm.js:97:10)
     at Module._compile (module.js:549:28)
     at Object.Module._extensions..js (module.js:586:10)
     at Module.load (module.js:494:32)
     at tryModuleLoad (module.js:453:12)
     at Function.Module._load (module.js:445:3)
     at Module.runMain (module.js:611:10)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:160:9)

` node -p process.versions`
>{ http_parser: '2.8.0',
  node: '6.17.1',
  v8: '5.1.281.111',
  uv: '1.30.1',
  zlib: '1.2.7',
  ares: '1.10.1-DEV',
  icu: '50.1.2',
  modules: '48',
  napi: '3',
  openssl: '1.0.2k-fips' }

Do you have any clue?
Thanking you in advance, regards,
Olivier

**Comment by webpro** [comment]
Yes, you need Node v8 or higher (your system has Node v6).

(When installing reveal-md with npm, npm should give a warning.)

**Comment by ovitrac** [comment]
Thank you for your very prompt response. I installed Node v10 (it is bundled with npm v6.9.0). I followed your advice in a previous post: `npm install -g --no-optional reveal-md.`
Everything is fine now.

**Comment by caopeirui** [comment]
I followed your above advice, but the error `SyntaxError: Unexpected token` exists. How should I do?
My environment is
```
macOS 10.14.5
node v6.10.0
npm 6.13.1
```

**Comment by webpro** [comment]
As stated above:

> Yes, you need Node v8 or higher (your system has Node v6).

Since reveal-md v5 you need Node v10.
