### ISSUE TITLE
Unexpected behavior on Release 3.0.5

### ISSUE THREAD

**Issue by iegik** [webpro/reveal-md#269]
In release 3.0.5 changed behavior of image tag parsing. For example, in 3.0.4 I can write URL in columns:

```
# yUML

![](http://yuml.me/diagram/plain/class/
// {type:class},
// {direction:leftToRight},
// Cool Class Diagram,
[Customer]-orders*>[Order],
[Order]++-0..*>[LineItem],
[Order]-[Aggregate root],
)
```

Expected:

<img width="749" alt="Screenshot 2019-09-02 at 15 00 10" src="https://user-images.githubusercontent.com/175293/64113243-68e0e800-cd92-11e9-8d1c-65076ab9a623.png">

Result:

<img width="1252" alt="Screenshot 2019-09-02 at 15 01 30" src="https://user-images.githubusercontent.com/175293/64113317-a04f9480-cd92-11e9-8781-cda896a85fd0.png">

**Comment by webpro** [comment]
Ha, didn't even know this was possible.

This issue is likely due to the update from reveal.js 3.7.0 to 3.8.0, and maybe specifically the Markdown plugin. Could you please try your slides with reveal.js directly? My gut feelings tell me you will need to file an issue there.

**Comment by webpro** [comment]
Closing this issue, as it's not something reveal-md itself can fix.

One workaround, though, could be to [pre-process the Markdown](https://github.com/webpro/reveal-md#pre-process-markdown) to fix things before handing it over to the parser.
