### ISSUE TITLE
Flexbox in markdown

### ISSUE THREAD

**Issue by jakupmichaelsen** [webpro/reveal-md#271]
Hello.
I'm using CSS to use flexbox in reveal-md, but I was wondering if there's a way to implement it using markdown comments?

CSS
```
.flex-container {
	display: flex;
	flex-direction: row;
}

.flex-container > div {
	margin: 10px;
	padding: 20px;
}

```
In slides:
```
# Testing 

<div class="flex-container">
  <div>Item 1</div>
  <div>Item 2</div>
  <div>Item 3/div>
</div>
```

**Comment by webpro** [comment]
This depends on what reveal.js itself supports (https://github.com/hakimel/reveal.js/#markdown). Basically the only thing reveal-md is doing here is separating the slides, the rest is handled by reveal.js.

Therefore I'm going to close this issue, but feel free to discuss further.

**Comment by jakupmichaelsen** [comment]
Thanks for the feedback! I've posted the same question at the reveal.js repo (https://github.com/hakimel/reveal.js/issues/2478). Will update if I find a solution :)
