### ISSUE TITLE
Missing latest docker image

### ISSUE THREAD

**Issue by nautikos1235** [webpro/reveal-md#273]
Hello @webpro !

I see you created a docker hub account, but you did not publish any image with the `latest` tag that is referenced in the README:
```
docker run --rm -p 1948:1948 -v <path-to-your-slides>:/slides webpronl/reveal-md:latest
```

I think you should publish this tag or fix the doc (1st solution is best).
Were you able to setup image auto-build ?

**Comment by webpro** [comment]
In order to `docker push`, I need to authenticate:

```
❯ docker login hub.docker.com
Username: webpronl
Password: 
Error response from daemon: login attempt to https://hub.docker.com/v2/ failed with status: 404 Not Found
```

Then I tried to use `index.docker.io` as the server to login, which works, but then I still get:

```
❯ docker push webpronl/reveal-md:3.3.0
The push refers to repository [docker.io/webpronl/reveal-md]
...
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the docker.io registry NOW to avoid future disruption.
errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

Do you maybe have suggestions on how to proceed here?

**Comment by nautikos1235** [comment]
Have you tried `docker login docker.io`?
Don't know what the `index.` is about... But I don't think it's the registry url

**Comment by webpro** [comment]
Thanks! That did the trick, I've just pushed the latest tag: https://hub.docker.com/r/webpronl/reveal-md/tags

**Comment by nautikos1235** [comment]
Cool!
