### ISSUE TITLE
Local custom theme  path 

### ISSUE THREAD

**Issue by jakupmichaelsen** [webpro/reveal-md#274]
Is it possible to specify a custom, local, absolute path to my own theme, instead of having to place my css-file in `npm\node_modules\reveal-md\node_modules\reveal.js\css\theme`?

**Comment by webpro** [comment]
Yes, it's documented here: https://github.com/webpro/reveal-md#theme

Please let me know if anything is not clear or doesn't work for you.

**Comment by jakupmichaelsen** [comment]
Yeah that doesn't work :) 

Using sub-directories, like in the readme example, works perfectly. But I can't get it to work for any other, absolute path (e.g. `d:\GitHub\CSS\myTheme.css`)

**Comment by webpro** [comment]
Ah, I'm on MacOS, so not testing on Windows. That dir is passed verbatim to the `copy` function of the fs-extra package. Node.js should handle this properly cross-OS.

Maybe you can try something like this (quoted argument):

```
reveal-md [slides] --theme 'd:\GitHub\CSS\myTheme.css'
```

**Comment by jakupmichaelsen** [comment]
I've tried that as well. Also with both slashes and backslashes. None of the following works on Windows 10: 

```
reveal-md [slides] --theme d:\GitHub\CSS\myTheme.css
reveal-md [slides] --theme 'd:\GitHub\CSS\myTheme.css'
reveal-md [slides] --theme "d:\GitHub\CSS\myTheme.css"
reveal-md [slides] --theme d:/GitHub/CSS/myTheme.css
reveal-md [slides] --theme 'd:/GitHub/CSS/myTheme.css'
reveal-md [slides] --theme "d:/GitHub/CSS/myTheme.css"

**Comment by webpro** [comment]
In general, reveal-md was designed to use files from the directory of the slides or children thereof. That's why I'm going to close this issue, but feel free to discuss further or open a PR with a fix.
