### ISSUE TITLE
Error at static export: Source and destination must not be the same

### ISSUE THREAD

**Issue by cnoss** [webpro/reveal-md#276]
Hi Lars, 
I have a Setup with some additional Files. I use the static export only a couple of times a year. Until today it works fine, but now I receive an error message. This is mal command:
```reveal-md --highlight-theme Vs -w --scripts core/reveal-md-add-icons.js --preprocessor core/reveal-md-pre.js --static-dirs=assets --static static/2019/mi-emi-ui-sketching/ slidedecks/2019/mi-emi-ui-sketching/mi-emi-ui-sketching.md```

And here is the result:
<img width="946" alt="Bildschirmfoto 2019-10-14 um 20 51 05" src="https://user-images.githubusercontent.com/2807738/66775487-665ecb80-eec4-11e9-83bd-8db9ebaa96d0.png">

Thanks for your support.

**Comment by webpro** [comment]
Let's start by making this more readable:

```
reveal-md \
  --highlight-theme Vs \
  -w \
  --scripts core/reveal-md-add-icons.js \
  --preprocessor core/reveal-md-pre.js \
  --static-dirs=assets \
  --static static/2019/mi-emi-ui-sketching/ \
  slidedecks/2019/mi-emi-ui-sketching/mi-emi-ui-sketching.md
```

First of all, the `-w` (watch mode) can be removed.

As for the actual issue, please try to remove the output dir first. Does this help?

**Comment by cnoss** [comment]
Möööp. yes! Thank you.
