### ISSUE TITLE
`reveal.json` must be in json format

### ISSUE THREAD

**Issue by yoonghm** [webpro/reveal-md#28]
`reveal.json` must be in json format instead of javascript as in [https://github.com/hakimel/reveal.js#configuration](https://github.com/hakimel/reveal.js#configuration).

Options in `reveal.json` are also not used.

**Comment by webpro** [comment]
Hi @yoonghm,

They should indeed be in JSON format, not JS (it's implied by the file extension). I've linked to the Reveal.js #configuration docs so users can see what can be configured.

The `reveal.json` should be picked up. Are you using the latest version (v0.0.14))? Did you put the file in the root of the Markdown files directory? E.g. if you would do `reveal-md here` the file should be at "here/reveal.json".

**Comment by yoonghm** [comment]
It is working. Thanks.
