### ISSUE TITLE
Button to help code copy/paste ?

### ISSUE THREAD

**Issue by dacr** [webpro/reveal-md#281]
Something which can be very very helpful : adding a button to help copy/paste code, such as this small example in the top-right border :

![image](https://user-images.githubusercontent.com/381901/68483358-b1f26400-023b-11ea-84c2-0c7b5d281ea1.png)

**Comment by webpro** [comment]
Could you please be more clear about your feature request? Not sure how/where this fits in reveal-md.

**Comment by dacr** [comment]
Have a way to add a copy content buttons on all code block area such as :
![image](https://user-images.githubusercontent.com/381901/68745722-7c60c880-05f7-11ea-93e8-d76f47472d08.png)

And a way to activate this feature or not, through something like that in the reveal.json file:
```
{
  "controls": true,
  "show-copy-content-button":true
}
```

reveal-md is really a great tool, very useful, I use it for training purposes, and this feature would be very helpful as it is not always very easy to copy code content using a laptop trackpad for example, we've already seen many people (during trainings) reporting issues that were not really issues because they didn't copy all the content before trying to execute it...

**Comment by webpro** [comment]
Ah, I see. That would be a feature request to reveal.js itself or the plugin. Also see https://github.com/hakimel/reveal.js/#code-syntax-highlighting

Going to close this issue here.

**Comment by dacr** [comment]
OK thanks for your feedback. I've Just written : https://github.com/hakimel/reveal.js/issues/2528
