### ISSUE TITLE
Way to serve a single presentation, rather than a directory listing?

### ISSUE THREAD

**Issue by andyhall** [webpro/reveal-md#282]
Hi, sorry if I'm missing something obvious.

Is there a way to get the dev server to just serve a single presentation, rather than serving an index page linking to it?

That is, when doing `reveal-md index.md`, I'm looking for a way for the  `index.html` served locally to be the presentation, rather than a listing page that links to `/index.md`.

Thanks!

*Edit:* I see now that this already happens when statically building a single md file, so my question only applies to the dev server.

**Comment by webpro** [comment]
With e.g. `reveal-md slides.md` it should open the presentation (not the listing).

Maybe it's because you are using `index.md`, could you please try to rename it to e.g. `slides.md`?

**Comment by andyhall** [comment]
Hi, yes the page opened by default is the presentation, as you say. I'm asking about the page that gets served from the root of the dev server - e.g. when you manually open `localhost:1498` (or whichever is the correct port), you always get a file listing rather than the presentation. 

Is there a setting where the presentation gets served instead?

**Comment by webpro** [comment]
If that doesn't work with an `index.md`, then unfortunately no :)
