### ISSUE TITLE
whether the server host can be changed for external network access

### ISSUE THREAD

**Issue by jameslahm** [webpro/reveal-md#283]
I want to ask when I use `reveal-md slides.md` whether I can change the server host to make the presentation website accessible for the external network, not just the localhost.

I think it's a good feature to change the  server host, maybe add the option `-h host`

**Comment by webpro** [comment]
Use `--host [your-host]`

Not documented indeed 🙈

**Comment by jameslahm** [comment]
Sorry, I just find 🤣

**Comment by jameslahm** [comment]
Maybe it can be added into document😂
