### ISSUE TITLE
Static build runs a server too

### ISSUE THREAD

**Issue by siakaramalegos** [webpro/reveal-md#285]
Hi, thanks for building this tool! 

I love using it, but I noticed recently the static build also automatically starts serving the static build on a local server. 

```
reveal-md slides.md --static _site
```

![image](https://user-images.githubusercontent.com/4777393/69186754-d02f4e00-0ade-11ea-9817-6a1468866105.png)

This is disruptive to build pipelines since I then have to kill the server to run additional build commands (or if I wanted to use a solution like Netlify to serve static builds). 

Am I missing something in the build step? This used to work fine. If this was a change, can I suggest either dropping the automatic serving or splitting the current functionality into 2 different commands? Something like:

To generate the build files in _site:
```
reveal-md slides.md --static _site
```

To serve the build files in _site:
```
reveal-md --static-serve _site
```

**Comment by siakaramalegos** [comment]
For more context, I run a lot of extra bash steps to make my slides work with Github pages - like adding the .nojekyll file so it doesn't ignore underscore folders and copying my custom assets that don't seem to copy with the static build step. Then my last bash script add on is deploying to Github pages.

**Comment by webpro** [comment]
The `--static` does not serve anything, it only copies/exports files to the output directory. The error in your screenshot can be get rid of by removing the directory before making the static export.

Only when the "featured slide" option is used, the server is started to generate a preview image.

(I do see some sloppy coding in https://github.com/webpro/reveal-md/blob/master/bin/reveal-md.js (regarding `isStartServer` variable), but still it should not start any server.)

**Comment by webpro** [comment]
My apologies, @siakaramalegos. I was wrong in my previous comment (a server was started indeed). I was confused by the poor naming of the `isStartServer` variable at first glance. However, [v3.4.1](https://github.com/webpro/reveal-md/releases/tag/3.4.1) I've just released should no longer contain the bug. Thanks!
