### ISSUE TITLE
Remove the white border when printing the slides

### ISSUE THREAD

**Issue by silencej** [webpro/reveal-md#286]
When use `reveal-md main.md --print main.pdf`, there is a white border. I tried to inject print.css like below with no vail:

`@media print
{
  size: A4 landscape;
  margin: 0 !important;
}
`

The screenshot is like this:
<img src="https://i.imgur.com/sIXlGFj.png">

While I wannt it to be like:
<img src="https://i.imgur.com/i3d9vb8.png">

**Comment by webpro** [comment]
Try `--print-size` 

https://github.com/webpro/reveal-md#print-to-pdf

**Comment by silencej** [comment]
@webpro I tried `reveal-md test.md --print test.pdf --print-size A4` on the the following simple markdown, and it doesn't work either -- the white border still appears in the PDF.

test.md:

```markdown
# Test

This is a test

---

## Test 2

Test 2.
```

**Comment by webpro** [comment]
You can also try to print from (different) browser(s): https://github.com/webpro/reveal-md#print-to-pdf

Or use `px` or `mm` for paper size.

**Comment by movd** [comment]
Having the same issue. I aim to create my slide as a PDF with 16:9 dimensions. Puppeteer is set up correctly but something in CSS or Frontend-CSS causes problems.

```md

# Test

This is the cover

---

## Test 2

Test 2.

---

### Slide 3

Welcome to slide 3
```

```sh
$ DEBUG=reveal-md reveal-md slides/print-test.md --print slides/print-test.pdf --print-size 1920x1080
px
Reveal-server started at http://localhost:1948
  reveal-md { initialUrl: 'http://localhost:1948/print-test.md',
  reveal-md   printPluginPath:
  reveal-md    '/home/moritz/.npm-packages/lib/node_modules/reveal-md/node_modules/reveal.js/plugin/print-pdf/print-pdf.js',
  reveal-md   pdfFilename: 'slides/print-test.pdf',
  reveal-md   puppeteerLaunchConfig: { args: [], executablePath: null } } +0ms
Attempting to print "print-test.md" to "slides/print-test.pdf".
```

results in: 

![2020-01-24_14-11-28-screenshot](https://user-images.githubusercontent.com/22394314/73071927-4a4fca80-3eb4-11ea-99ed-09dd5765f74c.png)

When setting custom "width" or "height" via YAML-FrontmatterI only get a black single page pdf.

```md
---
revealOptions:
  width: 1920px
  height: 1080px
---

# Test

This is the cover

---

## Test 2

Test 2.

---

### Slide 3

Welcome to slide 3
```

**Comment by movd** [comment]
My mistake. I needed to set width and height without `px`. For best results the `print-size` should match. You can just set this via Frontmatter:

Input:

```md
---
revealOptions:
  width: 1920
  height: 1080
---

# Test

This is the cover

---

## Test 2

Test 2.

---

### Slide 3

Welcome to slide 3
```
```sh
$ reveal-md slides/test-169.md --print slides/test-169.pdf --print-size 1920x1080
```

Result:

![2020-01-27_13-15-09-screenshot](https://user-images.githubusercontent.com/22394314/73174246-934b8d00-4107-11ea-9c8e-a84575bdf681.png)
