### ISSUE TITLE
How to insert a picture in a slide?

### ISSUE THREAD

**Issue by Rylai-Zihang** [webpro/reveal-md#288]
I wonder how to insert a picture( like <img>) into a slide?
And I find that markdown tables are not supported well.

**Comment by webpro** [comment]
> I wonder how to insert a picture( like ) into a slide?

It's regular Markdown, so see e.g. https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

> And I find that markdown tables are not supported well.

The underlying presentation library is [reveal.js](https://github.com/hakimel/reveal.js/), which uses a Markdown parser/renderer: https://github.com/hakimel/reveal.js/#markdown. In other words, reveal-md can't do much here.
