### ISSUE TITLE
Error while generating PDF for "demo.md"

### ISSUE THREAD

**Issue by JingwangLi** [webpro/reveal-md#291]
When I use the cmd "reveal-md D://demo.md --print D://demo.pdf" to generate the pdf, the following error happened:
![image](https://user-images.githubusercontent.com/29228612/70857685-3ff1f680-1f2e-11ea-8b18-3a40b39a9294.png)

I also checked the previous issues related to this problem but they didn't help me, and I'm sure the puppeteer were installed successfully.
![image](https://user-images.githubusercontent.com/29228612/70857699-8c3d3680-1f2e-11ea-8a8a-6646d1fb89a6.png)

So what's wrong? My operation system is win10 1903 x64.@webpro

**Comment by webpro** [comment]
Unfortunately I don't have a Windows machine to check, but can you can try to go to `D:\` first and use reveal-md from the same drive?

**Comment by JingwangLi** [comment]
> Unfortunately I don't have a Windows machine to check, but can you can try to go to `D:\` first and use reveal-md from the same drive?

Thank you for you replying! But this didn't work, still same error. And I tried other demo file downing from this repository, also failed.
![image](https://user-images.githubusercontent.com/29228612/70865190-90e90580-1f95-11ea-8c5c-4d4f23697f01.png)

**Comment by webpro** [comment]
Did you try to use this? Not sure how to set `DEBUG` in Windows environment:

```
set DEBUG=* & reveal-md demo.md --print
```

**Comment by JingwangLi** [comment]
> Did you try to use this? Not sure how to set `DEBUG` in Windows environment:
> 
> ```
> set DEBUG=* & reveal-md demo.md --print
> ```

I tried the “DEBUG=reveal-md...” before, then I realized it was't Windows cmd.  I will try to debug it later but now I need to prepare my exam. Thank you!

**Comment by JingwangLi** [comment]
I also solved this problem, it's because of the version of chromium of the puppeteer. But there's a new problem, I will open a new issue.

**Comment by LiZeC123** [comment]
> I also solved this problem, it's because of the version of chromium of the puppeteer. But there's a new problem, I will open a new issue.

@JingwangLi could you please give more information about this issue? I have the same problem(can't print), but I am not understand the mean of the version of chrominum, what should I do for the version?
