### ISSUE TITLE
live-reload doesn't work

### ISSUE THREAD

**Issue by JingwangLi** [webpro/reveal-md#292]
When I use the live-reload function by adding the "-w" parameter like this:
"reveal-md D://demo.md -w"
the following error happened:

![image](https://user-images.githubusercontent.com/29228612/70857762-9f9cd180-1f2f-11ea-9b48-169c2c40de43.png)

My operation system is win10 1903 x64. How can I to fix this problem? @webpro

**Comment by webpro** [comment]
Unfortunately I don't have a Windows machine to check, but can you can try to go to `D:\` first and use reveal-md from the same drive?

**Comment by JingwangLi** [comment]
> Unfortunately I don't have a Windows machine to check, but can you can try to go to `D:\` first and use reveal-md from the same drive?

Thank you vary much! This problem was solved by running reveal-md in the same path with the md file.
