### ISSUE TITLE
Script load options?

### ISSUE THREAD

**Issue by csbrown** [webpro/reveal-md#293]
The normal `<script></script>` html tag takes various options.  These include `charset`, `type` and [some others](https://www.w3schools.com/Tags/tag_script.asp).  How do we pass script tag options to additional custom scripts that we load into reveal-md?

**Comment by webpro** [comment]
This isn't possible with the default template.

However, you can create a custom template and add any HTML you need: https://github.com/webpro/reveal-md#custom-template
