### ISSUE TITLE
About changing the font type and font size

### ISSUE THREAD

**Issue by JingwangLi** [webpro/reveal-md#295]
I have seen the docs:
"Custom CSS
Inject custom CSS into the page:
 reveal-md slides.md --css style.css,another-style.css"

I'm confused, does it mean that I need to write two css file and put them file in the same path with md file to change the font type and size ?  but why two css? Or  "style.css,another-style.css" belong to reveal-md?  If so , how to use?
I also tried the html method, just as the following:
![image](https://user-images.githubusercontent.com/29228612/71332693-1cecc580-2572-11ea-86f5-8039b5b54afd.png)

It worked, but I found it's differerent from the html, because every "font face="TimesNewRoman"" only influence the slide where it belongs to,
even if you put the corresponding "/font“ in the end of the md file. So I have to put the  "font face="TimesNewRoman""  in every slide, it will be too annoying when I have lots of slides.

So could you make it more concrete about the "Custom CSS" method or give me a suggestion about how to make the  "font face="TimesNewRoman""  working for all slides in the md file?

Thank you vary much!

**Comment by webpro** [comment]
```
reveal-md slides.md --css style.css,another-style.css
```

This means you can add e.g. a `style.css` file next to your Markdown file (`slides.md` in the example). You can also add multiple stylesheet files by putting a comma in between them (as per the example).

You will need to inspect the HTML to see what HTML tags and class names you need for your CSS selectors.
