### ISSUE TITLE
I want to fix the conflicts between LaTeX and Markdown but need some advice

### ISSUE THREAD

**Issue by JingwangLi** [webpro/reveal-md#296]
For reveal.js, there are  conflicts between LaTeX and Markdown. The docs of reveal.js said "If you want to include math inside of a presentation written in Markdown you need to wrap the formula in backticks. This prevents syntax conflicts between LaTeX and Markdown. " But it will become too annoying if have too many math formulas. At first, I try to fix the conflicts in the source codes of reveal.js, but I didn't succeed. So I want to solve it in reveal-md.js by generating a new md file(just existing in the running time of reveal-md.js, not really generating) which 
 has "\` " for all math formulas comparing to the origin md file which doesn't have "\`" . I think it's not hard by using the Regular Expression. 
However, I'm not familiar with the reveal-md.js. Could you give me some advice about where should I put the module on comfortable? I have checked the "\bin\reveal-md.js" but still have no idea.

**Comment by webpro** [comment]
Sounds like you could use a preprocessor? With a script, you can modify the original Markdown before it is parsed by the Markdown/Latex.

Could that be an option? Please let me know.

**Comment by webpro** [comment]
See https://github.com/webpro/reveal-md#pre-process-markdown
