### ISSUE TITLE
the printed pdf doesn't show the math formula even though the html is good.

### ISSUE THREAD

**Issue by JingwangLi** [webpro/reveal-md#297]
I found the the printed pdf doesn't show the math formula even though the html is good. 
![image](https://user-images.githubusercontent.com/29228612/71585042-354f7800-2b50-11ea-99dd-941af0f46456.png)

![image](https://user-images.githubusercontent.com/29228612/71585023-181aa980-2b50-11ea-8ddd-7b101387b18a.png)

**Comment by webpro** [comment]
I'm sorry, @JingwangLi, not much I can do for you here. But of course I will let this issue open in case others can help out.
