### ISSUE TITLE
Static index doesn't use the correct paths for css and js

### ISSUE THREAD

**Issue by Taluu** [webpro/reveal-md#298]
When calling `yarn run reveal-md sources/ --static slides/` (I guess it's pretty much the same for global install ?), where in my `sources` directory I have a directory per presentation, it generates everything and their directory into `slides` which is as expected.

In this directory, I have a directory per presentation, which is also as expected (even though it has a lot of repeating stuff but I digress). When going onto each of these directories on my browser, the presentation is OK, which is also as expected.

What is not expected though, is that I have a `index.html` in the slides directory, which points to each presentation... But the CSS and JS loading lods from the root of the domain (`/css/...`, `/js/...`) while in each presentation it does it from a relative path (`./css/...`, `./js/...`).

So it doesn't find the css and js (have (404s on the slides directory), and I end up with a blank screen instead... Shouldn't the "root" index be also generated with relative paths ?

My goal being to be able to publish my slide on a github page in a nested directory.

**Comment by webpro** [comment]
I think I can't reproduce this. When I do a static export of the `demo` folder of this repo, and serve the static files inside the new `slides` directory, I can view each presentation as expected.

For example, in `sub/deep/d.html` there is (correctly):

```
<link rel="stylesheet" href="./../../css/reveal.css" />
```

So I'm not sure why you have a different output, right? Do you use the latest version of reveal-md?

**Comment by Taluu** [comment]
Just tried again with the latest, each presentations have indeed the correct path, but not the `index.html` served that gives a link to each generated presentation (the one with the links to the directories of each presentations) : it seems to be hardcoded as `/css` instead of expected `./css` or something like that.

I am running with `yarn run reveal-md sources/ --static slides/ --theme ${THEME}`, with `sources` being a top directory containing directories for each one of my presentations (the md slides, their assets, ...).

This generates a `slides` directory, with an `index.html` file that points to as many directories as many presentations I have. Each of these presentations have an entrypoint that has the correct path for css and js (`../css`, `../js`), but not the `index.html` generated into my `slides` directory.

**Comment by Taluu** [comment]
Here are the generated html files (redacted as there's some private stuff) :

```html
<!-- slides/index.html //-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Directory Listing</title>
    <link rel="stylesheet" href="/css/theme/moon.css" id="theme" />
    <style type="text/css">
      body {
        margin: 1em;
      }
      a {
        color: white;
        display: block;
      }
    </style>
  </head>

  <body>
    <a href="first-presentation/slides.html">first-presentation/slides.html</a><br><a href="second-presentation/slides.html">second-presentation/slides.html</a>
  </body>
</html>
```

```
<!-- slides/first-presentation/slides.html //-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <title>first presentation</title>
    <link rel="stylesheet" href="./../css/reveal.css" />
    <link rel="stylesheet" href="./../css/theme/moon.css" id="theme" />
    <link rel="stylesheet" href="./../css/highlight/solarized-dark.css" />
    <link rel="stylesheet" href="./../css/print/paper.css" type="text/css" media="print" />

  </head>
  <body>
    <div class="reveal">
      <div class="slides"><section  data-markdown><script type="text/template">
		<!-- my content //-->
	  </script></section></div>
    </div>

    <script src="./../js/reveal.js"></script>

    <script>
      function extend() {
        var target = {};
        for (var i = 0; i < arguments.length; i++) {
          var source = arguments[i];
          for (var key in source) {
            if (source.hasOwnProperty(key)) {
              target[key] = source[key];
            }
          }
        }
        return target;
      }

      // Optional libraries used to extend on reveal.js
      var deps = [
        { src: './../plugin/markdown/marked.js', condition: function() { return !!document.querySelector('[data-markdown]'); } },
        { src: './../plugin/markdown/markdown.js', condition: function() { return !!document.querySelector('[data-markdown]'); } },
        { src: './../plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
        { src: './../plugin/zoom-js/zoom.js', async: true },
        { src: './../plugin/notes/notes.js', async: true },
        { src: './../plugin/math/math.js', async: true }
      ];

      // default options to init reveal.js
      var defaultOptions = {
        controls: true,
        progress: true,
        history: true,
        center: true,
        transition: 'default', // none/fade/slide/convex/concave/zoom
        dependencies: deps
      };

      // options from URL query string
      var queryOptions = Reveal.getQueryHash() || {};

      var options = extend(defaultOptions, {"transition":"slide"}, queryOptions);
    </script>


    <script>
      Reveal.initialize(options);
    </script>
  </body>
</html>

```

My goal being able to access the listing of slides as `my-domain.tld/slides`.

**Comment by davidovich** [comment]
I have this error too. Rendering using the default `listing.html` template does not seem to get the same value of `{{{themeURL}}}` as rendering with `reveal.html`. 

With the former (listing.html), the value is `/css/theme/black.css` and on the latter, it is (in my code hierarchy) `./css/theme/black.css`. 

This is only a workaround, but If I prepend a `'.'` in a copy of listing.html:

```html
...
<link rel="stylesheet" href=".{{{themeUrl}}}" id="theme" />
...
```

The listing works.

**Comment by webpro** [comment]
Thanks guys, I just published [v3.4.3](https://github.com/webpro/reveal-md/releases/tag/3.4.3) which should fix this issue.

**Comment by davidovich** [comment]
Fix confirmed (by using latest tagged image :-)). Thanks @webpro.

**Comment by Taluu** [comment]
Fix confirmed. Thanks ! :}
