### ISSUE TITLE
More flexible reveal.json lookup

### ISSUE THREAD

**Issue by justmytwospence** [webpro/reveal-md#30]
I propose that `$HOME/reveal.json` or `$HOME/.reveal.json` be a fallback when a `reveal.json` is not located in the root directory of the markdown files. Also, a command line to point to a configuration file (`-c`?), would be nice. Thoughts?

**Comment by webpro** [comment]
Good idea, PR welcome!

**Comment by justmytwospence** [comment]
Cool, I'll take a look this weeknd.
