### ISSUE TITLE
publish a new 3.4.2 image ? 

### ISSUE THREAD

**Issue by davidovich** [webpro/reveal-md#301]
The latest image version on dockerhub is at v3.3.0, is it possible to publish a new image version ?

Ideally, this should be automated to avoid grunt work, would you be interested in this contribution (with [github actions](https://github.com/marketplace/actions/publish-docker) for example)?

**Comment by webpro** [comment]
Thanks @davidovich, I think many users (including myself) are interested in some form of auto-updated docker images! I guess GitHub Actions would be a cool way to do this :-)

**Comment by davidovich** [comment]
In the meantime, can a newer version be pushed ? :-)
