### ISSUE TITLE
Documentation fix needed: --css parameter must be used with relative path

### ISSUE THREAD

**Issue by greg-witczak** [webpro/reveal-md#303]
After few hours of crazy debugging I found out that `reveal-md` parameter `--css` must be used with a relative path (eg. `mycommons/custom.css`), not an absolute one (eg. `/home/user/slides/mycommons/custom.css`). Absolute path causes css file to be somehow invalid, and browser's developer tools show that `custom.css` file content is... html with file listing. I believe it might be related to #280.

**Comment by webpro** [comment]
Sorry for the inconvenience, @greg-witczak. I'll hope to fix this bug soon. Feel free to fix the documentation for now, or even fix the bug in a PR.
