### ISSUE TITLE
Add reveal.js-menu plugin

### ISSUE THREAD

**Issue by chbndrhnns** [webpro/reveal-md#312]
I tried to add this plugin myself but it would require lots of changes to --css and --scripts parameters due to the many files.

Would it be possible to add it to the included plugins?

**Comment by chbndrhnns** [comment]
It was easier than I thought. Instead of using `yarn add reveal.js-menu`, I put the plugin content into my `assets` folder.

**Comment by Ouch1978** [comment]
Hi @chbndrhnns,

I'm trying to add plugins into my slides according to [this](https://github.com/webpro/reveal-md/issues/102#issuecomment-692494366), but in vain. 

Would you please explain how you made it?

Thank you.

**Comment by Ouch1978** [comment]
I finally figure it out.

Just execute 
```shell
reveal-md slides/Test1.md
```

without `--scripts plugin.js` is working for me.
