### ISSUE TITLE
How get rid of black border with picture??

### ISSUE THREAD

**Issue by JunyiHe** [webpro/reveal-md#314]
my markdown code：
```
<img src="https://braybaut.com/images/Gopher-aws.png" width="692" height="300" alt="Go" align=left/>
```

picture int the slide：
![image](https://user-images.githubusercontent.com/9150170/81497473-43c55180-92f1-11ea-9af2-274f05ba88d1.png)

**Comment by JunyiHe** [comment]
use custom css to solved, sorry to trouble

**Comment by davidovich** [comment]
you can add  `<!-- .element: style="border: 0;" -->` inline to your markdown image reference.
