### ISSUE TITLE
Question: howto exclude chromium from "npm install reveal-md"

### ISSUE THREAD

**Issue by gaerfield** [webpro/reveal-md#319]
I've created a [template](https://github.com/gaerfield/reveal-md-github-pages)-repository which builds and then deploys to github-pages. The first build went fine, but subsequent ones running forever - my guess is, because chromium is downloaded on npm install.
Is it possible to ignore chromium for `npm install reveal-md` somehow or do I really need to create my own package.json where I remove the optional dependency?

**Comment by webpro** [comment]
Using `--no-optional` prevents puppeteer (which has chromium) from being installed.

**Comment by gaerfield** [comment]
Awesome! Thank you sir :vulcan_salute:
