### ISSUE TITLE
Custom LaTeX commands

### ISSUE THREAD

**Issue by mgenet** [webpro/reveal-md#320]
Hello,

Is there a way to load a LaTeX file containing custom commands and definitions? Thanks!

Martin

**Comment by webpro** [comment]
Not sure how those files look like or how they can be loaded, but you can add extra scripts and styles as described here:

https://github.com/webpro/reveal-md#custom-scripts

**Comment by mgenet** [comment]
Thanks! For instance one could have a file named `latexdefs.sty` containing
```latex
\newcommand{\p}[1]{\left( #1 \right)}
```
and allowing to compile the following reveal-md
```
$$
    f\p{x} = \sin{x}
$$
```
