### ISSUE TITLE
Way to share custom scripts

### ISSUE THREAD

**Issue by amra** [webpro/reveal-md#327]
There is plenty of custom scripts developed by users. My favorite one is integrating mermaidjs: https://github.com/webpro/reveal-md/issues/197#issuecomment-617112770

Create a way how users can simply share these scripts and discover some others. 

Maybe an git repo for start.

**Comment by webpro** [comment]
Good idea! Feel free to open a repo for this. For starters, we could use the wiki of this repo as well. I'm happy to help. At least we could link to it from the main readme.

**Comment by amra** [comment]
It took a little bit time to add first mermaid script: https://github.com/amra/reveal-md-scripts
