### ISSUE TITLE
Attributes in Markdown

### ISSUE THREAD

**Issue by Johanneslueke** [webpro/reveal-md#328]
See Issue at [reveal.js #Issue 639](https://github.com/hakimel/reveal.js/pull/639) and [reveal.js #Issue 430](https://github.com/hakimel/reveal.js/issues/430)

It is possible to link between different Slides. To Enable this 
reveal-md must produce an additional attribute for the section tag.

- Currently `<section data-markdown>`  

- Required `<section data-attributes="^\s*?--\s(.*?)$"  data-markdown>`

reveal-md is missing this possibility

**Comment by webpro** [comment]
See https://raw.githubusercontent.com/webpro/reveal-md/master/demo/sub/deep/d.md for an example

**Comment by Johanneslueke** [comment]
Well,

sometimes the solution to a problem is easier then expected
thanks a lot for the quick response.

it did indeed solve my problem :D

**Comment by webpro** [comment]
Glad to hear!

Although it would be more elegant in larger decks with id's (as numbers change when you insert a slide).

**Comment by Johanneslueke** [comment]
shall we reopen the issue and work on it? happy to contribute as it appears to have to do with slidify. if we find the proper way to parameterize slidify to add the data-attributes attribute, it should be possible to achieve relative short time. at least i hope so :D
