### ISSUE TITLE
Java Code Tag seems broken with generics

### ISSUE THREAD

**Issue by MatthewKhouzam** [webpro/reveal-md#329]
I have attached a file to describe the bug.

Basically, if there are generics in the ~~~java block, they are treated as HTML tags and are formatted wrong. A workaround is to use `&lt;` instead of `<` but this makes the code uncopyable for people looking directly at the code and untranscribable too.

~~~java
ITimeGraphEntry getParent();
List<Integer> getChildren();
String getName();
boolean hasTimeEvents();
Iterator<? extends Number> getIterator();
~~~
gives in typora
![image](https://user-images.githubusercontent.com/419535/86818398-555a7980-c054-11ea-8220-11f1f28c965c.png)

but in reveal-md
![image](https://user-images.githubusercontent.com/419535/86809410-d9f3ca80-c049-11ea-8b85-07d781c0919d.png)

Conversely:
~~~java
ITimeGraphEntry getParent();
List&lt;Integer> getChildren();
String getName();
boolean hasTimeEvents();
Iterator&lt;? extends Number> getIterator();
~~~
Gives in typora
![image](https://user-images.githubusercontent.com/419535/86818468-6c996700-c054-11ea-9e83-62708c80760d.png)

but 
![image](https://user-images.githubusercontent.com/419535/86809645-11fb0d80-c04a-11ea-9c2c-e2c8f11200ec.png)
in reveal-md

I have attached the example file below.
[test.zip](https://github.com/webpro/reveal-md/files/4885859/test.zip)

I would like to think this is a regression, as with version 3.4.7 it worked properly, with version 4.1.0 it does not. Also, the github issue shows the markdown properly too.

**Comment by MatthewKhouzam** [comment]
Update, github issues markdown displays the data properly. :)

**Comment by MatthewKhouzam** [comment]
Also the issue occurred somewhere between reveal 3.4.7 and 4.1.0

**Comment by clux** [comment]
Also ran into this, could not get a good solution. There's similar issues reported upstream: https://github.com/hakimel/reveal.js/issues/2684

Ended up search and replacing all generics tags (< and >) with the "equivalent" from the [Canadian Aboriginal Syllabics Unicode block](https://en.wikipedia.org/wiki/Unified_Canadian_Aboriginal_Syllabics_(Unicode_block)).

E.g.:

```rust
pub struct ApiᐸKᐳ {
    resource: Resource,
    client: Client,
    phantom: PhantomDataᐸKᐳ,
}

let api: ApiᐸPodᐳ = Api::namespaced(client, ns);
```

`¯\_( ツ )_/¯`

**Comment by MatthewKhouzam** [comment]
It probably is from the issue upstream. My issue: if we use aboriginal codes, we're basically breaking copy-paste.

**Comment by clux** [comment]
Yeah, it's definitely not a great solution. Maybe there's something that can be done using the [markdown preprocessor support](https://github.com/webpro/reveal-md#pre-process-markdown) to try to inject that extra `<script type="text/template">` tag around your `<code>`?

**Comment by MatthewKhouzam** [comment]
I was looking at the bug one level higher, my issue is that everyone works one way, reveal seems to work another... I will test it out, but I want to make sure our markdown isn't shackled to reveal.

**Comment by clux** [comment]
I've found a pretty crappy solution to replace `<` with `&lt` automatically by a preprocessor.

```js
module.exports = (markdown, options) => {
  return new Promise((resolve, reject) => {
    let in_code = false;
    return resolve(
      markdown
        .split('\n')
        .map((line, index) => {
          if (!/^```/.test(line) || index === 0) {
            if (in_code) {
              return line.replace('<', "&lt").replace('>', '&gt');
            }
            return line;
          }
          in_code = !in_code;
          return line;
        })
        .join('\n')
    );
  });
};
```

Works if you load `reveal-md` with `--preprocessor that-file/pre-hack.js`
