### ISSUE TITLE
I have a problem with slide separation

### ISSUE THREAD

**Issue by jeud** [webpro/reveal-md#33]
I'm currently using `---` as mentioned in the documentation, but when using `reveal-md myslide.md` these contents are in only one side.

Please guide.

    # Getting Started using AngularJS

    ---

    ## Instructor

    Kongthap Thammachat (tutor4dev)

    ---

    ## Sample Code

	$http.get(url)
		.success(function(data) {
			defer.resolve(data);
		});

    ---

Thanks
Kongthap

**Comment by webpro** [comment]
That's odd. If I copy this Markdown and open it with `reveal-md` I'm getting multiple slides as intended.

Maybe it's because of line endings. It looks for `^\n---\n$` by default, maybe you have `\r\n` in your Markdown file? Probably I should fix that regexp anyway.

**Comment by jeud** [comment]
@webpro is it about Windows? I'm using Windows 7 and I got some errors while installing reveal-md using NPM, it said about MS Build or something, but when running it, there was no errors at all

I'm using Subime Text, is there any way around i can see what's kind of line break is saved on the file?

Anyway thanks for this awesome ecosystem

**Comment by webpro** [comment]
I don't know how Sublime (for Windows) saves EOLs. Would be nice if you'd find a way to see EOL character(s) in your file. Then I might have a fix.

**Comment by jeud** [comment]
@webpro I just changed EOL to *unix* and it's just working like magic :)
Thanks for this wonderful ecosystem you've made

**Comment by webpro** [comment]
Thanks, good to hear! I'm going to fix it in reveal-md anyway (it should just work without worrying about EOL characters).

**Comment by webpro** [comment]
Just released v0.0.18, which should work with any of `\n`, `\r`, `\r\n` for EOLs.
