### ISSUE TITLE
Printing in portrait mode

### ISSUE THREAD

**Issue by sujee** [webpro/reveal-md#333]
is it possible to print in portrait mode?  Slide on top half + notes on the bottom half?

![image](https://user-images.githubusercontent.com/221159/89071002-c971ff80-d32a-11ea-9686-f2952d098b1b.png)

**Comment by webpro** [comment]
See https://github.com/webpro/reveal-md#print-to-pdf - so you can try to set the print dimensions.

An alternative could be to add [custom CSS](https://github.com/webpro/reveal-md#custom-css)
