### ISSUE TITLE
Disable autofilling missing HTML closing tags in Reveal MD

### ISSUE THREAD

**Issue by ptokarski** [webpro/reveal-md#335]
The following code:

    ```python
    x = '<x>'
    ```

Evaluates in Reveal MD to:

    x = '<x>'</x>

I suppose that Reveal MD tries to explore HTML tags and in case of missing closing tags found it closes them automatically. Is there any way to block this feature? This is obviously an unexpected behaviour - I specified explicitly after backticks that my intention was to put Python code, not HTML one.

**Comment by webpro** [comment]
Hi @ptokarski, this is an issue in reveal.js, and it seems to have been fixed (see e.g. https://github.com/hakimel/reveal.js/issues/2744). So when this is available in a new version of reveal.js I can update to it.

**Comment by webpro** [comment]
Seems to be fixed in reveal.js and I just updated and released reveal-md with it. Closing this issue.
