### ISSUE TITLE
Avoid height-centering screen-width images when there is more than one image

### ISSUE THREAD

**Issue by axfelix** [webpro/reveal-md#338]
This might not be an issue with reveal-md rather than reaveal.js, but I'm curious about how it's generating your layout here:

If I have a slide that just contains a single ~1280px wide gif like so:

```
---

![](bbb-bad.gif)

---
```

reveal-md automatically generates you a slide with that image height-centred. However, if you have two such images, and you'd like them displayed stacked vertically:

```
---

![](bbb.gif)
![](bbb-bad.gif)

---

```

The first one is always height-centred, and the second one is always missing from the bottom of the page.

**Comment by webpro** [comment]
I think you would need to look into the reveal.js styling and overwrite it with some custom styling.

Maybe your question is more about how to do this styling?

**Comment by axfelix** [comment]
Yeah, I played with the reveal.js css after opening this bug and it really doesn't like to support this -- it's strongly biased toward vertically centering a single square image. I think I'll close this issue though, since I don't think it's on reveal-md to support.
