### ISSUE TITLE
Enable auto-animate globally

### ISSUE THREAD

**Issue by jakupmichaelsen** [webpro/reveal-md#339]
Would it be possible to configure reveal-md to have auto-animate enabled globally by default?

**Comment by webpro** [comment]
You can put reveal.js configuration in `reveal.json` (https://github.com/webpro/reveal-md#revealjs-options)

**Comment by jakupmichaelsen** [comment]
Can you also put it into reveal-md's `defaults.json` file, in `"revealOptions" {}`? 

And I don't know what I'm doing wrong. I've tried using `"auto-animate": true` and `"autoAnimate": true` in both `reveal.json`, at the MD-file's root folder, and in `defaults.json` with no effect.

**Comment by webpro** [comment]
Just checked and using these files have the same effect (mind the file names):

reveal.json

```json
{
  "auto-animate": true
}
```

reveal-md.json

```json
{
  "revealOptions": {
    "auto-animate": true
  }
}
```

Even when used both, the options are merged and used as `Reveal.initialize(options)`. You can verify this when doing a "view source" in the browser, the relevant lines are at the end:

```js
var options = extend(defaultOptions, {"anything":true,"auto-animate":true}, queryOptions);

Reveal.initialize(options);
```

However, I don't know the actual options and what reveal.js does with it.

**Comment by gunhaxxor** [comment]
It should be noted that the auto-animate option is used to globally __disable__ auto-animate. 
autoAnimate: true ----> the data-auto-animate attribute can be used in slides to make elements auto animate
atuoAnimate: false ----> the data-auto-animate attribute has no effect

That is to say: setting autoAnimate to true will _not_ make elements auto animate throughout the slide deck


This is at least my understanding of how it works 👍
