### ISSUE TITLE
A question about `</body>`, `</script>`

### ISSUE THREAD

**Issue by jeud** [webpro/reveal-md#34]
Hi, I have got another question to bother you

I have experienced some problems using HTML tag e.g. `</body>`, `</script>`

    HTML

	<body>
		Hello World
		<script src="angular.min.js"></ script>
		<script src="angular-animate.min.js"></script>
	</body>

![](http://i.cubeupload.com/6uLOCX.png)

`</ script>` and `</ body>` would cause no problems

Any guides for me please ?

Thanks.

**Comment by webpro** [comment]
Sorry, I don't know how you include this in your Markdown and I haven't tried the highlighter. Maybe you need to escape like `<\/body>`?

**Comment by jeud** [comment]
@webpro I have tried to worked around using `<\/script>`, `&lt;/script&gt` but still not get it working, these escape characters did not get transformed into to `</script>` when they are surrounded by `<script type="text/template">...</script>`

**Comment by webpro** [comment]
I think the problem is not in reveal-md. Please see https://github.com/hakimel/reveal.js/issues/797 and https://github.com/hakimel/reveal.js/issues/1157. Closing this here, but feel free to discuss further.

**Comment by jeud** [comment]
Thanks :)
