### ISSUE TITLE
[Feature request] CLI argument for revealOptions

### ISSUE THREAD

**Issue by astik** [webpro/reveal-md#340]
Hi,

Right now, the project allows some configuration on the CLI (` --theme`, `--highlight-theme`, `--separator`, `--vertical-separator`, `--preprocessor`).
It would be great to be able to pass reveal options as well. For example, it could be something like this:

```sh
reveal-md --revealOptions '{"transition": "fade"}'
```

If you do so in current code base, `revealOptions` goes down to config.js' getRevealOptions (https://github.com/webpro/reveal-md/blob/master/lib/config.js#L59) and it messes up with lodash `_.defaults`.

Having something like a JSON.parse before getting here would be perfect =D

**Comment by webpro** [comment]
Sounds like a good idea, would you be up for a PR?

By the way, just to be sure, you can already put reveal.js options in a `reveal.json` file.

**Comment by astik** [comment]
Glad you like the idea =)
I've seen the configuration possibility in `reveal.json` but it does not match my use case =D
I'll be up for a PR =P
