### ISSUE TITLE
Way to share custom scripts ()

### ISSUE THREAD

**Issue by amra** [webpro/reveal-md#341]
I did create a first script which adds support for mermaid graphs: https://github.com/amra/reveal-md-scripts

It would be helpful, if the repo link is shared in the main README file.

I created new issue, because the original one is already closed: https://github.com/webpro/reveal-md/issues/327

**Comment by webpro** [comment]
Thank you @amra! I appreciate you put up the scripts in a repo, I'm happy to link to it from the readme.
