### ISSUE TITLE
--static with multiple input files fails because it's trying to do the same thing multiple times

### ISSUE THREAD

**Issue by kendfrey** [webpro/reveal-md#343]
### Steps:

1. Create a project with the following layout:
```
+- src
|  +- 1.md
|  +- 2.md
|  | ...
|  \- n.md
\- script.js
```
2. Run `reveal-md src --scripts script.js --static html`

### Actual Result:

`Error: EBUSY: resource busy or locked, copyfile 'C:\project\script.js' -> 'C:\project\html\_assets\script.js'`

or a similar file system error.

### Expected Result:

Anything common to multiple pages should only be built once. For example:

- Assets (verified to be problematic)
- Highlight.js themes (verified to be problematic)
- Reveal.js files
- index.html
- Deletion of existing built assets (verified to be problematic)

### Severity:

With my project containing two input files, this happens roughly 1/3 of the time (except deletion of existing built assets, which happens consistently if I don't remove the output folder before each build). This is annoying but non-critical. Adding more input files will make it happen more often.

With a test project containing 6 input files, it happens consistently.

**Comment by webpro** [comment]
Thanks @kendfrey, guess Windows users are affected more by this (haven't seen many complaints from Linux/macOS users). I have just released a patch release to copy files only once ([v4.1.6](https://github.com/webpro/reveal-md/releases/tag/4.1.6))
