### ISSUE TITLE
Print-ready docker image?

### ISSUE THREAD

**Issue by Ninja73737** [webpro/reveal-md#344]
Hello! I recently discovered this project and have been loving it, but I was trying to print from the docker image and ran into some issues. I saw the issue #239 and got it working, but adding all that stuff after installing the container kind of takes away from some of the practicality of using a container in the first place... I also saw that in #299 a potential PR that might fix this was mentioned, but as far as I can tell it never came...
Is this something you guys would be willing to change the current Docker image to allow for? If so I can poke around and try and get it working...

**Comment by webpro** [comment]
Yes @Ninja73737, feel free to open a PR and I'm happy to look into it.

**Comment by Ninja73737** [comment]
Ok, sounds good, I'll try and get to that this week.

**Comment by Ninja73737** [comment]
Ok so I've done some testing, and while it seems like it might be doable, printing has some bugs, such as #297 , which is kinda a big issue probably for a lot of users, and all the printing methods I've seen seem like they will result in a larger download size, so I don't know if it would be worth adding to the default image.

I've done some looking around though, and came across this: [decktape](https://github.com/astefanutti/decktape). I did some more testing with that, and it seems to print everything correct as far as I can tell, and, it has a docker container! Maybe it would be best to recommend that people use decktape for printing, as it seems to avoid a lot of the current printing issues.

**Comment by webpro** [comment]
Thanks for your work, @Ninja73737! Maybe you could open a PR for the docs with instructions how to use reveal-md and decktape together?

**Comment by Ninja73737** [comment]
Sure, will do! I assume I should put that in the readme, where in the readme do you want me to put it?

**Comment by webpro** [comment]
My first idea would be to make a new section (somewhere between "Features" and "Related Projects & Alternatives"), and link to it from the existing "Print to PDF" subsection.
