### ISSUE TITLE
Custom directory listing

### ISSUE THREAD

**Issue by vvscode** [webpro/reveal-md#346]
As soon as it's possible to use `front matter` for files, it's nice to have an option, how to create `listing` HTML. 

We can defined template (like [default one](https://github.com/webpro/reveal-md/blob/master/lib/template/listing.html) ) but in fact it's not really customizable

Nice to have a chance to setup `getListing` module (file) to pass list of files inside and get HTML as a result

**Comment by vvscode** [comment]
Or add support for some plugins, so it might be implemented with plugin

**Comment by vvscode** [comment]
@webpro  please, take a look =)

**Comment by webpro** [comment]
I understand your issue (there's only pre-rendered HTML for list of files itself). We could add a list of file paths and file names, so you can create a custom Mustache template.

Would that work for you?

**Comment by webpro** [comment]
I just went ahead and refactored the current template to do the same (what was I even thinking by pre-rendering HTML outside the template, lol).

So now in [v4.2.0](https://github.com/webpro/reveal-md/releases/tag/4.2.0) there's a `filePaths` and `fileNames` array to use in a custom template. See the current template for an example.

**Comment by vvscode** [comment]
actually, I was going to use frontmatter info from files (with title and description), so just filenames and paths is not enough for me

Do you see it useful?

**Comment by webpro** [comment]
Right.. yes I definitely see value in this. You (or someone else) up to work on a PR for this?

**Comment by vvscode** [comment]
I have it in the plan for the Christmas holidays =)

**Comment by vvscode** [comment]
Or not that far =)

**Comment by webpro** [comment]
Thanks again, @vvscode, a present for reveal-md users well in advance before Christmas :)

**Comment by engeir** [comment]
Is it also possible to reverse the order of the files listed?

Having the files saved as `YYYY-MM-DD-title.md`, and then reversing the order would place the most recent files at the top, which is a more reasonable behavior at least for me.

**Comment by vvscode** [comment]
@engeir  not at the moment, but you can patch the package with `patch-package`

**Comment by engeir** [comment]
@vvscode Thanks, never heard about that before. Worked perfectly!
