### ISSUE TITLE
Support effects

### ISSUE THREAD

**Issue by piranna** [webpro/reveal-md#35]
Add support for [slide transition](https://github.com/hakimel/reveal.js#slide-transitions) effects and more specially [fragment](https://github.com/hakimel/reveal.js#fragments) effects (I use them too much and don't want to do my keynote in HTML :-P ). Seems this can be done using [HTML comments](https://github.com/hakimel/reveal.js#element-attributes), isn't it?

**Comment by webpro** [comment]
So, what is your issue? The effects don't work with HTML comments?

**Comment by piranna** [comment]
That seems there's no way to define effects with the markdown syntax of reveal-md, but maybe I missed the point: is reveal-md an augmented version of reveal.js markdown syntax, or is a "compiler" of reveral.js keynotes from markdown formatted files? At least this is the impression that give the docs...

**Comment by webpro** [comment]
The reveal-md just hooks into the [Markdown features of reveal.js](https://github.com/hakimel/reveal.js#markdown), so you can write Markdown only (without any HTML such as `<section>` and `<script>` tags), and also acts as a simple service to serve the results. Do a "view source" on a rendered Markdown file and it might make things more clear.

**Comment by piranna** [comment]
I see, so there's no extra markdown features besides the ones or reveal.js and it only to craft the keynote without need to work with html at all (it's done automatically) and host them. Anyway, it's a useful tool too, good job and thnks for your patience! :-)
