### ISSUE TITLE
Copy over images when they're included via <img> tags

### ISSUE THREAD

**Issue by N-Wouda** [webpro/reveal-md#350]
Sometimes I need a little more control over how my images are included, so I use an `<img>` tag directly in my markdown file.

When I then run `reveal-md ./slides --static dist`, the images included using an html tag have not been copied over into the static folder.

When I use regular markdown, reveal-md does the right thing.

A regex is currently used to detect included images:

https://github.com/webpro/reveal-md/blob/476f6a15d6ef22bcd975b2dbebcd06c490aa4375/lib/static.js#L15

This which works for markdown-style images. Ideally, this would be extended to also support html `<img>` tags.

I currently use the following hacky work-around. The image is included using markdown in a comment, so reveal-md's regex recognises the image and copies it over. For actual rendering, the html tag is then used, and the markdown ignored.
```html
<img width="85%" 
     src="images/schema.svg" 
     style="transform: rotate(90deg);  margin-top: -400px;" />

<!--- This hack ensures reveal-md actually copies the svg file -->
<!--- ![Schema](images/schema.svg) --->
```

**Comment by webpro** [comment]
Apologies for the late reply. That would indeed be a nice feature. Are you (or someone else) up for a PR? Happy to assist!

**Comment by N-Wouda** [comment]
No problem, thanks for your response!

I can have a go at this, but it might take a while before I have time to work on it. For now - as before - the work-around is perfectly fine. If I haven't opened a PR in a few months please tag me :).
