### ISSUE TITLE
Is it possible to print multiple slides at once?

### ISSUE THREAD

**Issue by quitequinn** [webpro/reveal-md#355]
Is there anything built in for this? I'm wondering what the best approach is.

**Comment by quitequinn** [comment]
'dream scenario' (since something like this is just a dream)

`reveal-md '*w.md' --print 'pdf/'`

**Comment by webpro** [comment]
There is nothing built-in, but I think a shell script like this should work for you:

```
find demo/*.md -exec ./bin/reveal-md.js {} --print \;
```

You could expand this idea further to export to another directory etc
