### ISSUE TITLE
_static folder appearing in listing

### ISSUE THREAD

**Issue by quitequinn** [webpro/reveal-md#356]
When generating a static version of the package a  _static/_static folder is generated and shows up in the listing. Is there a reason for this folder?

**Comment by quitequinn** [comment]
In the interim I'm just adding `&& rimraf _static/_static` to the end of my build line.

**Comment by webpro** [comment]
That should not happen. When I generate a static export twice, I still get only one `_static` folder:

```
reveal-md slides.md --static
reveal-md slides.md --static
```

Can you reproduce this? Which operating system do you use?

**Comment by quitequinn** [comment]
This seems to be a problem from a prior build that no longer happens.
