### ISSUE TITLE
Consider removing underscore from beginning of generated folders.

### ISSUE THREAD

**Issue by quitequinn** [webpro/reveal-md#358]
Consider removing underscore from the beginning of generated folders. This is especially problematic when including scripts in a static build. I think a lot of people will want to serve reveal-md on Github pages and directories starting with "_" are ignored.

**Comment by quitequinn** [comment]
My solution for this right now is adding a .nojekyll file inside the _static repo on travis build.

**Comment by webpro** [comment]
The default folder is indeed `_static`, but you can override this:

```
reveal-md.js slides.md --static public
```

Are there other problematic folders?

**Comment by quitequinn** [comment]
Inside of the `_static` folder, an `_assets` folder is generated, that's the big issue when using Travis to generate a branch for Github pages.

**Comment by webpro** [comment]
You can use the `--assetsDir myAssets` argument for that.

**Comment by quitequinn** [comment]
I don't see that in the documentation, and when I try it locally it doesn't change anything.

Do you mean ` --static-dirs=assets`? Because I'm trying that and the  `_assets` folder is still being generated.

**Comment by quitequinn** [comment]
I should say that with the recent major update the JS folder is now included in the static directory, so this is no longer an issue since I can access all the assets in one location. 

BUT a `_assets/assets/js/*.js` folder is still being built and probably doesn't need to exist.
<img width="201" alt="Screen Shot 2021-01-28 at 1 34 20 PM" src="https://user-images.githubusercontent.com/2885870/106201596-883d9980-616d-11eb-8b15-9eb2343d4ac6.png">

**Comment by webpro** [comment]
`--assetsDir [dir]` should work, but it only is effective when `--script`, `--css` and/or `--theme` is also used. Please let me know if there's a bug.

All default settings are in https://github.com/webpro/reveal-md/blob/master/lib/defaults.json
