### ISSUE TITLE
Live reload in docker not working without mapping port 35729

### ISSUE THREAD

**Issue by nickto** [webpro/reveal-md#359]
It seems that running
```bash
docker run --rm -p 1948:1948 -v <path-to-your-slides>:/slides webpronl/reveal-md:latest /slides --watch
```
is not enough, because it attempts to access script on port 35729 which is not mapped. Extract from the generated page source: 
```html
<script>
  document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>');
</script>
```
Error from the browser console:
```
GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED
```

One way of fixing it is mapping port 35729 too:
```bash
docker run --rm -p 1948:1948 -p 35729:35729 -v <path-to-your-slides>:/slides webpronl/reveal-md:latest /slides --watch
```
however, it is probably not the optimal solution.

**Comment by webpro** [comment]
Thanks @nickto. I can't think of a better solution. They can't share the same port, so why you think there could/should be a better solution?

**Comment by nickto** [comment]
@webpro. I am not proficient in JavaScript, so treat everything inside this docker as a black box. That's the only reason why I said so. Sorry for the confusion :smile:

**Comment by webpro** [comment]
No worries, Docker is not my area of expertise either :)

I'll leave this open here in case someone has a better idea, in the meantime I'll update the docs with your suggestion.

**Comment by webpro** [comment]
Let's close this issue, I think mapping the port is fine.
