### ISSUE TITLE
How to modify marked's configuration?

### ISSUE THREAD

**Issue by charlax** [webpro/reveal-md#362]
I'd like to provide a custom renderer to marked to support resizing images using plain markdown.

What solution do you recommend?

**Comment by ryzokuken** [comment]
Putting the marked config in a `"markdown"` key in `reveal.json` (basically the reveal.js config) should work?

**Comment by webpro** [comment]
Thanks @ryzokuken, that should work indeed: https://revealjs.com/markdown/#configuring-marked
