### ISSUE TITLE
Config in reveal.json ignored?

### ISSUE THREAD

**Issue by patowod** [webpro/reveal-md#363]
Hi all. Just came across this and am really fascinated. So far everything works like a charm. I run into one problem, though: defining options in reveal.json has no impact at all. Also tried varying other config options from reveal.js documentation — without any luck. I've searched closed issues and read the readme multiple times. Am I missing something? Appreciate any help or hints in the right direction.

`
{
  "controls": false,
  "progress": false
}
`

---

- My Setup: Mac OS Catalina,
- Installed reveal & reveal-md via npm -g …
- reveal.json and reveal-md json are in the root folder together with the test.md

**Comment by webpro** [comment]
Did you put `reveal.json` in the same directory as where you execute `reveal-md`?

**Comment by patowod** [comment]
*That* did the trick! Indeed, I wasn't executing it from within that directory. Thank you very much. 👍

**Comment by chris-aeviator** [comment]
the docs state to put the file `file that must be located at the root directory of the Markdown files and nothing about the context of where the module is executed. This should be fixed.
