### ISSUE TITLE
Refactor `lib` to make the package usable in scripts

### ISSUE THREAD

**Issue by ryzokuken** [webpro/reveal-md#369]
First of all, love the package! Thanks for maintaining it, it has made my life so much easier...

As of right now, the functions in `lib` are set up in an "impure" manner, so while the package works flawlessly as a binary, it's pretty much *only* useful that way. Any external project cannot import it as a library/module.

If the logic of reading the configs was moved to `bin` and the functions in `lib` were made pure functions that only took the config as input parameters, then folks could import these functions and use them in scripts.

**Comment by ryzokuken** [comment]
> You are absolutely right, but I'm not sure if anybody wanted or wants to do this.

I filed this issue because I want it :see_no_evil: 

> Also, I'm certainly open to pull requests to improve the codebase and perhaps open up such possibilities.

I'm not sure if I know enough about the codebase in order to do it myself, but I could certainly try and perhaps make an imperfect PR and iterate over reviews?

**Comment by webpro** [comment]
For sure! Happy to help, assist, review. It's just that I didn't have this need myself, so never really took this into account.

If it helps, feel free to use modern JavaScript (i.e. Node v12/[ES Modules](https://blog.sindresorhus.com/hello-modules-d1010b4e777b)).

**Comment by ryzokuken** [comment]
Are you sure Node v12 qualifies as "modern" these days? :P

**Comment by webpro** [comment]
Feels like we are from a different generation, lol. What I meant is that I like it to run without modification/compilation/build in Node v12 (as Node v10 is EOL).

**Comment by ryzokuken** [comment]
Totally agreed, will look into it as soon as I can.

**Comment by ryzokuken** [comment]
No, this issue is still relevant. Just need to refactor.

**Comment by vvscode** [comment]
@ryzokuken  if it's still valid - I'm ready to help with refactoring. Can you share your needs and ideas?

**Comment by ryzokuken** [comment]
Thanks a ton, @vvscode! I want the core functions to be refactored into a function, perhaps `lib/index.js` that is exported by the module, so it can be imported and called with parameters. The `bin` action would then contain the CLI stuff and call this main function from `lib`.

How does that sound? Once that's done I could write a script that imports this package and does something specific to my needs. The idea is to create an easy-to-use package for my colleagues that sets up a presentation with hardcoded defaults that make sense for us, with the extensibility of JS (as opposed to shell scripts).

**Comment by vvscode** [comment]
I can take care about the first part (refactoring `lib`)

**Comment by ryzokuken** [comment]
Please reopen.

**Comment by TempleOfTemplar** [comment]
> Please reopen.

+

**Comment by vvscode** [comment]
@ryzokuken  I just checked and 

```js
const startServer = require('reveal-md/lib/server')
```

seems working (I mean no need to refactor something to get access to the functions). So the question - what function and what params do you see?

**Comment by webpro** [comment]
Cleaning the repo a bit, so closing this one.
