### ISSUE TITLE
serve vs build discrepancy

### ISSUE THREAD

**Issue by ryzokuken** [webpro/reveal-md#370]
I have an `assets` folder in my project that contains the `theme` directory and additional assets that are required for my theme (like fonts and images) are stored right next to it. The directory tree looks something like this:

```
assets
├── plugins.js
├── template.html
└── theme
    ├── fonts
    │   ├── ...
    ├── igalia.css
    └── images
        ├── ...
```

since the theme file (`igalia.css`) includes relative paths (`fonts/...`), everything works fine in the default "serve" mode. But when I try to build my slides into static HTML by `--static --static-dirs=assets`, both `igalia.css` and the rest of the folder get copied in different locations. More specifically, here is what the output directory look like:

```
_static
├── _assets
│   ├── assets
│   │   ├── plugins.js
│   │   └── theme
│   │       └── igalia.css
│   └── ...
├── assets
│   ├── plugins.js
│   ├── template.html
│   └── theme
│       ├── fonts
│       │   ├── ...
│       ├── igalia.css
│       └── images
│           ├── ...
...
```

with both `_assets/assets/...` and `assets/...`. The theme stops working as expected in this case, obviously. Any ideas on how this could be fixed?

**Comment by webpro** [comment]
Well, that looks like a bug indeed. Will look into it.

**Comment by ryzokuken** [comment]
@webpro If you want to go one way or another and end up picking the static behavior as the correct one, could you still allow switching to the other behavior? That one actually works better in my case since my css file needs to import fonts and images and stuff.

**Comment by cycomanic** [comment]
Any update on this? I'm running into the same issue. I don't have any webcoding experience but can have a stab at it.

**Comment by cycomanic** [comment]
Just another note this also prevents using plugins which have assets, because their assets get references as `./assets/plugin/*` but they would be in the top level directory, when added as static-dirs.

**Comment by ryzokuken** [comment]
Yep. still relevant.

**Comment by ryzokuken** [comment]
Please reopen.

**Comment by NukeManDan** [comment]
I am getting related error, the static build in general will not find the same paths to assets as the live server will. The behavior centers around custom css files as well. I _suspect_ this has to do with the mustache behavior being different between how these are rendered.

**Comment by webpro** [comment]
Considering a structure as described, adding the assets directly in the template seems to work fine:

```
...
<link rel="stylesheet" href="{{{base}}}/assets/theme/igalia.css" />
...
<script src="{{{base}}}/assets/plugins.js"></script>
...
```

Serve

```
reveal-md a.md --template assets/template.html
```

Build

```
reveal-md a.md --static --static-dirs=assets --template assets/template.html
```

Probably that's not what you're doing, can you please elaborate?

**Comment by webpro** [comment]
Closing this one to clean up the repo a bit. Feel free to re-open as necessary.
