### ISSUE TITLE
Any transitionSpeed, please?

### ISSUE THREAD

**Issue by dxps** [webpro/reveal-md#375]
First of all, thank you for making and sharing this great tool.
It totally improves the authoring experience, comparing with the standard HTML approach.

Currently (ver. 5.1.1 at the time of this writing), we have the `transition` option to specify the effect to be used, which is great.

But can we also have a `transitionSpeed` option for setting up the pace, to leverage the [existing transition](https://revealjs.com/transitions/) features of reveal.js too?

Thanks.

**Comment by webpro** [comment]
Please see https://github.com/webpro/reveal-md#revealjs-options

**Comment by dxps** [comment]
Thanks Lars for the feedback! :pray: 
Indeed, silly me, I guess I was in a hurry. :facepalm: 

To summarize for anybody else that might also (like me initially) search on issues for feature, this and any other reveal.js specific options can be specified using a `reveal.json` file. In my concrete case, I just created that file containing:
```json
{
  "transitionSpeed": "fast"
}
```

Of course, you can also have reveal-md specific options declared in `reveal-md.json` file. For example, I had to specify and use a custom vertical separator since my VSCode markdown formatter would change `----` into `---`. Therefore, in this `reveal-md.json` file I have:
```json
{
  "verticalSeparator": "==="
}
```

Furthermore, `theme` can be specified as part of `reveal-md` command line flag, or it could be part of `reveal.json` file, but if it is declared within the markdown file you get another benefit: when using great `reveal-md` tool with VSCode and [vscode-reveal](extension) you can also quickly navigate through slides, while staying in VSCode. Of course, the end result might look better on reveal-md result (because of a `--css file.css` option provided at its startup, but that's a different story):

![image](https://user-images.githubusercontent.com/14140226/122167565-d4227e00-ce83-11eb-90e9-cc74403d27c2.png)


And this is how I'm starting reveal-md:
`reveal-md slides.md -w  --title "Cloud Native Solutions" --theme moon --highlight-theme zenburn --css _/css/dxps-material-oceanic.css`

**Comment by webpro** [comment]
Thanks for this helpful explanation/tutorial, @dxps!
