### ISSUE TITLE
Can't use reveal.json

### ISSUE THREAD

**Issue by mandeeps708** [webpro/reveal-md#38]
I placed the reveal.json file in the `~/reveal-md/demo` and also in `~/reveal-md`. Then I executed `reveal-md a.md` from the demo directory. This gives the following error:
>[SyntaxError: /home/mandeep/reveal-md/demo/reveal.json: Unexpected token R]

---

I cloned from `https://github.com/webpro/reveal-md/` 0.0.19 and followed the README installation guide. Also copied text from the configuration file you linked from [hakimel/reveal.js](https://github.com/hakimel/reveal.js#configuration) 

---

I copied the configuration text from line:
>Reveal.initialize({

 >   // Display controls in the bottom right corner`

till

>parallaxBackgroundVertical: ''
>});

---

And changed controls to false, transition to 'zoom' but it didn't work. 

Do I have to do something else?

I just want to change the transition style and may need to modify some other defaults.

**Comment by webpro** [comment]
Hopefully the update in the readme I just did clarifies it. Let me know if you still have issues.

**Comment by mandeeps708** [comment]
Yes. Thanks for the quick action. 
Actually I was writing `Reveal.initialize({` things. Now I came to know that I've to write only properties.
