### ISSUE TITLE
PDF Printing Issues

### ISSUE THREAD

**Issue by dxps** [webpro/reveal-md#382]
To Lars @webpro and reveal-md community,
     
I have to admit that I really enjoyed creating my first template and delivered a presentation based on it.
It is a nice experience and thank you again for making this possible! :tada: 

[Here](https://github.com/dxps/slideshow_template1) is the template that I am talking about, if you want to test and/or use it.

I would need just one help, please: how can get the slides in PDF to look exactly as the presentation renders on the browser?
I tried:
- Puppeteer option:
   - Ran `reveal-md slides.md --print slides.pdf`
   - Issues:
      - text is left-aligned
      - slides have a white background
- DeckTape option:
   - Having `./show.sh` started and the presentation available at `http://localhost:1948/slides.md#/`
   - Created a local `print` directory just for the printing output
   - Ran and result:
     ```shell
     $ docker run --rm -t --net=host -v /path/to/slideshow_template1/print:/slides astefanutti/decktape 'http://localhost:1948/slides.md#/' slides.pdf
     Loading page http://localhost:1948/slides.md#/ ...
     Loading page finished with status: 200
     Reveal JS plugin activated
     Printing slide #/4      (6/6) ...
     Printed 6 slides
     $
     ```
   - Issues:
      - the font face is different
      - a strange padding partially destroys the layout

For the 2nd option (DeckTape) I had included the output (that is `print/slides.pdf`).

<br/>

Thanks in advance for the help!

**Comment by dxps** [comment]
I know this time could be the holiday season for many of us. Still, any help :question:  It might be related to [this](https://github.com/astefanutti/decktape/issues/151) DeckTape issue.

**Comment by dxps** [comment]
Meanwhile, using `decktape` option and its _size_ CLI could solve stripping content and alignment:
`docker run ... astefanutti/decktape -s 1024x860 reveal 'http://localhost:1948/slides.md#/' test_size_1024x860.pdf`

The only thing I'll still try to solve is using the same font. See currently a side-by-side comparison:
![image](https://user-images.githubusercontent.com/14140226/128758963-f4d0e886-83df-4bd4-bb9e-8f2535607cb2.png)

**Comment by dxps** [comment]
My bad: discovered some CSS path mistakes.
Somehow, an aggressive browser cache prevented me at that time to discover this.
Anyway, it's all good! I left that template available for others, as an example.

Thanks again for the whole community!

**Comment by webpro** [comment]
Thanks for sharing this, @dxps!
