### ISSUE TITLE
Online Demo as Cheat Sheet?

### ISSUE THREAD

**Issue by coolaj86** [webpro/reveal-md#384]
There's a similar project, [Markdown Slides](https://github.com/dadoomer/markdown-slides) that has a Online Demo that also serves as a Cheat Sheet for their markdown-to-reveal conversion:

- Cheat Sheet / Demo: https://da_doomer.gitlab.io/markdown-slides/
- Cheat Sheet / Source: https://raw.githubusercontent.com/dadoomer/markdown-slides/master/example/presentation.md

Do you have something like that?

That project is the best of all that I've encountered so far, but if I had a way to **translate _that_ cheat sheet for _this_ project**, I like the YAML syntax that you're using a bit better that the Markdown Comments that they're using.

**Comment by webpro** [comment]
No this project doesn't have it. It's an excellent idea! Pretty sure there are reveal-md users out there that may want to open a PR with some basics to get started. Or maybe you? Guess it can be hosted using GH Pages.
