### ISSUE TITLE
reveal-md.json options should be relative to cwd or self

### ISSUE THREAD

**Issue by ryzokuken** [webpro/reveal-md#385]
Calling `reveal-md` with a directory runs it recursively on the directory. Also, you can set things like the theme and template path in the `reveal-md.json` file. The paths are taken relative to the markdown file in question, it should be relative to the cwd (where the command is run) or better, relative to the `reveal-md.json` file itself.

**Comment by ryzokuken** [comment]
Yes, this is still relevant.

**Comment by vvscode** [comment]
@ryzokuken   sorry for the delay =)

can you provide some ongoing scenarios, to better understand the context?

**Comment by ryzokuken** [comment]
@vvscode I'd say that atleast the `theme` option in the room `reveal-md.json` should be relative to the file itself or if that's not possible, relative to cwd.

The `theme` option within the files could be relative to the markdown files, I suppose that part does make sense.

**Comment by ryzokuken** [comment]
Please reopen.

**Comment by webpro** [comment]
Closing this one to clean up the repo a bit. Feel free to re-open as necessary.

In general, it's best to open a pull request with a fix.
