### ISSUE TITLE
deployment on Github Pages broken due to _assets directory

### ISSUE THREAD

**Issue by maiermic** [webpro/reveal-md#388]
Deployment on Github Pages is broken, since it does not serve `_assets` directory. It works if I change the directory name and references to it (e.g. the `src` attributes of the script tags in `index.html`) to `assets`.

**package.json**

```json
{
  "scripts": {
    "build": "reveal-md presentation.md --static dist",
    "predeploy": "npm run build",
    "deploy": "NODE_DEBUG=gh-pages gh-pages -d dist",
    "start": "reveal-md presentation.md --watch"
  },
  "devDependencies": {
    "reveal-md": "^5.1.2",
    "gh-pages": "^3.2.3"
  }
}
```

**Comment by webpro** [comment]
You can use `--assets-dir <dirname>` (also see `reveal-md --help` for more options)

**Comment by maiermic** [comment]
Thanks for the hint :+1:
