### ISSUE TITLE
The --static site option does not copy assets from the source directory

### ISSUE THREAD

**Issue by eableson** [webpro/reveal-md#389]
Currently using the docker container for portability and when I use the --static option, it doesn't copy any assets from the /slides directory.

Current use case is using Obsidian for authoring and using the default import assets to the same directory as the document so it would be useful to track any files referenced to be copied to the root of the resulting static site.

**Comment by eableson** [comment]
Followup after looking through the source code in more detail. As noted I'm using Obsidian and by default it uses the wiki style links ![[mypicturepng]]. For the dynamic presentations, I'd written a little preprocessor to convert those links to markdown style links, but it appears that the static site generator only looks at the raw files, not the output from the pre-processor.

**Comment by fidian** [comment]
I am also hitting this problem. A workaround is to ensure only the necessary files are in a folder and use `--static-dir` to copy that folder.

**Comment by fidian** [comment]
I've also noticed that using syntax like the following, the resources are not detected and not copied to the destination folder.

**Comment by webpro** [comment]
Closing this one to clean up the repo a bit.

Should be fixed by @MartenBE in #461.
