### ISSUE TITLE
Modifying data-transition 

### ISSUE THREAD

**Issue by mandeeps708** [webpro/reveal-md#39]
I wrote 
`"backgroundTransition": "slide",`
in reveal.json
and then I try to override it by `data-background-transition="convex"`. But it's not working.

**Comment by webpro** [comment]
That sounds like an issue you're having with reveal.js itself. Or, please provide more details (such as the HTML being rendered, what exactly is not working, etc.).

**Comment by mandeeps708** [comment]
I typed in a present.md file: 
```
---
<section data-transition="zoom" data-background="#FE642E">
Background Slides
</section>
---
<section data-background="#01DFD7" data-background-transition="convex" data-transition="fade">
Changing Background Transitions
</section>
---
```

Also had written the following in the reveal.json file:
```
{
	"controls": false,
	"progress": true, 
	"transition": "zoom",
	"backgroundTransition": "slide",
	"parallaxBackgroundImage": "sea.jpg",
	"parallaxBackgroundSize": "2100px 900px",
	"parallaxBackgroundHorizontal": 200,
        "parallaxBackgroundVertical": 50
	
}
```

When I run the `reveal-md present.md` then the `slide` transition (i.e. in the reveal.json) works not the `convex` one.

**Comment by webpro** [comment]
I think this is about reveal.js itself. reveal-md just passes the options to reveal.js (see `{{{options}}}` in https://github.com/webpro/reveal-md/blob/master/template/reveal.html).

**Comment by mandeeps708** [comment]
I took the following code from the `reveal.js` and added the attribute `data-transition="zoom"` into the `section` tag. This (zoom effect on first slide) didn't work with reveal-md, but it worked fine on reveal.js. 

```html
<section data-transition="zoom">
<h1>Reveal.js</h1>
<h3>The HTML Presentation Framework</h3>
<p>
<small>Created by <a href="http://hakim.se">Hakim El Hattab</a> / <a href="http://twitter.com/hakimel">@hakimel</a></small>
</p>
</section>
```

Can you please help me with this?

**Comment by webpro** [comment]
Does any HTML inside your Markdown get rendered properly?

**Comment by mandeeps708** [comment]
Yes the above section works fine except the transition.

**Comment by webpro** [comment]
I just checked, and a nested `<section>` is generated from the Markdown (the slide separator + the custom HTML `<section>`). I guess reveal.js still picks up the background color, but does not override the transition per slide.

**Comment by mandeeps708** [comment]
Now, is there any hack that would make it work?

**Comment by webpro** [comment]
Not sure, you'd need to dig into the reveal.js codebase. I'm closing this for now.

**Comment by mandeeps708** [comment]
Can you please point me to a particular section to look for? 
Thanks for the help.

**Comment by webpro** [comment]
https://github.com/hakimel/reveal.js#markdown & https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/markdown.js

**Comment by mandeeps708** [comment]
Thank you :+1:
