### ISSUE TITLE
Feature request: A way to show some slides which are hidden in markdown

### ISSUE THREAD

**Issue by vvscode** [webpro/reveal-md#393]
As a presenter, I would like to have a way to display some information on slides and hide it in markdown 

> More specific example - when slides are used for presentation during a lesson, and markdown is used as notes/cheatsheet for students. So some slides like `about presenter`, `sound check` and so on are odd in the markdown view.

It might be done in a way, that we comment some slides in a specific way in markdown, so it's invisible (as well as it can be done with slides separator), but are used to generate the presentation.

What do you think?

**Comment by webpro** [comment]
Did you see the "speaker notes" option? https://github.com/webpro/reveal-md#speaker-notes

**Comment by webpro** [comment]
Sorry, not sure how this would look like and personally not interested in this feature. Feel free to open a PR, and I'm happy to look into it.

**Comment by vvscode** [comment]
The draft idea is to have something like

```
<!-- invisible slide:

## Hello

### this slide is hidden in mardown

 -->
```
