### ISSUE TITLE
Created a nix flake for reveal-md

### ISSUE THREAD

**Issue by sagikazarmark** [webpro/reveal-md#394]
Hello!

I just wanted to stop by and say thank you for creating reveal-md and that I've created a Nix flake for it: https://github.com/sagikazarmark/reveal-md-flake

It was easier for me to create a separate repository first, because I want to use it in my [workshop template](https://github.com/sagikazarmark/workshop-template), but it could also be part of this repo. Let me know if you are interested and I'll try to submit a PR.

**Comment by webpro** [comment]
Thanks, @sagikazarmark!

It doesn't look like a maintenance burden to include a Nix flake in this repo. We could use [release-it's version bumper plugin](https://github.com/release-it/bumper) to also update the version in `flake.nix` with every release, if that's necessary?

**Comment by sagikazarmark** [comment]
I made some progress here: I submitted a PR to the official package repository to include reveal-md: NixOS/nixpkgs#144918

Once it gets merged, the flake won't be necessary.

**Comment by sagikazarmark** [comment]
The referenced PR was merged. The changes should land in unstable in a couple days.

**Comment by sagikazarmark** [comment]
reveal-md is now available in unstable: https://search.nixos.org/packages?channel=unstable&show=nodePackages.reveal-md&from=0&size=50&sort=relevance&type=packages&query=reveal-md
