### ISSUE TITLE
Trying to copy static assets from paths in code examples

### ISSUE THREAD

**Issue by raaaahman** [webpro/reveal-md#396]
Hello,

I use reveal-md for a lesson about HTML. When I write some code examples like:

```html
<img src="images/logo.png"/>
```

And I try to build a static website with:

```bash
reveal-md --static docs --static-files assets
```

I have an error:

```bash
[Error: ENOENT: no such file or directory, lstat 'images/logo.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'images/logo.png'
}
```
Indeed the image does not exists. But this code is supposed to be preformated, not executed.

**Comment by webpro** [comment]
When building a static website from the Markdown slides, reveal-md will copy image(s) to the output directory (since they are part of the presentation).

It could be an option to disable this, though. But it's a pretty specific use case, no?

**Comment by raaaahman** [comment]
It's probably specific indeed, but since I ran into it I feel like opening an issue to see if I'm the only one to be bothered by it.

Thanks for considering my request!
