### ISSUE TITLE
Does reveal-md support fragment ?

### ISSUE THREAD

**Issue by jeud** [webpro/reveal-md#40]
Q 1. Can I do fragment using pure markdown ?
e.g.
This is my list
- Item 1
- Item 2
- Item 3

Q 2. Can I override style sheet e.g. specify my own *mystyle.css* ?

**Comment by webpro** [comment]
1. #21
2. #37

**Comment by jeud** [comment]
@webpro thanks for your reply, I have solved my Q1 with your help, but I still don't understand about how to solve Q2. (Sorry that I have too little background about this)

In case that I just want very small customized style sheet (not really a custom theme) e.g. `img { border: none; }`

Is there really easy way about how to hook *mystyle.css* into the slide ?  If not so would you please explain me little more about how to solve my problem with [#37](https://github.com/webpro/reveal-md/pull/37), do I need to modify the reveal-md's *reveal.html* to hook *mystyle.css* ? if so, will I lost this when upgrading to newer version of reveal-md ?

Thanks so much for your help.

**Comment by webpro** [comment]
You either need to provide `--theme` as a string (e.g. `"black"`), or a path to your own CSS file.

So, unfortunately, you can't _add_ your own stylesheet. You would need to get a theme, modify it, and link to it using the `__theme` option.

Of course you are welcome to fork/PR to make `reveal-md` to what you want it to do.

**Comment by jeud** [comment]
Thanks for the answer, I would be happy to close this issue.
