### ISSUE TITLE
Issue with scipt when using static

### ISSUE THREAD

**Issue by Alexsaphir** [webpro/reveal-md#401]
I have at the top level, plugin, preprocessor,slides,plugin.js, reveal.md,reveal.json. My assets are place at slides/assets and my markdown files inside slides.

When I use the live server, the plugins are loaded correctly, however when building the static site, the html file try to load the plugingsfrom ../_assets in place of _assets.

Launching the ive server with a container and the command `slides/ --watch --disable-auto-open`

reveal-md.json
```json
{
    "separator": "^\n---Slide---\n",
    "verticalSeparator": "^\n___Slide___\n",
    
    "preprocessor": "preprocessor/autoslide-html.js",

    "scripts": [
        "plugin/reveal.js-menu/menu.js",
        "plugin.js"
    ]
}
```

**Comment by oeyoews** [comment]
@Alexsaphir When i use 5.3.0 version, i met the same problems, the following is my reveal-md configuration
- <img width="289" alt="reveal-md" src="https://user-images.githubusercontent.com/72405338/146665578-8d135db5-0976-4691-aa45-129ba6a451aa.png">
- so i downgrade to 5.2.0(but like `staticDir` commands, i can't fint it from reveal-md's cli options, just jave static-dir etc)

**Comment by tonai** [comment]
I have the same issue, but when downgrading to `5.3.0` (or `5.2.0`) I have an issue with my custom theme.

In `5.3.0` (scripts are ok but theme is ko):
```html
<link rel="stylesheet" href="/_assets/assets/smile.css" id="theme" />
[...]
<script src="./_assets/assets/toc.js"></script>
<script src="./_assets/assets/plugin.js"></script>
```

In `5.3.1` (scripts are ko but theme is ok):
```html
<link rel="stylesheet" href="./_assets/assets/smile.css" id="theme" />
[...]
<script src="../_assets/assets/toc.js"></script>
<script src="../_assets/assets/plugin.js"></script>
```

I use the command `npm run reveal-md -- --static --static-dirs=assets --theme assets/smile.css reveal-md.md`.
And `reveal-md.json` is:
```json
{
  "scripts": ["assets/toc.js", "assets/plugin.js"]
}
```

**Comment by webpro** [comment]
I should have tested better and not merge #398. This is reverted in [v5.3.2](https://github.com/webpro/reveal-md/releases/tag/5.3.2)

**Comment by webpro** [comment]
Feel free to check and play with https://github.com/webpro/reveal-md-test if you encounter any more issues.
