### ISSUE TITLE
Feature Request: tag or directive to exclude a block of markdown from slide creation

### ISSUE THREAD

**Issue by jdwolin** [webpro/reveal-md#41]
This is a great project - exactly what I was looking for!  I think many users could benefit from a custom syntax (much like your slide separator --- ) that elminates a block of markdown from the slide creation.  This way slides could be parsed out of a larger text document eliminating the need for a separate slides document.  This would be an awesome feature!

Another feature idea would be to add an option (ie. --jpg) that returns a set of *.jpg images for slides.  This might be accomplished through imagemagick.  This might seem to defeat the point of the whole HTML5 glory but it would have its very necessary uses in things like preview images in notes or web icons, etc.  

Great work thus far!

**Comment by webpro** [comment]
Thanks, good to hear it's useful. Feel free to submit a PR!


On Saturday, July 18, 2015, jdwolin <notifications@github.com> wrote:

> This is a great project - exactly what I was looking for! I think many
> users could benefit from a custom syntax (much like your slide separator
> --- ) that elminates a block of markdown from the slide creation. This way
> slides could be parsed out of a larger text document eliminating the need
> for a separate slides document. This would be an awesome feature!
>
> Another feature idea would be to add an option (ie. --jpg) that returns a
> set of *.jpg images for slides. This might be accomplished through
> imagemagick. This might seem to defeat the point of the whole HTML5 glory
> but it would have its very necessary uses in things like preview images in
> notes or web icons, etc.
>
> Great work thus far!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpro/reveal-md/issues/41>.
>


-- 
Sent from Gmail Mobile
