### ISSUE TITLE
Support for fragments

### ISSUE THREAD

**Issue by darek1024** [webpro/reveal-md#413]
Do you consider adding easy way to include fragments to the source slides?

For instance with different separator?

https://revealjs.com/fragments/

**Comment by webpro** [comment]
Yes I would consider a PR to add support for this. Did you have a syntax in mind? Happy to review a pull request!

**Comment by NukeManDan** [comment]
https://revealjs.com/markdown/#element-attributes is supported, the syntax is not _fantastic_ but it works.

I wish there was a way to interleave with code fragments for example (so different text per code lines highlighted) but presently it's not possible from reaveal.js I think.

**Comment by webpro** [comment]
Thanks @NukeManDan, that seems to be the way. Happy to review PRs that improve this, but I'm going to close this one.
