### ISSUE TITLE
Is it capable of displaying math formulation?

### ISSUE THREAD

**Issue by chunleili** [webpro/reveal-md#415]
Hi guys,
I want to use it as a replacement of beamer, but it seems failed. So I typed the math formulation in latex grammer.

I want it show like this
![image](https://user-images.githubusercontent.com/48758868/169527547-a50f42ca-0762-4566-b3d9-93e526127a2d.png)

but I got this
![image](https://user-images.githubusercontent.com/48758868/169527520-ba7ab15d-d571-4736-b2e1-d357dc7e32e0.png)

**Comment by webpro** [comment]
The https://revealjs.com/math/ is enabled by default.

Please search this repo for "math" or "mathjax" and you may find some help.

**Comment by chunleili** [comment]
> The https://revealjs.com/math/ is enabled by default.
> 
> Please search this repo for "math" or "mathjax" and you may find some help.

thanks!
