### ISSUE TITLE
zenburn.css no longer in highlight.js styles folder after I upgraded to reveal-md 5.3.3 (just now)

### ISSUE THREAD

**Issue by interglobalmedia** [webpro/reveal-md#416]
Hi,

zenburn.css no longer in highlight.js styles folder after I upgraded to reveal-md 5.3.3 (just now). So when I run my local build script to build my static site for my reveal-md presentation, my build broke. And I got the following in the Terminal console:

`npm run build          

> complete-nodejs-developer-zero-to-mastery-docs@1.0.0 build
> rm -rf docs && npx reveal-md content/ --static docs --static-dirs=content/assets --static-dirs=content/attachments docs/

❏ node_modules/reveal.js/dist → docs/dist
❏ node_modules/reveal.js/plugin → docs/plugin
❏ content/assets → docs/assets
❏ content/attachments → docs/attachments
★ docs/index.html
❏ node_modules/highlight.js/styles/zenburn.css → docs/css/highlight/zenburn.css
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, lstat '/Users/mariacam/Development/complete-nodejs-developer-zero-to-mastery-docs/node_modules/highlight.js/styles/zenburn.css'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/mariacam/Development/complete-nodejs-developer-zero-to-mastery-docs/node_modules/highlight.js/styles/zenburn.css'`
  
 I fixed it manually by actually manually inserting a copy of the zenburn.css file inside the highlight.js styles folder in node_modules, and it worked. of course that will mean any time the node_modules folder changes, I will have to re-insert the file, but just thought I would let you know about this issue. Thanks!

**Comment by webpro** [comment]
Right, interesting. Please see https://github.com/highlightjs/highlight.js/issues/3461

It's now at `node_modules/highlight.js/styles/base16/zenburn.css`

Does that help?

**Comment by dvirtz** [comment]
I get the same error. Bypassed it by setting `highlightTheme: github` in the YAML Front matter.

**Comment by webpro** [comment]
Should be fixed in [v5.3.4](https://github.com/webpro/reveal-md/releases/tag/5.3.4)
