### ISSUE TITLE
安装后不识别命令reveal-md

### ISSUE THREAD

**Issue by git136975643** [webpro/reveal-md#418]
window11
yarn add reveal-md -g
安装后使用 reveal-md xx.md报错：
reveal-md : 无法将“reveal-md”项识别为 cmdlet、函数、脚本文件或可运行程序的名称

**Comment by git136975643** [comment]
Command reveal-md not recognized after installation

window11
yarn add reveal-md -g
After installation, use reveal-md xx.md to report an error:
reveal-md : Unable to recognize the 'reveal-md' item as the name of a cmdlet, function, script file, or runnable program

**Comment by webpro** [comment]
That looks like an issue with npm/Yarn on Windows?
