### ISSUE TITLE
Nested list isn't rendered correctly

### ISSUE THREAD

**Issue by raghur** [webpro/reveal-md#43]
```
1. outer 1
    2. inner 1
    1. inner 2
    3. Inner 3
1. Outer 2
1. outer 3

```
produces

![2015-07-30 10_04_39-reveal js](https://cloud.githubusercontent.com/assets/516267/8975867/1d3b164a-36a2-11e5-85f6-4234a625f902.png)

see how the first nested point has moved out to the outer list? Happens with `-`, `*` etc.

**Comment by kevinsimper** [comment]
Why would your nested list start with 2? However I don't think this is related to reveal-md but more reveal.js :)

**Comment by webpro** [comment]
What @kevinsimper said, so I'm closing this one.
