### ISSUE TITLE
watching server vs. static files are not matching file paths

### ISSUE THREAD

**Issue by NukeManDan** [webpro/reveal-md#433]
### https://github.com/NukeManDan/reveal-md-issue

I made a demo, related to #417 perhaps, I cannot get the watching server to properly use the style and plugin pages as presently configured. The _static_ files work in this repo, but _not_ the dev server. 

It might be related to:
https://github.com/webpro/reveal-md/blob/7af468659e43233f1eb11bcb2add43e8fafd43aa/lib/server.js#L41-L42

vs how the static site is handled.

Would love to upstream a solution for this if I can get some help fixing the issue in my example repo :pray:

**Comment by JoshOrndorff** [comment]
Is this fixed by #458 or is this still an issue?

**Comment by webpro** [comment]
Cleaning the repo a bit, feel free to re-open if it's still an issue.
