### ISSUE TITLE
`--static` with `--theme` generate the `index.html` with the wrong path of `theme.css`

### ISSUE THREAD

**Issue by IsshikiHugh** [webpro/reveal-md#439]
For example, there is a theme file and a md file.

```
$ tree
.
├── puzzle.css
└── slides.md
```

And I use `reveal-md slides.md --theme` to render the slides, and everything is fine.

However, if I use `reveal-md slides.md --static slides --theme puzzle.css` or just set `theme: puzzle.css` in the head of `slides.md`, the output will be like this:

```
$ tree -L 3
.
├── puzzle.css
├── slides
│   ├── _assets
│   │   └── puzzle.css
│   ├── css
│   │   └── highlight
│   ├── dist
│   │   ├── reset.css
│   │   ├── reveal.css
│   │   ├── reveal.esm.js
│   │   ├── reveal.esm.js.map
│   │   ├── reveal.js
│   │   ├── reveal.js.map
│   │   └── theme
│   ├── favicon.ico
│   ├── index.html
│   ├── plugin
│   │   ├── highlight
│   │   ├── markdown
│   │   ├── math
│   │   ├── notes
│   │   ├── search
│   │   └── zoom
│   └── slides.html
└── slides.md
```

And the css failed in the final html file.

And if you check `index.html` or `slides.html`..., you will find that:

```
<link rel="stylesheet" href="/_assets/puzzle.css" id="theme" />
```

As long as I change to the right path(`./_assets/puzzle.css`), of course, everything will be ok.

I think it might be a bug, but I am not sure if it is my fault. 

------

I have now achieved my purpose in this way: set the `theme: simple` and set `css: puzzle.css`.

**Comment by TonyCrane** [comment]
Maybe here should pass `base` to `getAssetPath`

https://github.com/webpro/reveal-md/blob/937bd4103b1afa01807a0e29c684c64b4850488d/lib/config.js#L63-L73

**Comment by MartenBE** [comment]
I'm also experiencing this problem, is there any update?
