### ISSUE TITLE
Font rendering regression

### ISSUE THREAD

**Issue by marrowsuck** [webpro/reveal-md#446]
Since version 5.4.0 the font rendering isn't that clear compared to prior versions

Rendering in 5.3.4:
![reveal-5 3 4](https://user-images.githubusercontent.com/1490076/224113813-e5255505-c196-48e0-b3b5-041b900838eb.png)

Rendering in 5.4.0:
![reveal-5 4 0](https://user-images.githubusercontent.com/1490076/224113833-c049af61-39a5-44c1-99ab-66fd3c33e949.png)

Open images in separat windows for better visualization of the issue.

**Comment by webpro** [comment]
This is probably not an issue with reveal-md.

In this time reveal.js itself was also updated from v4.3.1 to v4.4.0 so that could be something to look into.
