### ISSUE TITLE
Feature request: command line options in file

### ISSUE THREAD

**Issue by asifm** [webpro/reveal-md#45]
It'd be nice to store the desired command line options in a file (maybe the same reveal.json options file?) so that one doesn't have to type, for example, `--theme solarized --separator '\n\n\n'` if one always wants those options for an md file. Those stored options will be overwritten when mentioned explicitly on the command line.

**Comment by webpro** [comment]
You can put options in a `reveal.json` file: https://github.com/webpro/reveal-md#options.

**Comment by asifm** [comment]
But can you include these command line options in that file? I tried and it didn't work.
```
"theme": "solarized",
"highlightTheme: "github",
"separator": "^\n\n\n",
"vertical": "^\n\n",
"port": "8888"
```

**Comment by webpro** [comment]
That's a bummer. Apparently in `reveal.json` you can only provide options that will be passed to reveal.js. 

The options handling is a bit messy. If anybody wants to pick that up and submit a PR, that would be appreciated.

What you can always do is simply create an alias, this is exactly what they're for. E.g. in a Unix-y environment:

    alias rmd="reveal-md --separator '\n\n\n'"

**Comment by tommardh** [comment]
There is a pull request, "Add support for YAML front matter in md files", that provides a solution for this. It would be great to get this into reveal-md.

**Comment by paddelkraft** [comment]
coming from the world of Static site generators it felt natural to add YAML front matter support to the .md files so i did this way you can set the properties you want for your presentation in the md file itself.  The pull request has been sitting for 10 days without any action. im considering forking reveal-md toget this functionality out in the wild.

```
---
title: Foobar
separator: <!--s-->
verticalSeparator: <!--v-->
theme: css/theme/solarized.css
---
Foo

Note: test note

<!--s-->

# Bar

<!--v-->
```

**Comment by webpro** [comment]
Going to close this one, as the YAML PR was merged/released.
