### ISSUE TITLE
Image paths referencing parent directory not working

### ISSUE THREAD

**Issue by lecodeski** [webpro/reveal-md#451]
imagine following directory structure:

```
[CWD]
|-- a.png
|-- talk
     |-- main.md
```

in `main.md` there is a reference to a.png which won't resolve in reveal-md:
`![](../a.png)`

OTOH generic MD readers do resolve this reference correctly.

All other constellations, like having the image in the same or in a subdirectory, work just fine.

**Comment by webpro** [comment]
Yes, reveal-md should be started from the root dir. It doesn't support serving files and references to ancestor directories.
