### ISSUE TITLE
Doesn't work with npm v3

### ISSUE THREAD

**Issue by bclinkinbeard** [webpro/reveal-md#46]
npm 3 uses a flat node_modules directory, so the hard coded path of `__dirname + '/../node_modules/reveal.js'` in `server-cli.js` is invalid. There are likely other places where this will be an issue as well.

`require.resolve()` may be the (only?) way to resolve the issue.

**Comment by webpro** [comment]
Thanks for catching this, @bclinkinbeard. There's some ugly path resolving going on in general, so I'll take a look at this soon.

**Comment by webpro** [comment]
Should be fixed in [v0.0.22](https://github.com/webpro/reveal-md/releases/tag/0.0.21).

**Comment by webpro** [comment]
Sorry I screwed up, v0.0.22 should be OK :-)
