### ISSUE TITLE
Request: update to reveal.js 4.6.1

### ISSUE THREAD

**Issue by MartenBE** [webpro/reveal-md#462]
I've tried to try it myself, but got a lot of issues with the slidify functionality I don't really comprehend at the moment. There seems to be a breaking change there.

Note: https://www.npmjs.com/package/reveal.js shows version 4.6.1 instead of 4.6.0 as on their GitHub repo, probably a small bugfix for npm.

**Comment by webpro** [comment]
Yes I just tried to update and it's indeed a breaking change. Don't really have the bandwidth to dive into it myself atm.

**Comment by MartenBE** [comment]
I'm digging deeper and it has something to do with this commit in `reveal.js`: https://github.com/hakimel/reveal.js/commit/31174cbaba128dc3db83ff1a977bda9c2ab3405c . I'll try if I can understand it, but I think I'm out of my league here ...

**Comment by webpro** [comment]
Superseded by #469
