### ISSUE TITLE
?print-pdf can't find local images

### ISSUE THREAD

**Issue by hwang63130** [webpro/reveal-md#467]
Not sure what's wrong. But here is an example `example.md` file. 

When I trying to print the pdf via `http://localhost:1948/example.md/?print-pdf`, the image on the first page is correctly displayed while the local image on the second page is shown missing.

```example.md
# page 1

![img](https://example.site/example-image.png)

---

# page 2

![img](local-image.png)
```

node version 20.9.0
reveal-md version 5.5.2

**Comment by vvscode** [comment]
@hwang63130  can you attach some demo repository to check the issue?

**Comment by hwang63130** [comment]
@vvscode That's for the response. But not sure what went wrong but I still get the same broken link on both of my Windows machines (one with Windows 10 and the other with fresh installed Windows 11/Node LTS/reveal-md). I don't have Linux/Mac machines in hand so I am not sure if it is a Windows-only issue.

**Comment by vvscode** [comment]
Have you inspected the page? Please run build command and attach results here in archive, also what is the directory name for you? Are you using wsl?

**Comment by hwang63130** [comment]
OK. I know what I did wrong. I have been using the url `http://localhost:1948/presentation.md/?print-pdf` instead of `http://localhost:1948/presentation.md?print-pdf`
When switching to the correct url, the local images is shown correctly. 

Sorry for the stupid mistake.

**Comment by hwang63130** [comment]
OK. I know what I did wrong. I have been using the url http://localhost:1948/presentation.md/?print-pdf instead of http://localhost:1948/presentation.md?print-pdf
When switching to the correct url, the local images is shown correctly.

Sorry for the stupid mistake.
