### ISSUE TITLE
Feature Request: export to HTML

### ISSUE THREAD

**Issue by neuromusic** [webpro/reveal-md#47]
I love using reveal.md & how it lets me go quickly from outline to a presentation. However, then I find myself wanting to more carefully tweak a presentation & I want access to the full HTML.

I'd love to be able to run `reveal-md slides.md --html` and get a directory called `slides` with an HTML file & required assets.

**Comment by webpro** [comment]
Not sure if I understand. You can provide a directory and see the Markdown
files. What exactly do you need?

On Sunday, 27 September 2015, Justin Kiggins <notifications@github.com>
wrote:

> I love using reveal.md & how it lets me go quickly from outline to a
> presentation. However, then I find myself wanting to more carefully tweak a
> presentation & I want access to the full HTML.
>
> I'd love to be able to run reveal-md slides.md --html and get a directory
> called slides with an HTML file & required assets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpro/reveal-md/issues/47>.
>


-- 
Sent from Gmail Mobile

**Comment by mandeeps708** [comment]
As I understood, he wants a feature to `export` the presentation `as HTML`. Once the required command is fired, all the `necessary files`(CSS, JS, images etc.) should be stored in a different directory along with an `index.html` file. 
It would be useful for porting the presentation to a different computer(that don't have nodejs and reveal-md) and present it just by double clicking index.html in browser.

**Comment by neuromusic** [comment]
yes, exactly.

**Comment by webpro** [comment]
OK thanks for explanation.

The browser has a "Save page" option that does the same?

On Sunday, 27 September 2015, Justin Kiggins <notifications@github.com>
wrote:

> yes, exactly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpro/reveal-md/issues/47#issuecomment-143528845>.
>


-- 
Sent from Gmail Mobile

**Comment by mandeeps708** [comment]
No. I tried it once, and I got a blank page(on Chrome at least).
@neuromusic Can you please try again and tell?

**Comment by webpro** [comment]
What exactly where the issues? Because if we would have an "export to HTML" feature, it would do pretty much the same, right?

**Comment by rapilabs** [comment]
Would be awesome to just auto gen HTML with a command then push up on gh-pages!

**Comment by rapilabs** [comment]
Saving as a complete web page from Chrome doesn't work.

A few links to resources seem to be generated on the fly with paths like `/plugin/markdown/marked.js`. Saving HTML from Chrome flattens everything in a folder named after the file you save the HTML to and rewrites all the references it found from `<script>` and `<link>` tags.  This rewrite step would be missing the paths embedded in js.

**Comment by jsanz** [comment]
wow yes, an option to export the presentation as a static HTML instead of starting a server would be really awesome!! :+1:

**Comment by xy124** [comment]
I guess I did something like this now :) 
use e.g.
`reveal-md example.md --static > reveal.js/index.html`
As you see you have to download the [reveal.js](https://github.com/hakimel/reveal.js/) to some place and extract the folder to save the exported static html pages right there.

The pull request is this: #55


Maybe some one wants to build something that compiles all assets into one single html file. There probably is already a package somewhere on npm that can do exactly this

**Comment by HoverBaum** [comment]
A bit more on the issue with `Ctrl + S` and temporary solution.

Using `Ctrl + S` I get a website referencing resources as such:
`<link rel="stylesheet" href="./Reveal_files/reveal.css">`

Using `Ctrl + U` to view at the source of the page the link becomes:
`<link rel="stylesheet" href="/css/reveal.css">`

Now the later I can save to an `index.html` and put it in a folder with the `reveal.js` resources to have a html version of the presentation. I feel like this is what @rapilabs was talking about, but hopefully more clearly illustrates the issue with just "saving" the website.

It would be a really great feature to get a single `.html` that I can then just move around and open anywhere. With all the js and css files included. Idealy I think even all the image base64 encoded in it.

**Comment by skorokithakis** [comment]
Thanks, @xy124. I installed this library thinking I could export to HTML, but it's not useful to me if it can't. I'll try using your fork for now, thanks again.
