### ISSUE TITLE
Regexp escape for `!` is missing and causes missing images

### ISSUE THREAD

**Issue by MartenBE** [webpro/reveal-md#473]
See https://github.com/webpro/reveal-md/commit/be811016c12ac9be30c579fffe39fb67e6ebf6b2#commitcomment-136249062

**Comment by webpro** [comment]
The `!` is not a special regex character? My linter was complaining about it being unnecessarily escaped.

**Comment by vvscode** [comment]
looks like we need some screenshot tests =)

**Comment by MartenBE** [comment]
Sorry, there is a mistake in the regex I introduced, but it is not the `!` char, it is the following: the regexp currently only copies images with an alt explanatation because I used + instead of * in the regexp:

Current regexp: `const htmlImageRE = /!\[.+?\]\((.+?)\)/g;`
Shoud be: `const htmlImageRE = /!\[.*?\]\((.+?)\)/g;`

I'll test it out and create a PR the following days. Sorry for the mishap and the wrong hint to the error.

**Comment by MartenBE** [comment]
PR created at https://github.com/webpro/reveal-md/pull/474

**Comment by webpro** [comment]
No need to apologize! Thanks for the fix.
