### ISSUE TITLE
Is it possible to have templates?

### ISSUE THREAD

**Issue by ooker777** [webpro/reveal-md#489]
I want to design 3 slides of one same layout. I need to use custom HTML and CSS for them. Is it possible to have a template, so that I don't have to duplicate the edit when I want to change the layout?

**Comment by webpro** [comment]
There's quite a few options to use custom templates and/or CSS. See e.g. https://github.com/webpro/reveal-md?tab=readme-ov-file#custom-template

**Comment by ooker777** [comment]
Done at #492
