### ISSUE TITLE
Add reveal-js plugins and other dependencies

### ISSUE THREAD

**Issue by garaud** [webpro/reveal-md#50]
Hi,

Is there a way to add some reveal-js plugins or other Javascript dependencies from reveal-md? I know you can use the `dependencies` variable in the `initialize` call as described [here](https://github.com/hakimel/reveal.js/blob/master/README.md#dependencies)

I would like to use some charts js libs in my slides. Maybe it's simpler if I don't use reveal-md and write a *pure* HTML + JS reveal file.

Thanks. Cheers,
Damien

**Comment by webpro** [comment]
With reveal-md, indeed you need to add dependencies in the page template (https://github.com/webpro/reveal-md/blob/master/template/reveal.html). You could fork this into e.g. "reveal-md-charts" and add them.

**Comment by garaud** [comment]
Hi,

Sorry for the delay. I'll do that thanks

**Comment by qsys** [comment]
Just a thought: wouldn't it be a possibility to deep-extend dependencies? This way, the base dependencies would be merged with user-defined dependencies, which is a lot easier than forking if one wants additional third party plugins.

**Comment by webpro** [comment]
Hi @qsys, good idea, but how would that look like? Reveal.js plugins have a `src`, but also might have a `condition` or `callback` function (see https://github.com/webpro/reveal-md/blob/a0c4f7e12ea81f17c1757421dcd406ca71aaa11b/lib/template/reveal.html#L42-L50). Feel free to open a PR to show you'd like this to work.

**Comment by qsys** [comment]
Hey, I have been looking at it for a while, but javascript doesn't seem to have merge/extend like this. I should override single-value attributes, and merge multiple-value attributes. Don't know yet how to do this easily in js. 
For a first version of this feature, I'd just merge multiple-value attributes (like deps), without any other logic. In the future, there may be some more logic (like merging deps with the same 'src' etc). Let me think about it...

**Comment by qsys** [comment]
... or another idea may be to use custom templates (replacing the one provided by reveal-md)?

**Comment by webpro** [comment]
@qsys Adding the option to override the template sounds like a good idea to me :-)
