### ISSUE TITLE
Maybe a link on the README.md?

### ISSUE THREAD

**Issue by jjasghar** [webpro/reveal-md#58]
I created https://github.com/jjasghar/reveal-md-cookbook to help get reveal-md up and running as quickly as possible.

Could it be possible to get a link in the README to that cookbook?

**Comment by webpro** [comment]
Hi @jjasghar. To be honest, I'm not sure what your project adds on top of reveal-md. It seems to be a Chef cookbook? Could you please explain the advantage(s) in one sentence?

**Comment by jjasghar** [comment]
"Setup or deployment  can be hard, this automates the process."

**Comment by webpro** [comment]
Yes I've seen that, but for users of reveal-md (including me) that don't know about Chef (it's a Chef cookbook, right?), might not have a clue as how to install and/or use your project. I for one had no idea, and still don't have.

**Comment by jjasghar** [comment]
I respect that. I just thought it might help, if you want I can write up some detailed usage docs, or you can just close this out.

**Comment by webpro** [comment]
OK thanks. I'm closing this one, but feel free to open a PR in this repo with a link to your project once you feel it's also useful for people not familiar with e.g. cookbooks.
