### ISSUE TITLE
Add Watch option

### ISSUE THREAD

**Issue by lbischof** [webpro/reveal-md#63]
It would be nice to be able to specify `--watch` and have it auto reload when changes are made. This would simplify writing a presentation. What do you think?

**Comment by webpro** [comment]
I think it's a nice idea, but honestly I'm not too interested in implementing it myself. So if anyone is up to it, I'm happy to consider and merge it.

**Comment by lbischof** [comment]
I think only grunt supports watch? I guess it would be harder to add this to the cli tool.

**Comment by webpro** [comment]
I've released this in v0.0.34.
