### ISSUE TITLE
Specify theme with http url

### ISSUE THREAD

**Issue by lbischof** [webpro/reveal-md#65]
Would it be possible to allow urls for the --theme option? Then it would be possible to use custom themes from within any third-party repository and have them auto update. Simply download the css file and put it in the correct directory. I don't exactly understand how the custom theme code is implemented.

**Comment by webpro** [comment]
I think it's a nice idea, but honestly I'm not too interested in implementing it myself. So if anyone is up to it, I'm happy to consider and merge it.

**Comment by webpro** [comment]
Done with #66.
