### ISSUE TITLE
Three level headers should go down

### ISSUE THREAD

**Issue by RangerMauve** [webpro/reveal-md#67]
Since reveal JS has a way to go up and down in the slides, I think it would make sense to make use of this by having `##` second level headers add more slides to the right, and have `###` three level slides nest further down.

**Comment by webpro** [comment]
Not sure what you mean. The (vertical) slide separators can be used to add slides to the right (`---`) or bottom (`----`). Or do you mean something else?

**Comment by RangerMauve** [comment]
OH.

I somehow missed that point. :P My bad.

**Comment by webpro** [comment]
No problem!

**Comment by gauravarora** [comment]
@webpro is there an example of vertical slides somewhere?

**Comment by webpro** [comment]
Yes, it's at https://github.com/webpro/reveal-md/blob/master/demo/a.md
