### ISSUE TITLE
Build Error (on windows 10, with VS 2015)

### ISSUE THREAD

**Issue by tim-c-smith** [webpro/reveal-md#72]
While running the commmand

`npm install -g reveal-md --python=D:\Python\Py27\python.exe`

I get the following error (despite having downloaded and installed WDK8.1)

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.ta
rgets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version o
f Windows SDK or change the SDK version in the project property pages or by right-clicking the soluti
on and selecting "Retarget solution". [C:\Users\tim\AppData\Roaming\npm\node_modules\reveal-md\node_m
odules\reveal.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\n
ode_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
```

**Comment by webpro** [comment]
Hi @tim-c-smith. I'm sorry, I have no idea how I can help you out with this. I'm not running Windows myself and I'm also not sure how this is specific to reveal-md. I'm going to close this issue, but feel free to re-open if you feel otherwise.

**Comment by firoozye** [comment]
I followed the install directions here and had no trouble: [PandaScience: How 2 Install Reveal.js on Windows 10](https://pandascience.net/doku.php?id=how2:revealjs). After, installing reveal-md was quite easy.
