### ISSUE TITLE
Internal links

### ISSUE THREAD

**Issue by firoozye** [webpro/reveal-md#73]
I have tried the HTML version for internal links
`<a href="#/some-slide">click for some-slide/a>`

but 

`<section id="some-slide">`

seems to have no effect except to tag the first page of the presentation.  Strangely, `<section>`  has an influence for other attributes but not for id. Or does this work in some other form? I haven't looked through the code thoroughly enough so I don't know if this is difficult to solve.

It'd be great to have a table of contents for a large slide. Thanks!
(sorry for multiple edits--I'll make sure the code gets commented correctly in the future)

**Comment by webpro** [comment]
You can have internal links, you can check out https://github.com/webpro/reveal-md/blob/master/demo/sub/deep/d.md.
