### ISSUE TITLE
Speaker notes always print

### ISSUE THREAD

**Issue by firoozye** [webpro/reveal-md#76]
While ^Note: should indicate speaker notes, even when the .reveal option is explicitly set not to show, I find that speaker notes sometimes do get shown. 

Is this an issue others have had? I have experimented with putting notes at the beginning and at the end of slides. The only thing that truly is ignored is HTML comments i.e. ,
`<!-- ....  -->`

**Comment by webpro** [comment]
Not sure if it's still relevant, but I'm going to close this one. If anybody still has issues regarding this, please let me know.

**Comment by jarbus** [comment]
Yeah still facing this issue sadly :(

**Comment by jarbus** [comment]
Resolved this by putting speaker notes at the end of every slide, and putting no HTML comments anywhere. Seems to work for now.
