### ISSUE TITLE
Getting --static to work with a user level reveal.js installation

### ISSUE THREAD

**Issue by ncoghlan** [webpro/reveal-md#87]
Attempting to render a presentation as a self-contained reveal.js folder, I had to use the following tricks to get it to work:

- copy the reveal.js folder from ~/node_modules to the local directory
- stop using the YAML header feature to set the theme and page title
- generate the HTML with --static and pipe it to reveal.js/index.html
- search & replace in the generated file to convert `///` references to `./` references
- edit the theme name (passing `--theme` on the command line didn't appear to have any effect)
- copy the images directory into the reveal.js directory

Where would be the appropriate place in the code for me to look for ways to fix some of these and make the --static option easier to use?

**Comment by webpro** [comment]
FYI, I'm working on a complete rewrite of reveal-md, and I will take open tickets into account.

**Comment by webpro** [comment]
@ncoghlan I've just released a new v0.1.0.

Using `--static` (or `--static [dir]`) it should write out the whole static website into the `_static` dir, which can be served statically.

The code should also be easier to scan/read in case of any issues. Happy to hear your findings.

**Comment by mlopezantequera** [comment]
On 0.1.1:

After generating with --static, I still had to do the following steps to get it to work.

- Renamed all references starting with `/` to `./`
- Copy all of my resources (images and videos) from the original location to the new location
- Renamed `css/theme/css/theme/serif.css.css` to `css/theme/serif.css` (For reference, my yaml preamble has this line:  `theme: css/theme/serif.css`

**Comment by webpro** [comment]
* Currently, the generated index.html is expected to be at the root level (hence the `/` links). I will consider to make the links relative (ie. `./`).
* Indeed, you'll have to copy things yourself that this tool is not aware of.
* You should now use just `serif`.

**Comment by ncoghlan** [comment]
Thanks for the update @webpro! As with @mlopezantequera, I needed to make the following updates:

* rename `css/theme/white.css` to just `white` in the YAML header
* find and add a leading `.` to the resource references (while the absolute references work with the local `reveal-md` server, the browser gets confused when opening the static version from a `file:///` URL)
* copy my `image` folder from the parent directory into the `_static` subdirectory

Of those, copying the image directory in manually is probably fine given a mention in the documentation, but it would definitely be helpful if the css and js references were relative by default.

**Comment by webpro** [comment]
I've changed to base for url's to `.` in [v0.1.2](https://github.com/webpro/reveal-md/releases/tag/0.1.2), so that should make your lives slightly easier :-) Closing for now, let me know if you encounter any issues.
