### ISSUE TITLE
data-background-video-loop doesn't work?

### ISSUE THREAD

**Issue by mlopezantequera** [webpro/reveal-md#88]
I can't seem to get this to work as intended:

`<!-- .slide: data-background-video="file.mp4" data-background-video-loop -->`

Is it only me?

**Comment by webpro** [comment]
This is working for me:

```
<!-- .slide: data-background-video="file.mp4" data-background-video-loop="1" -->
Foo

---

<!-- .slide: data-background-video="file.mp4" data-background-video-loop="1" -->

Bar
```

Make sure to leave a blank line between the separator `---` and the comment. Also, the attribute should have some value (I've used `"1"`).

**Comment by mlopezantequera** [comment]
Indeed, adding ="1" worked.

Thanks!
