### ISSUE TITLE
Cannot override highlight-theme from YAML front matter

### ISSUE THREAD

**Issue by SystemFw** [webpro/reveal-md#90]
Hello,
First of all, thanks for creating reveal-md, it's amazing. I am having a problem overriding `highlight-theme` from the front matter. Given these test slides
````Markdown
---
theme: solarized
highlight-theme: solarized-light
---

# Code should not be zenburn
```Scala
def foo: Int => Int = ???
```
````
Using `reveal-md ./*.md` displays the slide theme as solarized, but the code highlighting is still in zenburn;
`reveal-md ./*.md  --highlight-theme solarized-light` on the other hand works correctly.

Is there any reason why is not possible to override `highlight-theme` from the front matter? Or is it indeed possible, but I'm doing something wrong?

**Comment by webpro** [comment]
Hi @SystemFw, please try `highlightTheme`.

**Comment by SystemFw** [comment]
That works, thank you very much.
