### ISSUE TITLE
not able to render link

### ISSUE THREAD

**Issue by digitalsatori** [webpro/reveal-md#91]
Not able to show Link defined  implicitly or explicitly as below:
```
Visit [Daring Fireball][] for more information.

[Daring Fireball]: http://daringfireball.net/
```
```
Visit [Daring Fireball][df] for more information.
And then define the link:

[df]: http://daringfireball.net/
```

**Comment by webpro** [comment]
The markdown plugin of Reveal.js uses [marked](https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/marked.js). I don't think this issue is caused by reveal-md, but by reveal.js, the plugin, or the parser. Feel free to re-open to discuss.

**Comment by digitalsatori** [comment]
I did another test. It seems that the parsing is OK. but the link will be generated only when the link definition is inside the same Section. In the below example, the link in `Section A` won't be generated while the link in `Section B` is good.

```
# Section A
Visit [Daring Fireball][] for more information.

---

#Section B
I Visited [Daring Fireball][]
[Daring Fireball]: http://daringfireball.net/
```

**Comment by webpro** [comment]
Ah unfortunately, reveal.js parses markdown per slide (https://github.com/hakimel/reveal.js#markdown).

**Comment by digitalsatori** [comment]
I tested reveal-ck(https://github.com/jedcn/reveal-ck <https://github.com/jedcn/reveal-ck>) which can render the link as I expected. But I like reveal-md better. Do you think we can do anything to support it?

thank you and best regards,

Tony

**Comment by webpro** [comment]
You might have luck with the [preprocessor feature](https://github.com/webpro/reveal-md#markdown-preprocessor). The function receives the whole markdown document as the first argument, so you can parse it, before it is split into slides.

**Comment by digitalsatori** [comment]
Just noticed your answer, thank you very much. I referred your preprocessor example and managed to hack a dirty solution. I'm not a js coder but the code works 😄 
```js
// This preprocess script will gather all the link definetion in
// markdown text and insert them into each slide. So that, you
// will NOT have to define links used in each slide repeatedly.
module.exports = (markdown, options) => {
    var link_def_re = /\[.+\]:\s+.+/g ;
    var slide_sep_re = /(\n---\n)|(\n----\n)/g ;
    var link_defs = (markdown.match(link_def_re) || []).join('\n');
    if (!link_defs) return markdown;
    return link_defs + "\n" + markdown.replace(slide_sep_re, "$1" + "\n" + link_defs + "\n");
}
```
