### ISSUE TITLE
Add custom styles

### ISSUE THREAD

**Issue by shadowhand** [webpro/reveal-md#94]
I'd like to inject a custom stylesheet (eg: for using a Google Font) without having to make a custom theme. Can a `--styles` parameter be added?

💛

**Comment by webpro** [comment]
Yes, I'm happy to check out a PR that adds this feature.

**Comment by webpro** [comment]
This is released in [v0.2.0](https://github.com/webpro/reveal-md/releases/tag/0.2.0), thanks to @singingknight.
