### ISSUE TITLE
Reference link will be correctly generated only when the link definition is inside the same section

### ISSUE THREAD

**Issue by digitalsatori** [webpro/reveal-md#95]
this is refer to issue #91 . It seems that the parsing is OK. but the link will be generated only when the link definition is inside the same Section. In the below example, the link in Section A won't be generated while the link in Section B is good.

```
# Section A
Visit [Daring Fireball][] for more information.

---

#Section B
I Visited [Daring Fireball][]
[Daring Fireball]: http://daringfireball.net/
```

**Comment by webpro** [comment]
Why did you open a new ticket? We can discuss in the other ticket (even if it's closed).
