### ISSUE TITLE
reveal-md always concatenates the specified preprocess script with CWD

### ISSUE THREAD

**Issue by digitalsatori** [webpro/reveal-md#98]
When I run reveal-md in `~/My/Working/Path` similar like this 
```reveal-md -m ~/other/path/to/script.js my_md.md``` 
the path for preprocess script ended like: `~/My/Working/Path/~/other/path/to/script.js`
my 2 cents, reveal-md should respect the path specified, prepend CWD only when NO path specified for the pre-process script.

BTW, in the project's README, it read `-P` for the preprocessor, should be `-m`

**Comment by webpro** [comment]
Thanks for the catch, @digitalsatori. I've updated the readme. I haven't done anything about the `cwd` issue, but feel free to open a PR.

**Comment by mpacer** [comment]
I actually don't think the readme is updated. it still says `-P` when it should be `-m` based on https://github.com/webpro/reveal-md/blob/master/bin/cli.js#L38.

**Comment by webpro** [comment]
You're right, @mpacer. If somebody would open a PR with this fix, that would be great.
